# Fantasy Trade Calculator

A dynasty/redraft fantasy football trade calculator that trains supervised gradient-boosting
models to predict market consensus value (FantasyCalc, blended with KeepTradeCut) from player
fundamentals, producing one unified value board per format that puts every player and draft pick
on the same directly-comparable scale.

**Consensus value is the training target, not a benchmark to beat.** These models are trained to
reflect the fantasy trade market as closely as possible -- agreement with FantasyCalc/KeepTradeCut
consensus is the design goal, not an independent finding. Where a player's model-predicted value
diverges from their current market price, that divergence is reported as a residual: a candidate
worth investigating, never a claim that the model is right and the market is wrong.

Full methodology, scope, and known exclusions: see `README.md` in this directory.

This notebook is a thin orchestration layer -- all real logic lives in
`trade_calculator_pipeline.py`, which is imported and called stage by stage below.

In [1]:
import pandas as pd

import trade_calculator_pipeline as tcp

pd.set_option("display.max_rows", 250)
pd.set_option("display.max_columns", 50)
pd.set_option("display.width", 160)

## Stage 1 -- ID crosswalk

Built from nflreadpy's `load_ff_playerids()`, the backbone every source join uses.

In [2]:
crosswalk = tcp.build_crosswalk()
print(f"crosswalk rows: {len(crosswalk)}")
crosswalk.head()

crosswalk rows: 12472

   mfl_id  sleeper_id    espn_id     gsis_id  ktc_id    pfr_id                name position          merge_name
0   17462     13269.0  4837248.0  00-0041562  1924.0  MendFe00    Fernando Mendoza       QB    fernando mendoza
1   17463     13275.0  4685522.0  00-0041568  1925.0  SimpTy00          Ty Simpson       QB          ty simpson
2   17464         NaN        NaN         NaN     NaN       NaN  Trinidad Chambliss       XX  trinidad chambliss
3   17465     13404.0  4567747.0  00-0040906  1927.0  NussGa00   Garrett Nussmeier       QB   garrett nussmeier
4   17466     13272.0  4430841.0  00-0041561  1928.0  BeckCa01         Carson Beck       QB         carson beck

## Stage 2 -- Pull FantasyCalc (6 format-teamsize combos) and KeepTradeCut (dynasty + redraft)

In [3]:
fc_all = tcp.pull_all_fantasycalc()
for k, v in fc_all.items():
    print(f"  {k}: {len(v)} rows")

ktc_dyn = tcp.pull_ktc_dynasty()
ktc_redraft = tcp.pull_ktc_redraft()
print(f"ktc_dynasty: {len(ktc_dyn)} rows, ktc_redraft: {len(ktc_redraft)} rows")

  ('sf_dynasty', 10): 475 rows
  ('sf_dynasty', 12): 475 rows
  ('oneqb_dynasty', 10): 475 rows
  ('oneqb_dynasty', 12): 475 rows
  ('redraft', 10): 171 rows
  ('redraft', 12): 171 rows

ktc_dynasty: 500 rows, ktc_redraft: 300 rows

### Blend example -- SF dynasty, 12 team

A quick look at one format's crosswalk join + percentile blend before running the full 6-combo
version in Stage 7.

In [4]:
fc_joined_demo = tcp.join_fantasycalc_crosswalk(fc_all[("sf_dynasty", 12)], crosswalk, label="FC-SF12")
ktc_joined_demo = tcp.join_ktc_crosswalk(ktc_dyn, crosswalk, label="KTC-dyn")
blended_demo = tcp.blend_consensus(fc_joined_demo, ktc_joined_demo, ktc_value_col="sf_value")
blended_demo[["name", "position", "value", "ktc_percentile", "fc_percentile", "consensus_value"]] \
    .sort_values("consensus_value", ascending=False).head(15)

[FC-SF12] 1 rows matched via normalized-name fallback (documented last resort)
[FC-SF12] 1 unmatched after fallback: ['Matt Hibner']
[FC-SF12] top-200 join coverage: 100.0%
[KTC-dyn] 7 unmatched after fallback: ['Hassan Haskins', 'Stetson Bennett', 'Dylan Laube', 'Thomas Fidone', 'Sterling Shepard', 'Foster Moreau', 'Tim Patrick']
[KTC-dyn] top-200 join coverage: 100.0%

                  name position  value  ktc_percentile  fc_percentile  consensus_value
0       Bijan Robinson       RB  10438       99.890591     100.000000     10405.618873
1           Josh Allen       QB  10225       99.562363      99.748744     10215.767328
2         Jahmyr Gibbs       RB  10189       99.890591      99.497487     10208.844721
3        Ja'Marr Chase       WR  10080       99.343545      99.246231     10095.560303
4   Jaxon Smith-Njigba       WR   8777       99.124726      98.994975      9025.013154
5           Drake Maye       QB   8595       98.905908      98.743719      8638.302373
6           Puka Nacua       WR   8308       98.687090      98.492462      8389.941414
7         Brock Bowers       TE   7606       98.468271      98.241206      7839.832817
9    Amon-Ra St. Brown       WR   7264       98.249453      97.738693      7288.166341
8        Lamar Jackson       QB   7297       97.592998      97.989950      7279.461681
10       Ashton Jeanty       RB   7243       97.811816      97.487437      7252.992855
11      Caleb Williams       QB   7143       98.030635      97.236181      7245.762163
12      Jayden Daniels       QB   7060       96.717724      96.984925      7048.060656
13          Joe Burrow       QB   7025       96.498906      96.733668      6994.765474
14    Justin Jefferson       WR   6922       96.936543      96.482412      6990.617607

## Stage 3 -- Feature assembly

Draft capital, season-level production/efficiency, continuous position-specific aging curves, and
combine metrics (RB speed score).

In [5]:
draft_capital = tcp.load_draft_capital(crosswalk)
print(f"draft_capital rows: {len(draft_capital)}")

weekly = tcp.load_weekly_features()
print(f"weekly/season feature rows: {len(weekly)}, cols: {len(weekly.columns)}")

curve_params, peak_ages, aged = tcp.fit_aging_curves(weekly, draft_capital)
print(f"peak ages by position: { {k: round(v, 1) for k, v in peak_ages.items()} }")

combine_feats = tcp.load_combine_features()
print(f"combine feature rows: {len(combine_feats)}")
combine_feats.dropna(subset=["speed_score"]).head(3)

[draft_capital] 2 duplicate gsis_id rows in load_draft_picks -- keeping first (data-entry dupes, e.g. supplemental draft)
[draft_capital] 73 rows had a non-gsis id from load_draft_picks (new/unplayed draft class) -- 73/73 repaired via crosswalk name match
[draft_capital] 1 rows still unresolved after repair attempt: ['Mike Washington Jr.']
draft_capital rows: 3551

[snap_share] 1.0% of player-season snap rows unmatched to gsis_id via pfr_id (dropped)
weekly/season feature rows: 4191, cols: 27
[aging_curve] 1261 / 4191 player-seasons have no draft-capital age match (undrafted players) -- age kept as NaN, excluded only from curve fitting
peak ages by position: {'QB': 27.0, 'RB': np.float64(26.0), 'WR': np.float64(27.2), 'TE': np.float64(32.2)}

[combine] 35.1% of combine rows unmatched to gsis_id via pfr_id
combine feature rows: 1954

        gsis_id  forty_time  combine_weight combine_height  speed_score
56   00-0019641        4.45           216.0           5-10   110.165016
118  00-0020514        4.38           207.0            5-9   112.487405
125  00-0020270        4.53           226.0            6-0   107.336054

### Rookie college-production features (CollegeFootballData)

Dominator rating (80% yardage / 20% TD weighted share of team receiving output) and breakout age
for the current draft class. **Note:** CFBD's free-tier monthly call quota can be exhausted at
build time -- if so, this degrades gracefully to `NaN` for affected rookies, who then fall back to
draft capital + age + combine speed score alone (`HistGradientBoostingRegressor` handles missing
features natively; see README's "Known exclusions").

In [6]:
rookie_college = tcp.compute_rookie_college_features(draft_capital, draft_year=2026)
coverage = (rookie_college["college_seasons_found"] > 0).mean()
print(f"2026 rookie CFBD college-production coverage: {coverage:.1%}"
      + ("  (degraded -- CFBD quota likely exhausted this cycle)" if coverage < 0.3 else ""))
rookie_college.sort_values("dominator_rating", ascending=False).head(10)

[cfbd_rookie] 0.0% of 2026 skill draftees matched to >=1 CFBD college season with usable receiving-dominator data (QBs excluded from this stat by design)
2026 rookie CFBD college-production coverage: 0.0%  (degraded -- CFBD quota likely exhausted this cycle)

      gsis_id  dominator_rating  breakout_age  college_seasons_found
0  00-0041562               NaN           NaN                      0
1  00-0041027               NaN           NaN                      0
2  00-0041438               NaN           NaN                      0
3  00-0041029               NaN           NaN                      0
4  00-0041568               NaN           NaN                      0
5  00-0041032               NaN           NaN                      0
6  00-0040867               NaN           NaN                      0
7  00-0041547               NaN           NaN                      0
8  00-0041511               NaN           NaN                      0
9  00-0041512               NaN           NaN                      0

## Stage 4 -- Draft pick valuation

2027-2029 x rounds 1-3 x {Early, Mid, Late} tiers, priced from native FantasyCalc/KeepTradeCut
market data where available, constructed via a year-discount/class-strength/format-multiplier
formula elsewhere. Redraft formats have no pick assets.

In [7]:
pick_universe = tcp.build_pick_universe(fc_all, ktc_dyn)
print(f"pick_universe rows: {len(pick_universe)}")
pick_universe[(pick_universe["format"] == "sf_dynasty") & (pick_universe["team_size"] == 12)] \
    .sort_values("pick_value", ascending=False)[["year", "round", "tier", "fc_value", "pick_value"]]

[format_multiplier] overall mean SF/1QB pick-value ratio: 1.060
[format_multiplier] by round: {1: 1.061, 2: 1.061, 3: 1.06, 4: 1.059}
[format_multiplier] NOTE: spec §6 cites a 30-60% player-level SF premium for elite QBs; picks came out much lower (~6%). That's expected, not a bug -- a pick is position-agnostic (might become a WR/RB/etc.), so it can't carry a specific elite-QB premium the way a known franchise QB player does.

[pick_universe] 36 native FC tier prices, 72 FC-derived (aggregate x tier-ratio), 0 fully constructed (of 108 total)
pick_universe rows: 108

    year  round   tier     fc_value   pick_value
27  2027      1  Early  4532.000000  5389.500000
36  2028      1  Early  3190.750270  3885.937676
28  2027      1    Mid  2984.000000  3862.850000
29  2027      1   Late  2297.000000  3237.800000
37  2028      1    Mid  2101.090720  2966.258968
45  2029      1  Early  2910.832307  2910.832307
30  2027      2  Early  1843.000000  2496.450000
38  2028      1   Late  1617.233964  2476.402076
31  2027      2    Mid  1528.000000  2179.350000
39  2028      2  Early  1583.333802  2142.166971
32  2027      2   Late  1316.000000  1928.150000
46  2029      1    Mid  1916.766350  1916.766350
40  2028      2    Mid  1312.155871  1901.501316
41  2028      2   Late  1130.277642  1723.080467
33  2027      3  Early  1154.000000  1646.800000
48  2029      2  Early  1526.917570  1526.917570
34  2027      3    Mid  1027.000000  1525.400000
47  2029      1   Late  1475.357352  1475.357352
42  2028      3  Early  1070.648419  1471.871472
35  2027      3   Late   945.000000  1390.200000
43  2028      3    Mid   952.766470  1365.498206
49  2029      2    Mid  1265.402060  1265.402060
44  2028      3   Late   876.816018  1265.030412
50  2029      2   Late  1090.004387  1090.004387
51  2029      3  Early  1063.872163  1063.872163
52  2029      3    Mid   946.736303   946.736303
53  2029      3   Late   871.266550   871.266550

## Stage 5 -- Unified feature table

One row per player, "entering the 2026 season" snapshot: most-recent-season production plus
career aggregates (kept separate from single-season stats and from age -- never blended into one
composite score), current age, draft capital, combine metrics, and rookie college-production
features all in one table keyed on `gsis_id`.

In [8]:
snapshot = tcp.build_player_snapshot(aged, draft_capital, peak_ages)
feature_table = tcp.build_feature_table(snapshot, draft_capital, combine_feats, rookie_college)
feature_table[["gsis_id", "position", "current_age", "career_games", "ppg_ppr"]].head()

[snapshot] 1422 player rows (73 zero-snap 2026 rookies appended with NaN production/career features)

[feature_table] 1422 rows, 43 columns

      gsis_id position  current_age  career_games    ppg_ppr
0  00-0019596       QB         49.0          66.0  15.980000
1  00-0020531       QB         47.0          23.0  17.456667
2  00-0021206       QB         47.0           2.0   0.380000
3  00-0022127       TE         44.0          26.0   3.190000
4  00-0022787       QB         45.0           6.0  -0.400000

## Stage 6 -- Consensus targets for all 6 format-teamsize combos

In [9]:
consensus_targets = tcp.build_all_consensus_targets(fc_all, ktc_dyn, ktc_redraft, crosswalk)
for k, v in consensus_targets.items():
    print(f"  {k}: {len(v)} players with a consensus target")

[KTC-dyn] 7 unmatched after fallback: ['Hassan Haskins', 'Stetson Bennett', 'Dylan Laube', 'Thomas Fidone', 'Sterling Shepard', 'Foster Moreau', 'Tim Patrick']
[KTC-dyn] top-200 join coverage: 100.0%
[ktc_redraft_bridge] 281/300 rows bridged to dynasty-page playerID by name (93.7%)

[KTC-redraft] 14 unmatched after fallback: ['Joe Mixon', 'Nick Chubb', 'Miles Sanders', 'DeAndre Hopkins', 'Adam Thielen', 'Jermaine Burton', 'Tyler Lockett', 'Hunter Renfrow', 'Austin Ekeler', 'Brandin Cooks', 'Zay Jones', 'Taysom Hill', 'Russell Wilson', 'Raheem Mostert']
[KTC-redraft] top-200 join coverage: 99.5%

[FC-sf_dynasty10] 1 rows matched via normalized-name fallback (documented last resort)
[FC-sf_dynasty10] 1 unmatched after fallback: ['Matt Hibner']
[FC-sf_dynasty10] top-200 join coverage: 100.0%

[FC-sf_dynasty12] 1 rows matched via normalized-name fallback (documented last resort)
[FC-sf_dynasty12] 1 unmatched after fallback: ['Matt Hibner']
[FC-sf_dynasty12] top-200 join coverage: 100.0%

[FC-oneqb_dynasty10] 1 rows matched via normalized-name fallback (documented last resort)

[FC-oneqb_dynasty10] 1 unmatched after fallback: ['Matt Hibner']
[FC-oneqb_dynasty10] top-200 join coverage: 100.0%

[FC-oneqb_dynasty12] 1 rows matched via normalized-name fallback (documented last resort)
[FC-oneqb_dynasty12] 1 unmatched after fallback: ['Matt Hibner']
[FC-oneqb_dynasty12] top-200 join coverage: 100.0%

[FC-redraft10] top-200 join coverage: 100.0%

[FC-redraft12] top-200 join coverage: 100.0%
  ('sf_dynasty', 10): 398 players with a consensus target
  ('sf_dynasty', 12): 398 players with a consensus target
  ('oneqb_dynasty', 10): 398 players with a consensus target
  ('oneqb_dynasty', 12): 398 players with a consensus target
  ('redraft', 10): 171 players with a consensus target
  ('redraft', 12): 171 players with a consensus target

## Stage 7 -- Fit all 6 models

One `HistGradientBoostingRegressor` per format-teamsize combo, trained on `log(consensus_value)`
with `position` as a native categorical feature, validated via 10-fold out-of-fold cross-validated
predictions (not train-set fit metrics). A `RandomForestRegressor` (imputed/encoded) serves as a
comparison baseline. Zero-snap rookies get an auxiliary lower-quantile prediction as their final
value instead of the mean -- a genuine predictive-uncertainty discount, never a neutral risk
multiplier.

**Sample-weighted training.** `HistGradientBoostingRegressor`'s default `min_samples_leaf=20`,
combined with this project's ~379-row training pool, structurally forces the top ~15-20 "elite tier"
players -- in any position, any format -- into leaves blended with lower-value neighbors, since every
leaf must average at least 20 samples. That systematically compresses predictions for the most
valuable assets (first surfaced as superflex elite-QB underprediction -- Josh Allen, Lamar Jackson,
Jayden Daniels were predicted well below their own training target -- then confirmed as a general,
position-agnostic effect across the whole board). The fix: every training row is weighted by its own
percentile rank in that format's `consensus_value` distribution (`weight = 1 + percentile**3`,
purely a function of where a row sits in its own format's target -- no position or format is
special-cased anywhere), combined with a lower `min_samples_leaf` (10). Verified across all 6 formats
with a multi-seed robustness check: this fixes the elite-QB compression as well as an earlier
QB-only board-assembly blend did, *and* also fixes the smaller RB/WR/TE top-of-board compression that
blend never touched, with Spearman/MAE flat-to-improved everywhere -- not a tradeoff against overall
accuracy. See `trade_calculator_pipeline.py`'s module comment above `fit_format_model` for the full
diagnosis, including the two earlier fixes (a QB-only model split, a starter-status feature) that
were tried and honestly ruled out first.

In [10]:
fit_results = tcp.fit_all_format_models(feature_table, consensus_targets)

validation_rows = []
for (fmt, team_size), res in fit_results.items():
    hm, rm = res["hgb_metrics"], res["rf_metrics"]
    validation_rows.append({
        "format": fmt, "team_size": team_size,
        "hgb_spearman": hm["spearman"], "hgb_mae": hm["mae"], "hgb_top50_mae": hm["top50_mae"],
        "rf_spearman": rm["spearman"], "rf_mae": rm["mae"],
    })
validation_df = pd.DataFrame(validation_rows)
validation_df

[sf_dynasty-10] dropping 2 feature(s) with <2 distinct values in this group: ['breakout_age', 'dominator_rating']

[sf_dynasty-10] rookie quantile discount: 55 rookies in training pool, mean-model vs quantile-model prediction reduced by 7.4% on average
[sf_dynasty-10] n=379  HGBR: spearman=0.826 mae=649 top50_mae=1574  |  RF baseline: spearman=0.827 mae=655 top50_mae=1816
[sf_dynasty-12] dropping 2 feature(s) with <2 distinct values in this group: ['breakout_age', 'dominator_rating']

[sf_dynasty-12] rookie quantile discount: 55 rookies in training pool, mean-model vs quantile-model prediction reduced by 8.4% on average
[sf_dynasty-12] n=379  HGBR: spearman=0.826 mae=671 top50_mae=1694  |  RF baseline: spearman=0.830 mae=659 top50_mae=1834
[oneqb_dynasty-10] dropping 2 feature(s) with <2 distinct values in this group: ['breakout_age', 'dominator_rating']

[oneqb_dynasty-10] rookie quantile discount: 55 rookies in training pool, mean-model vs quantile-model prediction reduced by 10.4% on average
[oneqb_dynasty-10] n=379  HGBR: spearman=0.838 mae=562 top50_mae=1484  |  RF baseline: spearman=0.827 mae=596 top50_mae=1729
[oneqb_dynasty-12] dropping 2 feature(s) with <2 distinct values in this group: ['breakout_age', 'dominator_rating']

[oneqb_dynasty-12] rookie quantile discount: 55 rookies in training pool, mean-model vs quantile-model prediction reduced by 7.3% on average
[oneqb_dynasty-12] n=379  HGBR: spearman=0.832 mae=566 top50_mae=1478  |  RF baseline: spearman=0.829 mae=596 top50_mae=1753
[redraft-10] dropping 2 feature(s) with <2 distinct values in this group: ['breakout_age', 'dominator_rating']

[redraft-10] rookie quantile discount: 13 rookies in training pool, mean-model vs quantile-model prediction reduced by 11.9% on average
[redraft-10] n=169  HGBR: spearman=0.749 mae=916 top50_mae=1708  |  RF baseline: spearman=0.759 mae=997 top50_mae=2003
[redraft-12] dropping 2 feature(s) with <2 distinct values in this group: ['breakout_age', 'dominator_rating']

[redraft-12] rookie quantile discount: 13 rookies in training pool, mean-model vs quantile-model prediction reduced by 9.4% on average
[redraft-12] n=169  HGBR: spearman=0.762 mae=938 top50_mae=1776  |  RF baseline: spearman=0.755 mae=1000 top50_mae=1980

          format  team_size  hgb_spearman     hgb_mae  hgb_top50_mae  rf_spearman      rf_mae
0     sf_dynasty         10      0.825811  648.982733    1574.019203     0.827224  655.211900
1     sf_dynasty         12      0.825908  671.331900    1693.519590     0.829865  658.916162
2  oneqb_dynasty         10      0.837936  562.359649    1483.791518     0.827190  596.086571
3  oneqb_dynasty         12      0.832218  565.691007    1478.093798     0.829192  596.458401
4        redraft         10      0.748991  916.329457    1708.457414     0.758863  997.177118
5        redraft         12      0.762133  937.583014    1776.299493     0.755363  999.735531

## Stage 8 -- Board assembly

Every player the model produced a final prediction for, plus (dynasty formats only) the 27 pick
assets, all on the same `model_value` scale -- the trade-calculator itself: any two assets, player
or pick, are now directly comparable.

In [11]:
boards = tcp.build_all_boards(feature_table, crosswalk, consensus_targets, pick_universe, fit_results)
for (fmt, team_size), board in boards.items():
    n_players = (board["asset_type"] == "player").sum()
    n_picks = (board["asset_type"] == "pick").sum()
    print(f"  {fmt}-{team_size}: {len(board)} rows ({n_players} players, {n_picks} picks)")

  sf_dynasty-10: 406 rows (379 players, 27 picks)
  sf_dynasty-12: 406 rows (379 players, 27 picks)
  oneqb_dynasty-10: 406 rows (379 players, 27 picks)
  oneqb_dynasty-12: 406 rows (379 players, 27 picks)
  redraft-10: 169 rows (169 players, 0 picks)
  redraft-12: 169 rows (169 players, 0 picks)

### Top 15, SF dynasty (12-team) -- eye-test sanity check

Should be recognizable star players, maybe a high pick mixed in near the very top -- **not** a
bottom-tier pick outranking Bijan Robinson.

In [12]:
boards[("sf_dynasty", 12)][["board_rank", "name", "position", "asset_type", "model_value", "consensus_value"]].head(15)

    board_rank                name position asset_type   model_value  consensus_value
0            1        Jahmyr Gibbs       RB     player  10362.818432     10208.844721
1            2      Bijan Robinson       RB     player  10248.266589     10405.618873
2            3       Ja'Marr Chase       WR     player  10036.008580     10095.560303
3            4          Josh Allen       QB     player   9893.008528     10215.767328
4            5  Jaxon Smith-Njigba       WR     player   8933.460219      9025.013154
5            6          Drake Maye       QB     player   8550.250195      8638.302373
6            7          Puka Nacua       WR     player   8371.281334      8389.941414
7            8        Brock Bowers       TE     player   8001.179628      7839.832817
8            9   Amon-Ra St. Brown       WR     player   7377.248456      7288.166341
9           10       Ashton Jeanty       RB     player   7223.761665      7252.992855
10          11      Caleb Williams       QB     player   7143.461288      7245.762163
11          12       Lamar Jackson       QB     player   7068.318791      7279.461681
12          13          Joe Burrow       QB     player   6956.128130      6994.765474
13          14        Malik Nabers       WR     player   6878.900184      6870.087268
14          15    Justin Jefferson       WR     player   6871.652549      6990.617607

## Top 200 -- every board

The full trade-calculator board for each of the 6 format-teamsize combos.

### Superflex Dynasty -- 10 team -- Top 200

In [13]:
boards[("sf_dynasty", 10)][
    ["board_rank", "name", "position", "asset_type", "model_value", "consensus_value", "current_age"]
].head(200)

     board_rank                    name position asset_type   model_value  consensus_value  current_age
0             1            Jahmyr Gibbs       RB     player  10423.362719     10347.101883         24.0
1             2          Bijan Robinson       RB     player  10279.126745     10509.841958         24.0
2             3           Ja'Marr Chase       WR     player   9921.971395      9996.099117         26.0
3             4              Josh Allen       QB     player   9635.181424      9953.403599         30.0
4             5      Jaxon Smith-Njigba       WR     player   8948.228134      8949.078601         24.0
5             6              Drake Maye       QB     player   8377.780022      8416.597602         24.0
6             7              Puka Nacua       WR     player   8293.388719      8277.130609         25.0
7             8            Brock Bowers       TE     player   7882.440078      7794.500436         23.0
8             9       Amon-Ra St. Brown       WR     player   7350.404406      7293.766710         26.0
9            10           Ashton Jeanty       RB     player   7160.420525      7297.713225         22.0
10           11          Caleb Williams       QB     player   7008.313199      7084.781987         24.0
11           12           Lamar Jackson       QB     player   6946.880958      7091.144735         29.0
12           13            Malik Nabers       WR     player   6805.348917      6822.899164         23.0
13           14          Jayden Daniels       QB     player   6791.329979      6834.000000         25.0
14           15              Joe Burrow       QB     player   6782.311388      6813.930726         29.0
15           16        Justin Jefferson       WR     player   6701.572181      6880.220353         27.0
16           17            Trey McBride       TE     player   6528.147041      6492.369963         26.0
17           18             CeeDee Lamb       WR     player   6509.392150      6476.426122         27.0
18           19         Omarion Hampton       RB     player   5998.265559      5949.261338         23.0
19           20           De'Von Achane       RB     player   5975.763569      5917.584019         24.0
20           21          Justin Herbert       QB     player   5910.684550      5885.906699         28.0
21           22            Drake London       WR     player   5739.045118      5854.803169         25.0
22           23         Jonathan Taylor       RB     player   5432.163432      5384.078562         27.0
23           24        Colston Loveland       TE     player   5423.180452      5378.480955         22.0
24           25    2027 Round 1 (Early)     PICK       pick   5397.950000      5397.950000          NaN
25           26       Tetairoa McMillan       WR     player   5263.893109      5104.292371         23.0
26           27             Jalen Hurts       QB     player   5222.509149      5107.755639         28.0
27           28              James Cook       RB     player   5196.623106      5220.240886         26.0
28           29         Patrick Mahomes       QB     player   5131.409421      5207.954348         30.0
29           30         Trevor Lawrence       QB     player   5054.489731      5007.704710         26.0
30           31          George Pickens       WR     player   4931.116471      4876.536967         25.0
31           32                  Bo Nix       QB     player   4925.499187      4814.827952         26.0
32           33            Tyler Warren       TE     player   4885.576820      4832.755897         24.0
33           34            Emeka Egbuka       WR     player   4799.561359      4853.398727         23.0
34           35             Jaxson Dart       QB     player   4640.506627      4835.921228         23.0
35           36          Jeremiyah Love       RB     player   4494.874502      6862.726563         21.0
36           37      Kenneth Walker III       RB     player   4489.235979      4453.224558         25.0
37           38            Carnell Tate       WR     player   4377.565609      4517.665476         21.0
38           39             Brock Purdy       QB     player   4359.341284      4453.913196         26.0
39           40            Nico Collins       WR     player   4311.357926      4310.335936         27.0
40           41             Chase Brown       RB     player   4283.806501      4357.702344         26.0
41           42     Christian McCaffrey       RB     player   4263.459411      4296.182310         30.0
42           43            Dak Prescott       QB     player   4083.537489      3914.681191         33.0
43           44          Garrett Wilson       WR     player   4055.273551      4137.166011         26.0
44           45             Zay Flowers       WR     player   3981.626271      3917.397544         25.0
45           46           Ladd McConkey       WR     player   3963.550883      3941.580075         24.0
46           47             Chris Olave       WR     player   3939.825248      4354.241041         26.0
47           48             Breece Hall       RB     player   3930.687537      3840.034933         25.0
48           49             Jordan Love       QB     player   3926.294034      4119.728533         27.0
49           50            Jordyn Tyson       WR     player   3910.467147      3912.385769         22.0
50           51    2028 Round 1 (Early)     PICK       pick   3892.070710      3892.070710          NaN
51           52          Saquon Barkley       RB     player   3874.948262      3931.298751         29.0
52           53      2027 Round 1 (Mid)     PICK       pick   3868.700000      3868.700000          NaN
53           54              A.J. Brown       WR     player   3793.086885      3799.539898         29.0
54           55           DeVonta Smith       WR     player   3780.870530      3838.961706         27.0
55           56           Luther Burden       WR     player   3750.909039      3839.914121         22.0
56           57             Rome Odunze       WR     player   3732.984829      3720.000000         24.0
57           58                Cam Ward       QB     player   3709.546782      3833.536758         24.0
58           59        Quinshon Judkins       RB     player   3605.369731      3839.974527         22.0
59           60             Rashee Rice       WR     player   3489.373750      3461.069751         26.0
60           61          Kyren Williams       RB     player   3458.066211      3448.762895         26.0
61           62            Tucker Kraft       TE     player   3438.397272      3386.421476         25.0
62           63        Fernando Mendoza       QB     player   3433.089503      3951.351850         22.0
63           64           Harold Fannin       TE     player   3390.100404      3246.488983         22.0
64           65             C.J. Stroud       QB     player   3381.451811      3202.613988         24.0
65           66             Tee Higgins       WR     player   3365.502186      3378.294599         27.0
66           67      TreVeyon Henderson       RB     player   3363.675780      3441.030949         23.0
67           68           Jaylen Waddle       WR     player   3348.486040      3357.039360         27.0
68           69            Cam Skattebo       RB     player   3319.862983      3377.267646         24.0
69           70              Jared Goff       QB     player   3308.649859      3372.394799         31.0
70           71            Tyler Shough       QB     player   3307.417442      3373.824459         26.0
71           72          Baker Mayfield       QB     player   3302.951832      3223.658457         31.0
72           73             Makai Lemon       WR     player   3253.189991      3252.076659         22.0
73           74     2027 Round 1 (Late)     PICK       pick   3242.350000      3242.350000          NaN
74           75        Brian Thomas Jr.       WR     player   3167.208371      3150.691161         23.0
75           76     Marvin Harrison Jr.       WR     player   3129.048614      3154.155743         24.0
76           77        Javonte Williams       RB     player   3110.002003      3140.862636         26.0
77           78          Jadarian Price       RB     player   3096.975624      3327.979328         22.0
78           79            Bucky Irving       RB     player   3091.801803      3131.892750         24.0
79           80             Sam LaPorta       TE     player   3060.834550      3147.894828         25.0
80           81        Jameson Williams       WR     player   3014.259006      3068.139217         25.0
81           82              Kyle Pitts       TE     player   2994.363203      3054.799994         25.0
82           83             Josh Jacobs       RB     player   2973.636081      3012.748229         28.0
83           84      2028 Round 1 (Mid)     PICK       pick   2970.297536      2970.297536          NaN
84           85             Sam Darnold       QB     player   2945.796630      3041.221209         29.0
85           86    2029 Round 1 (Early)     PICK       pick   2918.695171      2918.695171          NaN
86           87        Matthew Stafford       QB     player   2848.242350      2770.180589         38.0
87           88            Kenyon Sadiq       TE     player   2787.702635      2767.365843         21.0
88           89          Travis Etienne       RB     player   2779.157147      2767.204761         27.0
89           90       Parker Washington       WR     player   2766.775262      2768.259872         24.0
90           91            Kyler Murray       QB     player   2726.973359      2766.310733         29.0
91           92          Bhayshul Tuten       RB     player   2664.791067      2692.211880         23.0
92           93         Omar Cooper Jr.       WR     player   2652.160150      1960.922112         22.0
93           94        Christian Watson       WR     player   2617.526656      2631.976898         27.0
94           95           KC Concepcion       WR     player   2571.967871      2766.721515         21.0
95           96           D'Andre Swift       RB     player   2567.251060      2600.467403         27.0
96           97            Daniel Jones       QB     player   2550.352733      2599.537142         29.0
97           98           Derrick Henry       RB     player   2509.636091      3145.809912         32.0
98           99             Bryce Young       QB     player   2506.073692      2643.340117         25.0
99          100    2027 Round 2 (Early)     PICK       pick   2499.700000      2499.700000          NaN
100         101     2028 Round 1 (Late)     PICK       pick   2479.510609      2479.510609          NaN
101         102           Denzel Boston       WR     player   2476.598126      2450.209642         22.0
102         103            Malik Willis       QB     player   2409.809765      2472.939642         27.0
103         104              D.J. Moore       WR     player   2377.796945      2399.896998         29.0
104         105          Terry McLaurin       WR     player   2305.354308      2307.000000         30.0
105         106          Jordan Addison       WR     player   2303.388609      2339.310155         24.0
106         107          Michael Wilson       WR     player   2268.715597      2307.000000         26.0
107         108         Jonathon Brooks       RB     player   2196.353906      2156.465740         23.0
108         109        David Montgomery       RB     player   2184.191001      2245.755941         29.0
109         110      2027 Round 2 (Mid)     PICK       pick   2181.950000      2181.950000          NaN
110         111              DK Metcalf       WR     player   2174.290146      2129.826992         28.0
111         112             Alec Pierce       WR     player   2159.004566      2161.159388         26.0
112         113    2028 Round 2 (Early)     PICK       pick   2144.558529      2144.558529          NaN
113         114          Matthew Golden       WR     player   2142.388119      2162.005069         23.0
114         115           George Kittle       TE     player   2103.365751      2147.036815         32.0
115         116        Quentin Johnston       WR     player   2098.306790      2051.241837         25.0
116         117               RJ Harvey       RB     player   2053.341934      2038.843465         25.0
117         118              Ty Simpson       QB     player   2020.130564      1964.648077         23.0
118         119           Davante Adams       WR     player   2012.562201      2098.733462         33.0
119         120           Jaylen Warren       RB     player   2003.234117      2060.216816          NaN
120         121              Josh Downs       WR     player   1988.222325      2071.424471         25.0
121         122           Isaiah Likely       TE     player   1961.885120      2117.087200         26.0
122         123         Michael Pittman       WR     player   1959.538261      1932.121890         28.0
123         124          Jayden Higgins       WR     player   1932.081065      1932.852981         23.0
124         125     2027 Round 2 (Late)     PICK       pick   1930.750000      1930.750000          NaN
125         126      2029 Round 1 (Mid)     PICK       pick   1921.944000      1921.944000          NaN
126         127          Dalton Kincaid       TE     player   1904.846327      1875.776115         26.0
127         128      2028 Round 2 (Mid)     PICK       pick   1903.483271      1903.483271          NaN
128         129             Blake Corum       RB     player   1882.381594      1869.119014         25.0
129         130           Chuba Hubbard       RB     player   1862.302031      1875.288831         27.0
130         131           Kyle Monangai       RB     player   1847.777428      1850.202607         24.0
131         132             Jayden Reed       WR     player   1847.258911      1871.188791         26.0
132         133          Oronde Gadsden       TE     player   1846.982629      1804.683689         23.0
133         134         Zach Charbonnet       RB     player   1822.985993      1788.654633         25.0
134         135           Jake Ferguson       TE     player   1819.113221      1868.128293         27.0
135         136       Wan'Dale Robinson       WR     player   1817.442968      1785.819542         25.0
136         137              Mike Evans       WR     player   1814.342793      1957.504780         33.0
137         138             Rico Dowdle       RB     player   1814.220030      1810.277818          NaN
138         139            J.K. Dobbins       RB     player   1745.393259      1757.279593         27.0
139         140     2028 Round 2 (Late)     PICK       pick   1724.787703      1724.787703          NaN
140         141        Kenneth Gainwell       RB     player   1681.897536      1691.737947         27.0
141         142           Xavier Worthy       WR     player   1679.732280      1786.302789         23.0
142         143  Jacory Croskey-Merritt       RB     player   1675.948922      1753.252537         25.0
143         144     Rhamondre Stevenson       RB     player   1660.197530      1689.877426         28.0
144         145        Courtland Sutton       WR     player   1657.782254      1691.983608         30.0
145         146    2027 Round 3 (Early)     PICK       pick   1648.750000      1648.750000          NaN
146         147       Terrance Ferguson       TE     player   1642.489845      1595.014143         23.0
147         148           Rachaad White       RB     player   1611.254531      1555.122036         27.0
148         149             Jalen Coker       WR     player   1605.862794      1766.075584          NaN
149         150            Chris Godwin       WR     player   1605.698546      1594.030479         30.0
150         151               AJ Barner       TE     player   1569.270806      1565.000000         24.0
151         152          Tua Tagovailoa       QB     player   1557.927280      1550.391649         28.0
152         153             Romeo Doubs       WR     player   1555.785447      1572.924613         26.0
153         154           Khalil Shakir       WR     player   1550.989235      1554.960954         26.0
154         155           J.J. McCarthy       QB     player   1549.309291      1385.585096         23.0
155         156            Tony Pollard       RB     player   1548.649843      1565.770369         29.0
156         157            Ja'Kobi Lane       WR     player   1538.163008      1629.248950         22.0
157         158       Chigoziem Okonkwo       TE     player   1533.334612      1555.444200         26.0
158         159           Jakobi Meyers       WR     player   1531.707985      1554.316625          NaN
159         160    2029 Round 2 (Early)     PICK       pick   1530.596890      1530.596890          NaN
160         161      2027 Round 3 (Mid)     PICK       pick   1527.350000      1527.350000          NaN
161         162            Jordan Mason       RB     player   1510.122619      1633.622398          NaN
162         163            Stefon Diggs       WR     player   1507.195432      1579.120023         32.0
163         164            Travis Kelce       TE     player   1483.629315      1512.639576         36.0
164         165     2029 Round 1 (Late)     PICK       pick   1479.342650      1479.342650          NaN
165         166    2028 Round 3 (Early)     PICK       pick   1473.339661      1473.339661          NaN
166         167          Jalen McMillan       WR     player   1472.518011      1551.594672         24.0
167         168          Ricky Pearsall       WR     player   1459.931706      1454.463808         25.0
168         169         Brenton Strange       TE     player   1458.251650      1677.272788         25.0
169         170          Germie Bernard       WR     player   1455.093740      1451.992817         22.0
170         171       Michael Penix Jr.       QB     player   1453.321804      1422.066165         26.0
171         172            Tyrone Tracy       RB     player   1448.763244      1414.839465         26.0
172         173            Mark Andrews       TE     player   1445.985263      1625.576144         31.0
173         174          Dallas Goedert       TE     player   1445.173919      1452.753920         31.0
174         175              Chris Bell       WR     player   1438.623420      1440.072259         22.0
175         176          Tyler Allgeier       RB     player   1423.943462      1451.300142         26.0
176         177          T.J. Hockenson       TE     player   1420.030575      1451.090713         29.0
177         178              Tre Harris       WR     player   1413.480808      1408.826834         24.0
178         179             Woody Marks       RB     player   1413.122640      1412.477581         25.0
179         180             Tank Bigsby       RB     player   1405.421527      1451.135022         25.0
180         181          Rashid Shaheed       WR     player   1400.515827      1475.566793          NaN
181         182     2027 Round 3 (Late)     PICK       pick   1391.500000      1391.500000          NaN
182         183              Pat Bryant       WR     player   1385.333736      1436.141417         23.0
183         184         Shedeur Sanders       QB     player   1382.465120      1569.291969         24.0
184         185      2028 Round 3 (Mid)     PICK       pick   1366.804742      1366.804742          NaN
185         186               Tank Dell       WR     player   1354.700224      1380.173612         26.0
186         187            Deebo Samuel       WR     player   1349.723694      1326.844256         30.0
187         188         Chris Rodriguez       RB     player   1344.318240      1376.000000         25.0
188         189         Keaton Mitchell       RB     player   1324.337934      1412.504755          NaN
189         190          Kayshon Boutte       WR     player   1321.580972      1303.060861         24.0
190         191           Jonah Coleman       RB     player   1308.838569      1691.294971         23.0

### Superflex Dynasty -- 12 team -- Top 200

In [14]:
boards[("sf_dynasty", 12)][
    ["board_rank", "name", "position", "asset_type", "model_value", "consensus_value", "current_age"]
].head(200)

     board_rank                    name position asset_type   model_value  consensus_value  current_age
0             1            Jahmyr Gibbs       RB     player  10362.818432     10208.844721         24.0
1             2          Bijan Robinson       RB     player  10248.266589     10405.618873         24.0
2             3           Ja'Marr Chase       WR     player  10036.008580     10095.560303         26.0
3             4              Josh Allen       QB     player   9893.008528     10215.767328         30.0
4             5      Jaxon Smith-Njigba       WR     player   8933.460219      9025.013154         24.0
5             6              Drake Maye       QB     player   8550.250195      8638.302373         24.0
6             7              Puka Nacua       WR     player   8371.281334      8389.941414         25.0
7             8            Brock Bowers       TE     player   8001.179628      7839.832817         23.0
8             9       Amon-Ra St. Brown       WR     player   7377.248456      7288.166341         26.0
9            10           Ashton Jeanty       RB     player   7223.761665      7252.992855         22.0
10           11          Caleb Williams       QB     player   7143.461288      7245.762163         24.0
11           12           Lamar Jackson       QB     player   7068.318791      7279.461681         29.0
12           13              Joe Burrow       QB     player   6956.128130      6994.765474         29.0
13           14            Malik Nabers       WR     player   6878.900184      6870.087268         23.0
14           15        Justin Jefferson       WR     player   6871.652549      6990.617607         27.0
15           16          Jayden Daniels       QB     player   6686.107294      7048.060656         25.0
16           17             CeeDee Lamb       WR     player   6522.172365      6514.426122         27.0
17           18            Trey McBride       TE     player   6438.768248      6530.369963         26.0
18           19          Justin Herbert       QB     player   6383.990430      6295.036369         28.0
19           20           De'Von Achane       RB     player   5971.421308      5887.934984         24.0
20           21         Omarion Hampton       RB     player   5765.861207      5916.519152         23.0
21           22            Drake London       WR     player   5762.535487      5884.270364         25.0
22           23        Colston Loveland       TE     player   5468.535558      5325.732870         22.0
23           24    2027 Round 1 (Early)     PICK       pick   5389.500000      5389.500000          NaN
24           25             Jalen Hurts       QB     player   5355.083131      5293.612887         28.0
25           26         Jonathan Taylor       RB     player   5319.391948      5353.506159         27.0
26           27              James Cook       RB     player   5281.668070      5311.271485         26.0
27           28         Patrick Mahomes       QB     player   5258.415086      5354.996170         30.0
28           29         Trevor Lawrence       QB     player   5197.637966      5277.762113         26.0
29           30       Tetairoa McMillan       WR     player   5143.774607      4999.390235         23.0
30           31            Tyler Warren       TE     player   5003.393565      4880.524112         24.0
31           32          George Pickens       WR     player   4950.791541      4943.322060         25.0
32           33          Jeremiyah Love       RB     player   4870.548387      6986.469740         21.0
33           34            Emeka Egbuka       WR     player   4869.550144      4956.331850         23.0
34           35                  Bo Nix       QB     player   4847.041549      4870.538870         26.0
35           36             Jaxson Dart       QB     player   4801.617047      4989.102909         23.0
36           37      Kenneth Walker III       RB     player   4502.983382      4483.470141         25.0
37           38             Brock Purdy       QB     player   4427.971182      4533.886591         26.0
38           39             Chase Brown       RB     player   4278.273583      4326.159815         26.0
39           40            Nico Collins       WR     player   4237.966294      4227.921693         27.0
40           41            Carnell Tate       WR     player   4230.891621      4546.104415         21.0
41           42     Christian McCaffrey       RB     player   4230.187087      4224.776443         30.0
42           43          Garrett Wilson       WR     player   4154.228176      4155.231337         26.0
43           44            Dak Prescott       QB     player   4098.842745      3983.158089         33.0
44           45             Jordan Love       QB     player   4089.776965      4231.396065         27.0
45           46             Breece Hall       RB     player   4013.540949      3863.386566         25.0
46           47           Ladd McConkey       WR     player   4003.023193      3983.667637         24.0
47           48             Zay Flowers       WR     player   3976.267633      3937.678580         25.0
48           49          Saquon Barkley       RB     player   3933.085807      3943.719163         29.0
49           50            Jordyn Tyson       WR     player   3925.716112      3917.895261         22.0
50           51    2028 Round 1 (Early)     PICK       pick   3885.937676      3885.937676          NaN
51           52           Luther Burden       WR     player   3863.300075      3878.624682         22.0
52           53      2027 Round 1 (Mid)     PICK       pick   3862.850000      3862.850000          NaN
53           54              A.J. Brown       WR     player   3844.388220      3862.514692         29.0
54           55                Cam Ward       QB     player   3755.319311      3878.048671         24.0
55           56           DeVonta Smith       WR     player   3717.628882      3862.961706         27.0
56           57             Chris Olave       WR     player   3673.299982      4291.537354         26.0
57           58             Rome Odunze       WR     player   3646.359876      3687.499773         24.0
58           59        Quinshon Judkins       RB     player   3588.005917      3863.001977         22.0
59           60          Kyren Williams       RB     player   3552.694658      3491.369525         26.0
60           61             C.J. Stroud       QB     player   3516.672658      3258.202867         24.0
61           62      TreVeyon Henderson       RB     player   3465.351283      3449.546873         23.0
62           63          Baker Mayfield       QB     player   3462.280051      3313.333177         31.0
63           64             Rashee Rice       WR     player   3454.135089      3504.060970         26.0
64           65            Tyler Shough       QB     player   3434.710825      3476.618061         26.0
65           66           Harold Fannin       TE     player   3421.545465      3287.491627         22.0
66           67              Jared Goff       QB     player   3421.406808      3420.466977         31.0
67           68            Tucker Kraft       TE     player   3418.829912      3488.711668         25.0
68           69             Tee Higgins       WR     player   3358.898599      3340.794536         27.0
69           70            Cam Skattebo       RB     player   3299.520756      3339.870278         24.0
70           71     Marvin Harrison Jr.       WR     player   3267.252918      3233.002853         24.0
71           72             Makai Lemon       WR     player   3250.410760      3306.285830         22.0
72           73     2027 Round 1 (Late)     PICK       pick   3237.800000      3237.800000          NaN
73           74           Jaylen Waddle       WR     player   3219.701541      3335.853147         27.0
74           75        Brian Thomas Jr.       WR     player   3176.946289      3176.257196         23.0
75           76        Fernando Mendoza       QB     player   3173.650590      4095.351013         22.0
76           77        Javonte Williams       RB     player   3144.908113      3148.431318         26.0
77           78            Bucky Irving       RB     player   3117.927521      3143.525036         24.0
78           79        Jameson Williams       WR     player   3050.838082      3081.599269         25.0
79           80             Sam LaPorta       TE     player   3045.011997      3159.526724         25.0
80           81             Sam Darnold       QB     player   3022.729137      3037.824697         29.0
81           82              Kyle Pitts       TE     player   2967.539628      3072.799994         25.0
82           83      2028 Round 1 (Mid)     PICK       pick   2966.258968      2966.258968          NaN
83           84    2029 Round 1 (Early)     PICK       pick   2910.832307      2910.832307          NaN
84           85        Matthew Stafford       QB     player   2875.610770      2890.434377         38.0
85           86          Jadarian Price       RB     player   2854.277328      3308.299358         22.0
86           87             Josh Jacobs       RB     player   2826.771843      2818.220302         28.0
87           88          Travis Etienne       RB     player   2793.878861      2781.004457         27.0
88           89            Kenyon Sadiq       TE     player   2761.465019      2781.693094         21.0
89           90       Parker Washington       WR     player   2758.215771      2792.169422         24.0
90           91            Kyler Murray       QB     player   2753.726425      2795.068902         29.0
91           92           KC Concepcion       WR     player   2692.476359      2785.246816         21.0
92           93          Bhayshul Tuten       RB     player   2673.988485      2747.400218         23.0
93           94        Christian Watson       WR     player   2624.212249      2619.648558         27.0
94           95            Daniel Jones       QB     player   2554.827607      2636.413441         29.0
95           96             Bryce Young       QB     player   2547.203148      2754.246212         25.0
96           97            Malik Willis       QB     player   2545.119287      2599.104650         27.0
97           98           D'Andre Swift       RB     player   2539.865116      2599.104650         27.0
98           99    2027 Round 2 (Early)     PICK       pick   2496.450000      2496.450000          NaN
99          100     2028 Round 1 (Late)     PICK       pick   2476.402076      2476.402076          NaN
100         101           Derrick Henry       RB     player   2438.645544      3134.380346         32.0
101         102              D.J. Moore       WR     player   2398.162639      2406.583571         29.0
102         103           Denzel Boston       WR     player   2383.783085      2451.878484         22.0
103         104          Jordan Addison       WR     player   2337.693271      2379.773782         24.0
104         105          Michael Wilson       WR     player   2331.682197      2351.176831         26.0
105         106          Terry McLaurin       WR     player   2282.934886      2325.056847         30.0
106         107         Omar Cooper Jr.       WR     player   2189.983172      1970.384422         22.0
107         108      2027 Round 2 (Mid)     PICK       pick   2179.350000      2179.350000          NaN
108         109         Jonathon Brooks       RB     player   2170.891415      2130.033337         23.0
109         110             Alec Pierce       WR     player   2154.240912      2152.758367         26.0
110         111    2028 Round 2 (Early)     PICK       pick   2142.166971      2142.166971          NaN
111         112          Matthew Golden       WR     player   2132.736060      2189.315390         23.0
112         113              DK Metcalf       WR     player   2131.231478      2132.235882         28.0
113         114           George Kittle       TE     player   2128.912667      2130.677666         32.0
114         115        Quentin Johnston       WR     player   2112.589050      2071.912918         25.0
115         116           Davante Adams       WR     player   2065.161448      2085.545841         33.0
116         117        David Montgomery       RB     player   2055.225361      2258.755941         29.0
117         118           Jaylen Warren       RB     player   2041.918479      2063.175374          NaN
118         119               RJ Harvey       RB     player   2029.812829      2000.279813         25.0
119         120              Josh Downs       WR     player   2022.387997      2085.062595         25.0
120         121              Ty Simpson       QB     player   1976.299294      1975.321963         23.0
121         122           Isaiah Likely       TE     player   1975.433765      2129.058768         26.0
122         123          Jayden Higgins       WR     player   1934.997838      1942.226110         23.0
123         124             Rico Dowdle       RB     player   1928.344928      1814.659892          NaN
124         125     2027 Round 2 (Late)     PICK       pick   1928.150000      1928.150000          NaN
125         126      2029 Round 1 (Mid)     PICK       pick   1916.766350      1916.766350          NaN
126         127             Blake Corum       RB     player   1915.302273      1876.228813         25.0
127         128      2028 Round 2 (Mid)     PICK       pick   1901.501316      1901.501316          NaN
128         129         Michael Pittman       WR     player   1888.516371      1886.919081         28.0
129         130           Jake Ferguson       TE     player   1879.937508      1879.128293         27.0
130         131             Jayden Reed       WR     player   1877.095884      1885.430626         26.0
131         132           Chuba Hubbard       RB     player   1874.477537      1886.288831         27.0
132         133          Oronde Gadsden       TE     player   1872.531124      1847.035130         23.0
133         134          Dalton Kincaid       TE     player   1866.779453      1886.776115         26.0
134         135              Mike Evans       WR     player   1854.669062      1946.369721         33.0
135         136           Kyle Monangai       RB     player   1843.084164      1839.480569         24.0
136         137         Zach Charbonnet       RB     player   1827.912136      1778.764432         25.0
137         138       Wan'Dale Robinson       WR     player   1816.188441      1814.903589         25.0
138         139           Xavier Worthy       WR     player   1747.586067      1803.297375         23.0
139         140        Courtland Sutton       WR     player   1732.572817      1694.616246         30.0
140         141       Terrance Ferguson       TE     player   1723.478191      1631.306006         23.0
141         142     2028 Round 2 (Late)     PICK       pick   1723.080467      1723.080467          NaN
142         143            J.K. Dobbins       RB     player   1694.395453      1731.152351         27.0
143         144     Rhamondre Stevenson       RB     player   1671.383640      1684.614529         28.0
144         145  Jacory Croskey-Merritt       RB     player   1657.370753      1720.725005         25.0
145         146    2027 Round 3 (Early)     PICK       pick   1646.800000      1646.800000          NaN
146         147           J.J. McCarthy       QB     player   1637.469423      1423.613598         23.0
147         148        Kenneth Gainwell       RB     player   1632.676038      1684.248056         27.0
148         149          Tua Tagovailoa       QB     player   1600.251800      1562.895325         28.0
149         150            Chris Godwin       WR     player   1597.810875      1605.839423         30.0
150         151           Khalil Shakir       WR     player   1586.694824      1562.665816         26.0
151         152               AJ Barner       TE     player   1580.358559      1575.000000         24.0
152         153           Rachaad White       RB     player   1570.453648      1560.000000         27.0
153         154           Jakobi Meyers       WR     player   1567.628458      1560.237469          NaN
154         155           Jonah Coleman       RB     player   1565.178038      1684.999119         23.0
155         156             Jalen Coker       WR     player   1565.068843      1778.317418          NaN
156         157             Romeo Doubs       WR     player   1553.444738      1575.000000         26.0
157         158            Tony Pollard       RB     player   1552.813269      1567.000000         29.0
158         159          Germie Bernard       WR     player   1534.551438      1460.992817         22.0
159         160            Stefon Diggs       WR     player   1528.471862      1576.663795         32.0
160         161          Jalen McMillan       WR     player   1527.855228      1559.099715         24.0
161         162    2029 Round 2 (Early)     PICK       pick   1526.917570      1526.917570          NaN
162         163      2027 Round 3 (Mid)     PICK       pick   1525.400000      1525.400000          NaN
163         164       Chigoziem Okonkwo       TE     player   1524.203303      1563.037668         26.0
164         165         Brenton Strange       TE     player   1516.872298      1674.052926         25.0
165         166            Travis Kelce       TE     player   1492.011590      1517.000000         36.0
166         167          Dallas Goedert       TE     player   1485.631720      1461.753920         31.0
167         168            Mark Andrews       TE     player   1478.255930      1645.214679         31.0
168         169     2029 Round 1 (Late)     PICK       pick   1475.357352      1475.357352          NaN
169         170          T.J. Hockenson       TE     player   1472.301138      1460.090713         29.0
170         171    2028 Round 3 (Early)     PICK       pick   1471.871472      1471.871472          NaN
171         172       Michael Penix Jr.       QB     player   1466.668027      1460.018248         26.0
172         173              Tre Harris       WR     player   1462.189200      1441.778350         24.0
173         174          Ricky Pearsall       WR     player   1460.271149      1461.288790         25.0
174         175          Rashid Shaheed       WR     player   1440.659037      1483.551950          NaN
175         176              Pat Bryant       WR     player   1434.391279      1455.282834         23.0
176         177         Shedeur Sanders       QB     player   1421.063869      1642.221127         24.0
177         178              Chris Bell       WR     player   1420.252900      1459.807771         22.0
178         179            Tyrone Tracy       RB     player   1413.219105      1397.523271         26.0
179         180          Tyler Allgeier       RB     player   1411.269192      1453.349848         26.0
180         181            Jordan Mason       RB     player   1393.765339      1585.937102          NaN
181         182     2027 Round 3 (Late)     PICK       pick   1390.200000      1390.200000          NaN
182         183             Woody Marks       RB     player   1386.689323      1423.021654         25.0
183         184               Tank Dell       WR     player   1376.025757      1388.497795         26.0
184         185             Tank Bigsby       RB     player   1366.610259      1427.014269         25.0
185         186      2028 Round 3 (Mid)     PICK       pick   1365.498206      1365.498206          NaN
186         187         Chris Rodriguez       RB     player   1362.025138      1379.261640         25.0
187         188            Deebo Samuel       WR     player   1358.127216      1338.643407         30.0
188         189            Ja'Kobi Lane       WR     player   1324.850287      1646.338225         22.0
189         190          Kayshon Boutte       WR     player   1316.183531      1297.389838         24.0
190         191        Malik Washington       WR     player   1308.302575      1314.904181         25.0

### 1QB Dynasty -- 10 team -- Top 200

In [15]:
boards[("oneqb_dynasty", 10)][
    ["board_rank", "name", "position", "asset_type", "model_value", "consensus_value", "current_age"]
].head(200)

     board_rank                    name position asset_type   model_value  consensus_value  current_age
0             1            Jahmyr Gibbs       RB     player  11177.318163     11168.940955         24.0
1             2          Bijan Robinson       RB     player  11133.090701     11261.907002         24.0
2             3           Ja'Marr Chase       WR     player   9975.586321      9995.442701         26.0
3             4      Jaxon Smith-Njigba       WR     player   8718.033939      8786.440989         24.0
4             5              Puka Nacua       WR     player   8249.895811      8231.556447         25.0
5             6           Ashton Jeanty       RB     player   7622.700890      7678.140830         22.0
6             7       Amon-Ra St. Brown       WR     player   7368.683118      7266.905820         26.0
7             8            Brock Bowers       TE     player   7176.475676      7188.056839         23.0
8             9        Justin Jefferson       WR     player   6685.319660      6716.844033         27.0
9            10            Malik Nabers       WR     player   6667.484779      6701.581493         23.0
10           11             CeeDee Lamb       WR     player   6393.075593      6392.136325         27.0
11           12           De'Von Achane       RB     player   6376.577118      6326.108247         24.0
12           13         Omarion Hampton       RB     player   6321.325365      6383.051113         23.0
13           14            Trey McBride       TE     player   6224.297544      6286.369233         26.0
14           15              Josh Allen       QB     player   5823.844707      5819.245299         30.0
15           16            Drake London       WR     player   5763.141447      5812.093074         25.0
16           17         Jonathan Taylor       RB     player   5752.499476      5783.815288         27.0
17           18              James Cook       RB     player   5571.187383      5639.024869         26.0
18           19    2027 Round 1 (Early)     PICK       pick   5345.200000      5345.200000          NaN
19           20       Tetairoa McMillan       WR     player   5280.899474      5178.057314         23.0
20           21          George Pickens       WR     player   4872.832553      4788.390475         25.0
21           22        Colston Loveland       TE     player   4748.772786      4788.309934         22.0
22           23            Emeka Egbuka       WR     player   4699.259583      4706.189820         23.0
23           24      Kenneth Walker III       RB     player   4693.113818      4691.214849         25.0
24           25            Tyler Warren       TE     player   4606.742671      4426.560117         24.0
25           26              Drake Maye       QB     player   4582.665577      4513.615626         24.0
26           27             Chase Brown       RB     player   4438.775040      4446.285813         26.0
27           28     Christian McCaffrey       RB     player   4319.932189      4446.856476         30.0
28           29            Nico Collins       WR     player   4234.407603      4222.807349         27.0
29           30             Breece Hall       RB     player   4225.053764      4064.373454         25.0
30           31          Garrett Wilson       WR     player   4063.668647      4068.843594         26.0
31           32             Chris Olave       WR     player   4041.879019      4237.404010         26.0
32           33          Saquon Barkley       RB     player   4006.884331      4020.062234         29.0
33           34      2027 Round 1 (Mid)     PICK       pick   3993.400000      3993.400000          NaN
34           35    2028 Round 1 (Early)     PICK       pick   3952.909580      3952.909580          NaN
35           36            Carnell Tate       WR     player   3918.323221      4518.327281         21.0
36           37        Quinshon Judkins       RB     player   3908.905040      4025.351973         22.0
37           38             Zay Flowers       WR     player   3895.149895      3876.716741         25.0
38           39           Lamar Jackson       QB     player   3879.877135      4006.652139         29.0
39           40           Ladd McConkey       WR     player   3870.206716      3869.407635         24.0
40           41          Caleb Williams       QB     player   3749.769981      3702.163115         24.0
41           42           Luther Burden       WR     player   3737.160316      3785.925698         22.0
42           43            Jordyn Tyson       WR     player   3707.561902      3803.137091         22.0
43           44          Kyren Williams       RB     player   3704.126519      3626.574634         26.0
44           45          Jeremiyah Love       RB     player   3677.915121      7276.127777         21.0
45           46          Jayden Daniels       QB     player   3674.382389      3645.180300         25.0
46           47              A.J. Brown       WR     player   3648.217117      3687.127792         29.0
47           48             Rome Odunze       WR     player   3595.676601      3588.807192         24.0
48           49      TreVeyon Henderson       RB     player   3588.824377      3619.240830         23.0
49           50            Cam Skattebo       RB     player   3572.535661      3608.199921         24.0
50           51              Joe Burrow       QB     player   3557.532204      3610.398759         29.0
51           52           DeVonta Smith       WR     player   3457.109336      3634.620887         27.0
52           53             Tee Higgins       WR     player   3437.611381      3406.752678         27.0
53           54             Rashee Rice       WR     player   3429.797269      3439.311802         26.0
54           55           Jaylen Waddle       WR     player   3424.092418      3388.288246         27.0
55           56        Javonte Williams       RB     player   3366.789403      3373.245538         26.0
56           57     2027 Round 1 (Late)     PICK       pick   3337.900000      3337.900000          NaN
57           58             Makai Lemon       WR     player   3317.453182      3274.023850         22.0
58           59          Justin Herbert       QB     player   3240.138880      3197.832667         28.0
59           60            Bucky Irving       RB     player   3237.370092      3243.637351         24.0
60           61            Tucker Kraft       TE     player   3160.148729      3203.196835         25.0
61           62     Marvin Harrison Jr.       WR     player   3156.845301      3169.020205         24.0
62           63           Harold Fannin       TE     player   3142.651899      3052.975182         22.0
63           64      2028 Round 1 (Mid)     PICK       pick   3105.234034      3105.234034          NaN
64           65        Brian Thomas Jr.       WR     player   3086.756264      3087.652616         23.0
65           66          Jadarian Price       RB     player   2966.315252      3583.852244         22.0
66           67             Jalen Hurts       QB     player   2952.051478      2841.000000         28.0
67           68        Jameson Williams       WR     player   2933.691355      2987.864984         25.0
68           69             Josh Jacobs       RB     player   2905.877421      2877.591681         28.0
69           70             Sam LaPorta       TE     player   2901.475784      2947.760665         25.0
70           71         Patrick Mahomes       QB     player   2892.357229      2898.178774         30.0
71           72          Travis Etienne       RB     player   2833.125374      2841.000000         27.0
72           73           Derrick Henry       RB     player   2809.212174      3236.491129         32.0
73           74    2029 Round 1 (Early)     PICK       pick   2761.437888      2761.437888          NaN
74           75    2027 Round 2 (Early)     PICK       pick   2726.250000      2726.250000          NaN
75           76       Parker Washington       WR     player   2725.129338      2706.000000         24.0
76           77              Kyle Pitts       TE     player   2714.087126      2738.748298         25.0
77           78          Bhayshul Tuten       RB     player   2684.136290      2756.504146         23.0
78           79     2028 Round 1 (Late)     PICK       pick   2659.652758      2659.652758          NaN
79           80           D'Andre Swift       RB     player   2645.677177      2675.413104         27.0
80           81             Jaxson Dart       QB     player   2635.365843      2706.000000         23.0
81           82         Trevor Lawrence       QB     player   2583.611048      2667.922781         26.0
82           83            Kenyon Sadiq       TE     player   2568.316785      2554.526844         21.0
83           84           KC Concepcion       WR     player   2557.375048      2711.258625         21.0
84           85        Christian Watson       WR     player   2535.049373      2553.721433         27.0
85           86                  Bo Nix       QB     player   2515.352826      2566.613956         26.0
86           87         Omar Cooper Jr.       WR     player   2428.427286      1946.291508         22.0
87           88      2027 Round 2 (Mid)     PICK       pick   2407.350000      2407.350000          NaN
88           89             Brock Purdy       QB     player   2338.905743      2396.110186         26.0
89           90    2028 Round 2 (Early)     PICK       pick   2331.655517      2331.655517          NaN
90           91           Denzel Boston       WR     player   2321.885071      2303.995889         22.0
91           92              D.J. Moore       WR     player   2318.277028      2351.170743         29.0
92           93          Terry McLaurin       WR     player   2274.037178      2268.722481         30.0
93           94          Michael Wilson       WR     player   2272.680476      2251.293274         26.0
94           95          Jordan Addison       WR     player   2270.639326      2269.852130         24.0
95           96            Dak Prescott       QB     player   2255.557375      2179.581884         33.0
96           97         Jonathon Brooks       RB     player   2243.921654      2214.475221         23.0
97           98        David Montgomery       RB     player   2189.429684      2280.730372         29.0
98           99     2027 Round 2 (Late)     PICK       pick   2159.100000      2159.100000          NaN
99          100             Alec Pierce       WR     player   2150.955412      2134.183174         26.0
100         101           Jaylen Warren       RB     player   2126.202101      2134.013579          NaN
101         102             Jordan Love       QB     player   2080.556124      2214.153056         27.0
102         103        Quentin Johnston       WR     player   2079.603921      2042.470027         25.0
103         104          Matthew Golden       WR     player   2072.771050      2135.874537         23.0
104         105      2028 Round 2 (Mid)     PICK       pick   2065.137653      2065.137653          NaN
105         106               RJ Harvey       RB     player   2050.369263      2085.971079         25.0
106         107              DK Metcalf       WR     player   2035.019216      2068.618061         28.0
107         108           Davante Adams       WR     player   2010.463243      2071.703109         33.0
108         109             Blake Corum       RB     player   2000.201118      1981.182965         25.0
109         110              Josh Downs       WR     player   1985.739777      2068.773141         25.0
110         111           Kyle Monangai       RB     player   1942.751980      1944.358521         24.0
111         112           George Kittle       TE     player   1936.645052      1969.671698         32.0
112         113           Chuba Hubbard       RB     player   1920.709477      1963.369193         27.0
113         114         Zach Charbonnet       RB     player   1919.896472      1889.403044         25.0
114         115             Rico Dowdle       RB     player   1902.397891      1868.452938          NaN
115         116                Cam Ward       QB     player   1867.251530      2096.126555         24.0
116         117     2028 Round 2 (Late)     PICK       pick   1865.902201      1865.902201          NaN
117         118           Isaiah Likely       TE     player   1865.135758      1948.224494         26.0
118         119          Baker Mayfield       QB     player   1864.251329      1771.275935         31.0
119         120         Michael Pittman       WR     player   1855.556523      1843.479435         28.0
120         121             C.J. Stroud       QB     player   1836.347324      1763.000000         24.0
121         122          Jayden Higgins       WR     player   1831.433641      1843.723132         23.0
122         123      2029 Round 1 (Mid)     PICK       pick   1818.390983      1818.390983          NaN
123         124            J.K. Dobbins       RB     player   1818.119045      1831.598711         27.0
124         125    2027 Round 3 (Early)     PICK       pick   1809.050000      1809.050000          NaN
125         126              Jared Goff       QB     player   1803.724561      1819.146286         31.0
126         127            Tyler Shough       QB     player   1795.206735      1819.532895         26.0
127         128              Mike Evans       WR     player   1786.781042      1854.002650         33.0
128         129             Jayden Reed       WR     player   1784.248524      1819.128170         26.0
129         130     Rhamondre Stevenson       RB     player   1779.295736      1763.218087         28.0
130         131  Jacory Croskey-Merritt       RB     player   1775.351724      1817.735382         25.0
131         132       Wan'Dale Robinson       WR     player   1769.786108      1764.361815         25.0
132         133          Dalton Kincaid       TE     player   1747.344260      1744.314013         26.0
133         134          Oronde Gadsden       TE     player   1736.724623      1696.988347         23.0
134         135        Kenneth Gainwell       RB     player   1732.110024      1765.884020         27.0
135         136           Rachaad White       RB     player   1690.927466      1648.017235         27.0
136         137           Jake Ferguson       TE     player   1682.632574      1698.665523         27.0
137         138        Courtland Sutton       WR     player   1657.722806      1684.437348         30.0
138         139            Chris Godwin       WR     player   1651.760330      1650.207997         30.0
139         140      2027 Round 3 (Mid)     PICK       pick   1647.800000      1647.800000          NaN
140         141           Xavier Worthy       WR     player   1633.266175      1756.828600         23.0
141         142            Tony Pollard       RB     player   1622.491037      1650.834209         29.0
142         143    2028 Round 3 (Early)     PICK       pick   1591.300847      1591.300847          NaN
143         144            Jordan Mason       RB     player   1589.457436      1695.284922          NaN
144         145             Jalen Coker       WR     player   1579.645484      1743.464293          NaN
145         146             Sam Darnold       QB     player   1569.360069      1644.105825         29.0
146         147             Romeo Doubs       WR     player   1568.731663      1559.902975         26.0
147         148     2027 Round 3 (Late)     PICK       pick   1533.700000      1533.700000          NaN
148         149            Kyler Murray       QB     player   1521.070154      1517.305789         29.0
149         150        Matthew Stafford       QB     player   1520.238066      1544.173067         38.0
150         151           Khalil Shakir       WR     player   1517.591507      1520.172965         26.0
151         152       Terrance Ferguson       TE     player   1510.858633      1439.793435         23.0
152         153           Jonah Coleman       RB     player   1507.581342      1785.029434         23.0
153         154          Germie Bernard       WR     player   1502.073827      1396.601977         22.0
154         155            Ja'Kobi Lane       WR     player   1484.665183      1572.519532         22.0
155         156          Tyler Allgeier       RB     player   1478.429695      1491.900502         26.0
156         157           Jakobi Meyers       WR     player   1466.636914      1531.880620          NaN
157         158      2028 Round 3 (Mid)     PICK       pick   1460.888066      1460.888066          NaN
158         159            Stefon Diggs       WR     player   1460.515606      1538.363445         32.0
159         160          Jalen McMillan       WR     player   1457.599257      1482.760995         24.0
160         161            Tyrone Tracy       RB     player   1455.300603      1439.708856         26.0
161         162             Woody Marks       RB     player   1455.000133      1434.397544         25.0
162         163    2029 Round 2 (Early)     PICK       pick   1447.198982      1447.198982          NaN
163         164             Tank Bigsby       RB     player   1438.964276      1485.361447         25.0
164         165          Rashid Shaheed       WR     player   1437.875829      1424.305369          NaN
165         166               AJ Barner       TE     player   1431.469309      1424.105981         24.0
166         167              Pat Bryant       WR     player   1431.024918      1395.749045         23.0
167         168         Brenton Strange       TE     player   1426.441421      1530.136873         25.0
168         169            Mark Andrews       TE     player   1424.843288      1478.553785         31.0
169         170          Ricky Pearsall       WR     player   1420.647966      1419.410316         25.0
170         171              Tre Harris       WR     player   1410.429821      1404.837111         24.0
171         172       Chigoziem Okonkwo       TE     player   1403.413819      1416.286948         26.0
172         173     2029 Round 1 (Late)     PICK       pick   1399.636688      1399.636688          NaN
173         174         Chris Rodriguez       RB     player   1382.644876      1406.384551         25.0
174         175        Fernando Mendoza       QB     player   1372.778060      2194.353429         22.0
175         176            Deebo Samuel       WR     player   1370.690531      1307.690992         30.0
176         177     2028 Round 3 (Late)     PICK       pick   1362.621983      1362.621983          NaN
177         178             Bryce Young       QB     player   1360.773499      1429.000000         25.0
178         179            Daniel Jones       QB     player   1359.349042      1361.952336         29.0
179         180          Dallas Goedert       TE     player   1339.505936      1359.293164         31.0
180         181           Dylan Sampson       RB     player   1335.050930      1357.123575         21.0
181         182            Travis Kelce       TE     player   1334.777962      1395.118794         36.0
182         183          T.J. Hockenson       TE     player   1310.416170      1324.332592         29.0
183         184         Keaton Mitchell       RB     player   1304.264827      1432.385263          NaN
184         185            Malik Willis       QB     player   1296.709048      1364.115911         27.0
185         186            Tyjae Spears       RB     player   1296.415159      1317.471148         25.0
186         187               Tank Dell       WR     player   1291.568020      1316.343572         26.0
187         188           Braelon Allen       RB     player   1278.522359      1324.644716         22.0
188         189             Aaron Jones       RB     player   1273.130148      1284.487112         31.0
189         190          MarShawn Lloyd       RB     player   1271.598162      1241.576654         25.0
190         191          Kayshon Boutte       WR     player   1255.322898      1249.390689         24.0

### 1QB Dynasty -- 12 team -- Top 200

In [16]:
boards[("oneqb_dynasty", 12)][
    ["board_rank", "name", "position", "asset_type", "model_value", "consensus_value", "current_age"]
].head(200)

     board_rank                    name position asset_type   model_value  consensus_value  current_age
0             1            Jahmyr Gibbs       RB     player  11059.856167     11051.886055         24.0
1             2          Bijan Robinson       RB     player  10890.779871     11143.819147         24.0
2             3           Ja'Marr Chase       WR     player   9888.263256     10036.883112         26.0
3             4      Jaxon Smith-Njigba       WR     player   8820.225227      8837.583029         24.0
4             5              Puka Nacua       WR     player   8364.843255      8279.937128         25.0
5             6           Ashton Jeanty       RB     player   7599.866936      7597.991686         22.0
6             7       Amon-Ra St. Brown       WR     player   7333.105523      7233.085765         26.0
7             8            Brock Bowers       TE     player   7309.398689      7195.210709         23.0
8             9        Justin Jefferson       WR     player   6648.424251      6756.304540         27.0
9            10            Malik Nabers       WR     player   6576.483776      6740.921188         23.0
10           11             CeeDee Lamb       WR     player   6441.057369      6425.045904         27.0
11           12           De'Von Achane       RB     player   6293.068970      6264.826605         24.0
12           13         Omarion Hampton       RB     player   6210.895016      6268.773119         23.0
13           14            Trey McBride       TE     player   6149.681824      6223.345383         26.0
14           15              Josh Allen       QB     player   5725.911680      5785.692279         30.0
15           16            Drake London       WR     player   5717.874209      5757.306886         25.0
16           17         Jonathan Taylor       RB     player   5687.017461      5741.461977         27.0
17           18              James Cook       RB     player   5621.559563      5654.829959         26.0
18           19       Tetairoa McMillan       WR     player   5415.728098      5337.154060         23.0
19           20    2027 Round 1 (Early)     PICK       pick   5336.750000      5336.750000          NaN
20           21        Colston Loveland       TE     player   4840.834376      4816.516668         22.0
21           22          George Pickens       WR     player   4798.909060      4816.718021         25.0
22           23      Kenneth Walker III       RB     player   4679.494381      4649.871918         25.0
23           24            Tyler Warren       TE     player   4603.511962      4504.588651         24.0
24           25              Drake Maye       QB     player   4596.070996      4678.623675         24.0
25           26            Emeka Egbuka       WR     player   4588.642259      4606.230234         23.0
26           27     Christian McCaffrey       RB     player   4510.448648      4454.162255         30.0
27           28             Chase Brown       RB     player   4452.227502      4490.172448         26.0
28           29          Jeremiyah Love       RB     player   4288.180373      7237.515526         21.0
29           30            Nico Collins       WR     player   4205.761372      4180.746807         27.0
30           31            Carnell Tate       WR     player   4171.642375      4519.394355         21.0
31           32             Breece Hall       RB     player   4145.724396      4088.373454         25.0
32           33          Garrett Wilson       WR     player   4073.893357      4092.843594         26.0
33           34           Lamar Jackson       QB     player   4057.269657      4085.957220         29.0
34           35      2027 Round 1 (Mid)     PICK       pick   3988.200000      3988.200000          NaN
35           36          Saquon Barkley       RB     player   3954.713831      3978.062234         29.0
36           37    2028 Round 1 (Early)     PICK       pick   3947.798718      3947.798718          NaN
37           38             Chris Olave       WR     player   3938.922671      4199.230255         26.0
38           39          Caleb Williams       QB     player   3928.983379      3808.495439         24.0
39           40             Zay Flowers       WR     player   3909.043341      3855.125667         25.0
40           41        Quinshon Judkins       RB     player   3894.041132      3983.351973         22.0
41           42           Ladd McConkey       WR     player   3843.035675      3850.051577         24.0
42           43            Jordyn Tyson       WR     player   3841.881039      3828.115857         22.0
43           44          Jayden Daniels       QB     player   3773.297204      3809.022995         25.0
44           45           Luther Burden       WR     player   3748.821792      3809.997564         22.0
45           46              A.J. Brown       WR     player   3709.064783      3712.028546         29.0
46           47      TreVeyon Henderson       RB     player   3656.637387      3658.470499         23.0
47           48              Joe Burrow       QB     player   3655.834240      3707.280550         29.0
48           49           DeVonta Smith       WR     player   3627.493805      3703.276108         27.0
49           50          Kyren Williams       RB     player   3611.045199      3608.508639         26.0
50           51             Rome Odunze       WR     player   3578.004396      3595.651863         24.0
51           52            Cam Skattebo       RB     player   3552.983127      3562.195716         24.0
52           53             Rashee Rice       WR     player   3434.890272      3449.618489         26.0
53           54           Jaylen Waddle       WR     player   3423.006505      3417.433548         27.0
54           55             Tee Higgins       WR     player   3380.557280      3398.973265         27.0
55           56     2027 Round 1 (Late)     PICK       pick   3334.000000      3334.000000          NaN
56           57        Javonte Williams       RB     player   3313.070839      3366.679692         26.0
57           58          Justin Herbert       QB     player   3273.203698      3227.306660         28.0
58           59            Bucky Irving       RB     player   3231.642322      3219.920888         24.0
59           60           Harold Fannin       TE     player   3214.445082      3103.293586         22.0
60           61     Marvin Harrison Jr.       WR     player   3180.835178      3157.958278         24.0
61           62            Tucker Kraft       TE     player   3168.315725      3213.915348         25.0
62           63             Makai Lemon       WR     player   3150.637551      3234.558459         22.0
63           64        Brian Thomas Jr.       WR     player   3139.088764      3140.915694         23.0
64           65             Jalen Hurts       QB     player   3102.123428      2970.697839         28.0
65           66      2028 Round 1 (Mid)     PICK       pick   3101.868561      3101.868561          NaN
66           67          Jadarian Price       RB     player   2991.396876      3545.635714         22.0
67           68         Patrick Mahomes       QB     player   2979.664609      2991.465658         30.0
68           69        Jameson Williams       WR     player   2901.601718      2946.764479         25.0
69           70          Travis Etienne       RB     player   2895.661701      2827.939470         27.0
70           71             Josh Jacobs       RB     player   2850.380556      2882.394454         28.0
71           72           Derrick Henry       RB     player   2826.823546      3217.539698         32.0
72           73             Sam LaPorta       TE     player   2813.997321      2846.893197         25.0
73           74              Kyle Pitts       TE     player   2755.232061      2786.923128         25.0
74           75    2029 Round 1 (Early)     PICK       pick   2753.575024      2753.575024          NaN
75           76          Bhayshul Tuten       RB     player   2726.605351      2804.637278         23.0
76           77    2027 Round 2 (Early)     PICK       pick   2723.000000      2723.000000          NaN
77           78             Jaxson Dart       QB     player   2719.576999      2791.840283         23.0
78           79         Trevor Lawrence       QB     player   2717.165010      2753.259506         26.0
79           80       Parker Washington       WR     player   2664.672217      2673.143060         24.0
80           81     2028 Round 1 (Late)     PICK       pick   2657.062314      2657.062314          NaN
81           82           D'Andre Swift       RB     player   2604.620193      2613.784739         27.0
82           83                  Bo Nix       QB     player   2591.805878      2613.220951         26.0
83           84        Christian Watson       WR     player   2589.623268      2571.485317         27.0
84           85            Kenyon Sadiq       TE     player   2578.134884      2572.451810         21.0
85           86             Brock Purdy       QB     player   2453.818838      2568.319986         26.0
86           87      2027 Round 2 (Mid)     PICK       pick   2404.750000      2404.750000          NaN
87           88         Omar Cooper Jr.       WR     player   2380.135644      1958.291508         22.0
88           89              D.J. Moore       WR     player   2346.024216      2388.071602         29.0
89           90            Dak Prescott       QB     player   2344.779754      2226.127204         33.0
90           91    2028 Round 2 (Early)     PICK       pick   2329.263960      2329.263960          NaN
91           92           Denzel Boston       WR     player   2292.747137      2290.936527         22.0
92           93          Michael Wilson       WR     player   2278.657356      2238.147470         26.0
93           94          Jordan Addison       WR     player   2243.792464      2239.720095         24.0
94           95             Jordan Love       QB     player   2239.832042      2290.145194         27.0
95           96         Jonathon Brooks       RB     player   2234.780408      2226.288286         23.0
96           97          Terry McLaurin       WR     player   2184.429039      2238.590446         30.0
97           98             Alec Pierce       WR     player   2160.556196      2164.390385         26.0
98           99     2027 Round 2 (Late)     PICK       pick   2157.150000      2157.150000          NaN
99          100        David Montgomery       RB     player   2132.445337      2269.339136         29.0
100         101              DK Metcalf       WR     player   2121.622721      2093.836312         28.0
101         102          Matthew Golden       WR     player   2117.435502      2165.356878         23.0
102         103           KC Concepcion       WR     player   2098.314087      2717.132851         21.0
103         104           Jaylen Warren       RB     player   2097.933720      2164.293474          NaN
104         105        Quentin Johnston       WR     player   2096.943831      2055.915726         25.0
105         106      2028 Round 2 (Mid)     PICK       pick   2063.155698      2063.155698          NaN
106         107               RJ Harvey       RB     player   2057.776744      2094.129892         25.0
107         108              Josh Downs       WR     player   2052.715448      2093.902775         25.0
108         109           Davante Adams       WR     player   2040.060547      2094.844721         33.0
109         110             Blake Corum       RB     player   2002.420430      1959.258001         25.0
110         111           George Kittle       TE     player   1986.785514      1981.671698         32.0
111         112                Cam Ward       QB     player   1960.112424      2169.222852         24.0
112         113             Rico Dowdle       RB     player   1936.920388      1868.775398          NaN
113         114           Kyle Monangai       RB     player   1919.335329      1943.257690         24.0
114         115           Chuba Hubbard       RB     player   1901.825051      1944.959094         27.0
115         116              Jared Goff       QB     player   1898.169612      1865.332211         31.0
116         117         Zach Charbonnet       RB     player   1892.674151      1862.513272         25.0
117         118             C.J. Stroud       QB     player   1884.071960      1790.913000         24.0
118         119     2028 Round 2 (Late)     PICK       pick   1864.194966      1864.194966          NaN
119         120           Isaiah Likely       TE     player   1849.590266      1973.577208         26.0
120         121            Tyler Shough       QB     player   1846.885053      1865.956459         26.0
121         122          Jayden Higgins       WR     player   1845.699642      1854.180561         23.0
122         123         Michael Pittman       WR     player   1836.884720      1852.289255         28.0
123         124          Baker Mayfield       QB     player   1815.932812      1795.143482         31.0
124         125      2029 Round 1 (Mid)     PICK       pick   1813.213332      1813.213332          NaN
125         126    2027 Round 3 (Early)     PICK       pick   1807.100000      1807.100000          NaN
126         127             Jayden Reed       WR     player   1796.276947      1837.530739         26.0
127         128       Wan'Dale Robinson       WR     player   1793.656044      1779.702268         25.0
128         129            J.K. Dobbins       RB     player   1787.738775      1802.069016         27.0
129         130              Mike Evans       WR     player   1771.246824      1861.897264         33.0
130         131  Jacory Croskey-Merritt       RB     player   1770.827802      1799.872631         25.0
131         132          Dalton Kincaid       TE     player   1766.109850      1754.610746         26.0
132         133        Kenneth Gainwell       RB     player   1758.488928      1769.742184         27.0
133         134     Rhamondre Stevenson       RB     player   1747.386883      1753.922109         28.0
134         135           Jake Ferguson       TE     player   1740.139339      1725.856785         27.0
135         136          Oronde Gadsden       TE     player   1739.942339      1717.639519         23.0
136         137          Germie Bernard       WR     player   1739.517255      1405.601977         22.0
137         138           Xavier Worthy       WR     player   1686.671064      1767.102553         23.0
138         139            Chris Godwin       WR     player   1680.110969      1660.207997         30.0
139         140            Tony Pollard       RB     player   1671.707325      1660.834209         29.0
140         141        Fernando Mendoza       QB     player   1663.933719      2229.415446         22.0
141         142           Rachaad White       RB     player   1662.872405      1625.319813         27.0
142         143             Sam Darnold       QB     player   1649.766286      1660.471774         29.0
143         144      2027 Round 3 (Mid)     PICK       pick   1646.500000      1646.500000          NaN
144         145        Courtland Sutton       WR     player   1613.821863      1694.794150         30.0
145         146    2028 Round 3 (Early)     PICK       pick   1589.832659      1589.832659          NaN
146         147        Matthew Stafford       QB     player   1578.989990      1631.222626         38.0
147         148            Ja'Kobi Lane       WR     player   1564.807460      1578.839761         22.0
148         149            Jordan Mason       RB     player   1559.974062      1694.691454          NaN
149         150           Khalil Shakir       WR     player   1555.244451      1529.787155         26.0
150         151             Jalen Coker       WR     player   1551.214226      1752.732147          NaN
151         152            Kyler Murray       QB     player   1542.505538      1551.761121         29.0
152         153             Romeo Doubs       WR     player   1533.993688      1548.684407         26.0
153         154     2027 Round 3 (Late)     PICK       pick   1532.400000      1532.400000          NaN
154         155           Jonah Coleman       RB     player   1522.903086      1782.833331         23.0
155         156            Stefon Diggs       WR     player   1505.568312      1547.363445         32.0
156         157       Terrance Ferguson       TE     player   1503.073395      1467.441802         23.0
157         158          Jalen McMillan       WR     player   1498.064131      1487.941483         24.0
158         159           Jakobi Meyers       WR     player   1481.395498      1528.307294          NaN
159         160            Tyrone Tracy       RB     player   1468.717429      1448.763756         26.0
160         161          Rashid Shaheed       WR     player   1460.754094      1439.038367          NaN
161         162      2028 Round 3 (Mid)     PICK       pick   1459.581530      1459.581530          NaN
162         163               AJ Barner       TE     player   1452.738170      1433.843302         24.0
163         164          Tyler Allgeier       RB     player   1443.972735      1473.018330         26.0
164         165    2029 Round 2 (Early)     PICK       pick   1443.519663      1443.519663          NaN
165         166              Tre Harris       WR     player   1428.043260      1413.837111         24.0
166         167              Pat Bryant       WR     player   1427.804017      1404.749045         23.0
167         168          Ricky Pearsall       WR     player   1424.968490      1432.302871         25.0
168         169             Woody Marks       RB     player   1422.359694      1436.591849         25.0
169         170         Brenton Strange       TE     player   1409.163764      1503.977457         25.0
170         171            Malik Willis       QB     player   1399.652248      1399.288365         27.0
171         172             Tank Bigsby       RB     player   1398.727915      1479.815124         25.0
172         173     2029 Round 1 (Late)     PICK       pick   1395.651390      1395.651390          NaN
173         174             Bryce Young       QB     player   1391.391097      1467.857604         25.0
174         175       Chigoziem Okonkwo       TE     player   1389.090406      1423.177149         26.0
175         176         Chris Rodriguez       RB     player   1386.002791      1404.961475         25.0
176         177            Mark Andrews       TE     player   1369.413436      1485.294505         31.0
177         178          T.J. Hockenson       TE     player   1362.678518      1338.216784         29.0
178         179     2028 Round 3 (Late)     PICK       pick   1361.419599      1361.419599          NaN
179         180            Daniel Jones       QB     player   1360.393704      1388.861905         29.0
180         181           Dylan Sampson       RB     player   1341.046047      1328.755373         21.0
181         182            Deebo Samuel       WR     player   1335.838062      1314.963176         30.0
182         183          Dallas Goedert       TE     player   1335.368361      1369.013999         31.0
183         184               Tank Dell       WR     player   1321.453719      1320.096734         26.0
184         185         Keaton Mitchell       RB     player   1302.090253      1422.681789          NaN
185         186            Tyjae Spears       RB     player   1290.378521      1316.409309         25.0
186         187            Travis Kelce       TE     player   1285.780619      1404.118794         36.0
187         188           Braelon Allen       RB     player   1273.187408      1322.283458         22.0
188         189          MarShawn Lloyd       RB     player   1264.313834      1232.796252         25.0
189         190          Brian Robinson       RB     player   1261.002044      1249.735848         27.0
190         191         Adonai Mitchell       WR     player   1258.724826      1257.000000         23.0

### Redraft -- 10 team -- Top 200

In [17]:
boards[("redraft", 10)][
    ["board_rank", "name", "position", "asset_type", "model_value", "consensus_value", "current_age"]
].head(200)

     board_rank                    name position asset_type   model_value  consensus_value  current_age
0             1            Jahmyr Gibbs       RB     player  10455.525928     10200.000000         24.0
1             2           Ja'Marr Chase       WR     player  10065.583275      9757.817630         26.0
2             3          Bijan Robinson       RB     player   9873.149942     10056.487548         24.0
3             4              Puka Nacua       WR     player   9401.861022      9436.893633         25.0
4             5      Jaxon Smith-Njigba       WR     player   9089.426194      9321.934016         24.0
5             6       Amon-Ra St. Brown       WR     player   8821.936336      8650.483990         26.0
6             7         Jonathan Taylor       RB     player   8446.587374      8348.486178         27.0
7             8     Christian McCaffrey       RB     player   8276.906555      8217.410706         30.0
8             9             CeeDee Lamb       WR     player   8090.032888      8080.936695         27.0
9            10           Ashton Jeanty       RB     player   7995.124425      8136.355457         22.0
10           11              James Cook       RB     player   7912.264898      8149.510939         26.0
11           12         Omarion Hampton       RB     player   7648.748381      7661.780375         23.0
12           13        Justin Jefferson       WR     player   7615.788951      7828.848321         27.0
13           14           De'Von Achane       RB     player   7533.419008      7512.248006         24.0
14           15            Trey McBride       TE     player   6958.765651      6768.586032         26.0
15           16            Brock Bowers       TE     player   6789.288296      6694.902292         23.0
16           17          Saquon Barkley       RB     player   6643.866545      6664.915399         29.0
17           18      Kenneth Walker III       RB     player   6627.023043      6391.154245         25.0
18           19            Drake London       WR     player   6395.716021      6516.848444         25.0
19           20              Josh Allen       QB     player   6171.753481      6418.861541         30.0
20           21             Chase Brown       RB     player   6042.533940      5987.266061         26.0
21           22          George Pickens       WR     player   5656.885601      5611.355192         25.0
22           23            Malik Nabers       WR     player   5390.328573      5343.119505         23.0
23           24              A.J. Brown       WR     player   5311.703055      5307.448626         29.0
24           25            Nico Collins       WR     player   5200.154483      5295.337525         27.0
25           26           Derrick Henry       RB     player   4847.272746      5123.762749         32.0
26           27             Breece Hall       RB     player   4840.632415      4880.468531         25.0
27           28           Lamar Jackson       QB     player   4697.577108      5093.765601         29.0
28           29          Kyren Williams       RB     player   4571.811131      4513.403775         26.0
29           30           DeVonta Smith       WR     player   4096.276838      4062.625199         27.0
30           31             Chris Olave       WR     player   4078.973504      4565.987609         26.0
31           32             Rashee Rice       WR     player   4008.951670      4048.857932         26.0
32           33              Joe Burrow       QB     player   3833.966806      3856.991162         29.0
33           34            Emeka Egbuka       WR     player   3803.139958      3732.651474         23.0
34           35        Quinshon Judkins       RB     player   3751.611769      3787.934671         22.0
35           36             Tee Higgins       WR     player   3750.099594      3745.188913         27.0
36           37            Cam Skattebo       RB     player   3734.322107      3746.756093         24.0
37           38       Tetairoa McMillan       WR     player   3727.398237      3731.084294         23.0
38           39        Javonte Williams       RB     player   3717.926899      3799.053910         26.0
39           40        Colston Loveland       TE     player   3653.675667      3915.261348         22.0
40           41             Josh Jacobs       RB     player   3627.197948      3741.388194         28.0
41           42              Drake Maye       QB     player   3499.387342      3403.174253         24.0
42           43          Garrett Wilson       WR     player   3493.947638      3577.581830         26.0
43           44           Ladd McConkey       WR     player   3484.606784      3744.738503         24.0
44           45             Zay Flowers       WR     player   3201.372699      3343.383307         25.0
45           46            Bucky Irving       RB     player   3076.745749      3026.128072         24.0
46           47          Travis Etienne       RB     player   3043.638005      2857.231505         27.0
47           48            Tyler Warren       TE     player   3018.429924      2984.057130         24.0
48           49      TreVeyon Henderson       RB     player   3005.511778      2955.593516         23.0
49           50           Jaylen Waddle       WR     player   2984.779197      2956.719237         27.0
50           51          Jayden Daniels       QB     player   2740.930681      2958.004509         25.0
51           52          Caleb Williams       QB     player   2600.590350      2973.213052         24.0
52           53           D'Andre Swift       RB     player   2563.105904      2506.351491         27.0
53           54        David Montgomery       RB     player   2536.095782      2567.104813         29.0
54           55             Jalen Hurts       QB     player   2518.960332      2492.733346         28.0
55           56           Luther Burden       WR     player   2475.488634      2572.641475         22.0
56           57          Justin Herbert       QB     player   2404.768673      2462.987670         28.0
57           58         Trevor Lawrence       QB     player   2316.780307      2182.665154         26.0
58           59             Rome Odunze       WR     player   2217.601094      2224.716190         24.0
59           60         Patrick Mahomes       QB     player   2188.352594      2207.728397         30.0
60           61          Terry McLaurin       WR     player   2126.701702      2170.690140         30.0
61           62           Davante Adams       WR     player   2102.655937      2233.214278         33.0
62           63            Tucker Kraft       TE     player   2062.591040      2153.031775         25.0
63           64        Jameson Williams       WR     player   2040.711303      2229.351511         25.0
64           65             Jaxson Dart       QB     player   1984.497225      2025.702470         23.0
65           66     Marvin Harrison Jr.       WR     player   1941.542498      1911.514538         24.0
66           67           Harold Fannin       TE     player   1766.753295      1863.299064         22.0
67           68              D.J. Moore       WR     player   1759.762405      1755.543093         29.0
68           69        Brian Thomas Jr.       WR     player   1713.729606      1648.755286         23.0
69           70                  Bo Nix       QB     player   1643.069974      1456.802028         26.0
70           71             Sam LaPorta       TE     player   1611.776817      1627.562733         25.0
71           72          Bhayshul Tuten       RB     player   1609.156513      1888.701754         23.0
72           73           Jaylen Warren       RB     player   1589.696727      1627.172024          NaN
73           74              Mike Evans       WR     player   1575.615037      1604.366714         33.0
74           75              DK Metcalf       WR     player   1495.827652      1460.196786         28.0
75           76              Kyle Pitts       TE     player   1489.145683      1482.871907         25.0
76           77        Christian Watson       WR     player   1467.290924      1459.137284         27.0
77           78            Jordyn Tyson       WR     player   1370.002689      1666.091768         22.0
78           79             Brock Purdy       QB     player   1367.366671      1725.065769         26.0
79           80          Jeremiyah Love       RB     player   1364.496112      5609.280334         21.0
80           81            Dak Prescott       QB     player   1362.852589      1685.301088         33.0
81           82               RJ Harvey       RB     player   1200.646960      1190.328048         25.0
82           83         Michael Pittman       WR     player   1180.703720      1186.582771         28.0
83           84     Rhamondre Stevenson       RB     player   1169.413935      1188.525191         28.0
84           85             Jordan Love       QB     player   1165.548104      1205.747086         27.0
85           86           George Kittle       TE     player   1159.137321      1165.873512         32.0
86           87           Chuba Hubbard       RB     player   1108.803787      1304.633317         27.0
87           88        Matthew Stafford       QB     player   1092.636665      1231.239725         38.0
88           89       Parker Washington       WR     player   1047.305940      1028.017544         24.0
89           90            J.K. Dobbins       RB     player   1042.954482      1025.625843         27.0
90           91             Rico Dowdle       RB     player   1031.339075      1009.964912          NaN
91           92            Travis Kelce       TE     player   1019.755024      1090.208175         36.0
92           93             Alec Pierce       WR     player   1001.322868      1045.523504         26.0
93           94          Baker Mayfield       QB     player    982.365120      1044.555837         31.0
94           95              Jared Goff       QB     player    966.697119       820.597636         31.0
95           96            Carnell Tate       WR     player    929.751110      2564.871795         21.0
96           97        Courtland Sutton       WR     player    895.156691       867.715127         30.0
97           98          Michael Wilson       WR     player    884.575036       890.192982         26.0
98           99             Blake Corum       RB     player    883.576188       987.233632         25.0
99          100        Quentin Johnston       WR     player    858.451168       813.158876         25.0
100         101            Chris Godwin       WR     player    839.010610       868.112440         30.0
101         102            Stefon Diggs       WR     player    814.803700       719.604363         32.0
102         103       Wan'Dale Robinson       WR     player    812.606948       799.486014         25.0
103         104             Makai Lemon       WR     player    798.108408      1191.991341         22.0
104         105        Fernando Mendoza       QB     player    774.368701       372.020734         22.0
105         106           Jake Ferguson       TE     player    766.656872       786.656371         27.0
106         107            Tony Pollard       RB     player    765.144317       751.012391         29.0
107         108          Jordan Addison       WR     player    757.619371       768.301543         24.0
108         109          Matthew Golden       WR     player    755.325120       716.308367         23.0
109         110             Aaron Jones       RB     player    754.091118       800.509017         31.0
110         111          Jadarian Price       RB     player    731.122784      2176.043267         22.0
111         112           KC Concepcion       WR     player    721.648859       741.251626         21.0
112         113              Josh Downs       WR     player    719.880028       869.549442         25.0
113         114          Dalton Kincaid       TE     player    712.791538       689.694312         26.0
114         115           Kyle Monangai       RB     player    699.894778       720.304094         24.0
115         116            Mark Andrews       TE     player    696.604828       703.515458         31.0
116         117  Jacory Croskey-Merritt       RB     player    684.149875       753.876692         25.0
117         118        Kenneth Gainwell       RB     player    683.405278       740.761502         27.0
118         119             Jayden Reed       WR     player    660.360014       689.870895         26.0
119         120            Deebo Samuel       WR     player    656.756251       627.961477         30.0
120         121           Jakobi Meyers       WR     player    642.048843       600.681532          NaN
121         122           Isaiah Likely       TE     player    633.729297       739.627500         26.0
122         123           Rachaad White       RB     player    631.292178       627.431726         27.0
123         124            Jordan Mason       RB     player    629.001253       678.475279          NaN
124         125            Kyler Murray       QB     player    623.946946       535.465260         29.0
125         126             Romeo Doubs       WR     player    602.482522       613.737456         26.0
126         127           Xavier Worthy       WR     player    582.031632       645.464391         23.0
127         128            Kenyon Sadiq       TE     player    579.947248       471.438188         21.0
128         129             C.J. Stroud       QB     player    571.029399       531.323151         24.0
129         130          Jayden Higgins       WR     player    569.538757       600.996115         23.0
130         131         Jonathon Brooks       RB     player    536.227877       547.572363         23.0
131         132             Sam Darnold       QB     player    532.394015       600.240073         29.0
132         133          Oronde Gadsden       TE     player    527.415981       506.821310         23.0
133         134           Denzel Boston       WR     player    515.314937       560.021838         22.0
134         135                Cam Ward       QB     player    504.593164       582.329775         24.0
135         136         Zach Charbonnet       RB     player    491.974983       484.228929         25.0
136         137          Dallas Goedert       TE     player    459.024364       475.057631         31.0
137         138           Khalil Shakir       WR     player    420.747059       448.568780         26.0
138         139            Daniel Jones       QB     player    376.415437       316.042929         29.0
139         140            Tyrone Tracy       RB     player    370.669309       354.149460         26.0
140         141          Rashid Shaheed       WR     player    368.756880       389.138572          NaN
141         142         Brenton Strange       TE     player    368.614049       389.800761         25.0
142         143         Omar Cooper Jr.       WR     player    339.983301       312.190590         22.0
143         144            Hunter Henry       TE     player    311.839785       300.554492         31.0
144         145       Chigoziem Okonkwo       TE     player    310.437097       337.861377         26.0
145         146             Bryce Young       QB     player    301.532432       335.565789         25.0
146         147          Tyler Allgeier       RB     player    287.789867       250.873666         26.0
147         148          T.J. Hockenson       TE     player    264.478275       247.663743         29.0
148         149           Jonah Coleman       RB     player    260.229125       362.186971         23.0
149         150         Chris Rodriguez       RB     player    259.365990       218.735942         25.0
150         151             Jalen Coker       WR     player    253.698357       245.426901          NaN
151         152           Juwan Johnson       TE     player    246.200293       251.668292          NaN
152         153             Woody Marks       RB     player    236.525799       213.701754         25.0
153         154            Tyler Shough       QB     player    203.569558       193.726639         26.0
154         155            Alvin Kamara       RB     player    185.992508       161.772758         31.0
155         156          Jauan Jennings       WR     player    185.018893       177.448963         29.0
156         157           Isiah Pacheco       RB     player    171.239767       162.037633         27.0
157         158            Tyjae Spears       RB     player    169.767120       169.276132         25.0
158         159        Antonio Williams       WR     player    155.182517        63.356224         22.0
159         160            Ja'Kobi Lane       WR     player    153.239501       141.047642         22.0
160         161           Dylan Sampson       RB     player    149.044991       134.274752         21.0
161         162          Brian Robinson       RB     player    132.015271       130.182749         27.0
162         163            Jalen Nailor       WR     player    126.693081       149.421053         27.0
163         164           Aaron Rodgers       QB     player    123.481872        99.324336         42.0
164         165            Malik Willis       QB     player    100.904996       102.989378         27.0
165         166         Keaton Mitchell       RB     player     66.423875        59.812865          NaN
166         167               AJ Barner       TE     player     59.161721        51.590643         24.0
167         168         Jacoby Brissett       QB     player     38.501011        28.789474         33.0
168         169              Tre Tucker       WR     player     36.441197         8.947368         25.0

### Redraft -- 12 team -- Top 200

In [18]:
boards[("redraft", 12)][
    ["board_rank", "name", "position", "asset_type", "model_value", "consensus_value", "current_age"]
].head(200)

     board_rank                    name position asset_type   model_value  consensus_value  current_age
0             1            Jahmyr Gibbs       RB     player  10317.784987     10093.000000         24.0
1             2           Ja'Marr Chase       WR     player   9983.273758      9766.883164         26.0
2             3          Bijan Robinson       RB     player   9970.596929      9951.196029         24.0
3             4              Puka Nacua       WR     player   9456.952826      9492.122868         25.0
4             5      Jaxon Smith-Njigba       WR     player   9188.142385      9376.516174         24.0
5             6       Amon-Ra St. Brown       WR     player   9076.265512      8931.980820         26.0
6             7         Jonathan Taylor       RB     player   8344.475328      8260.942052         27.0
7             8     Christian McCaffrey       RB     player   8199.223681      8012.616734         30.0
8             9             CeeDee Lamb       WR     player   8073.080817      8036.159367         27.0
9            10              James Cook       RB     player   8018.147757      8074.358443         26.0
10           11           Ashton Jeanty       RB     player   7955.901599      8067.030221         22.0
11           12           De'Von Achane       RB     player   7694.688127      7540.749908         24.0
12           13        Justin Jefferson       WR     player   7644.093683      7851.083875         27.0
13           14         Omarion Hampton       RB     player   7635.159017      7599.813683         23.0
14           15            Trey McBride       TE     player   6845.004853      6698.266194         26.0
15           16            Brock Bowers       TE     player   6590.012764      6625.352758         23.0
16           17          Saquon Barkley       RB     player   6563.464368      6595.658897         29.0
17           18      Kenneth Walker III       RB     player   6354.211561      6324.154245         25.0
18           19            Drake London       WR     player   6278.349783      6449.038850         25.0
19           20              Josh Allen       QB     player   6202.815340      6683.212438         30.0
20           21             Chase Brown       RB     player   6010.086627      5978.310064         26.0
21           22          George Pickens       WR     player   5733.705991      5644.355192         25.0
22           23            Malik Nabers       WR     player   5461.162712      5427.088875         23.0
23           24            Nico Collins       WR     player   5265.057540      5303.794177         27.0
24           25              A.J. Brown       WR     player   5162.590233      5332.290885         29.0
25           26             Breece Hall       RB     player   4921.334830      4909.115569         25.0
26           27           Lamar Jackson       QB     player   4876.010224      5080.737650         29.0
27           28           Derrick Henry       RB     player   4735.603394      4953.301251         32.0
28           29          Kyren Williams       RB     player   4494.758915      4466.531438         26.0
29           30           DeVonta Smith       WR     player   4133.828048      4162.277512         27.0
30           31             Rashee Rice       WR     player   4079.657959      4112.125322         26.0
31           32              Joe Burrow       QB     player   3961.160497      4052.875000         29.0
32           33             Chris Olave       WR     player   3872.232927      4528.326954         26.0
33           34            Emeka Egbuka       WR     player   3789.400308      3741.204433         23.0
34           35            Cam Skattebo       RB     player   3766.437145      3743.190999         24.0
35           36             Tee Higgins       WR     player   3761.735937      3742.970269         27.0
36           37              Drake Maye       QB     player   3760.382851      3592.812416         24.0
37           38       Tetairoa McMillan       WR     player   3735.309221      3740.983703         23.0
38           39             Josh Jacobs       RB     player   3719.870198      3742.434957         28.0
39           40        Javonte Williams       RB     player   3689.683077      3759.944465         26.0
40           41        Colston Loveland       TE     player   3681.252797      3886.852564         22.0
41           42        Quinshon Judkins       RB     player   3604.589177      3690.602564         22.0
42           43           Ladd McConkey       WR     player   3573.713300      3742.906831         24.0
43           44          Garrett Wilson       WR     player   3458.039536      3551.980923         26.0
44           45             Zay Flowers       WR     player   3413.531524      3372.440989         25.0
45           46            Tyler Warren       TE     player   3064.189554      3002.057130         24.0
46           47           Jaylen Waddle       WR     player   3031.606511      2995.958737         27.0
47           48            Bucky Irving       RB     player   3026.095640      2978.212183         24.0
48           49      TreVeyon Henderson       RB     player   3005.182849      2973.275488         23.0
49           50          Travis Etienne       RB     player   2926.612091      2873.797663         27.0
50           51          Jayden Daniels       QB     player   2872.008152      2999.209719         25.0
51           52           Luther Burden       WR     player   2631.775793      2663.611244         22.0
52           53          Caleb Williams       QB     player   2630.012296      2991.213052         24.0
53           54           D'Andre Swift       RB     player   2563.295982      2492.527870         27.0
54           55             Jalen Hurts       QB     player   2467.654473      2500.577782         28.0
55           56        David Montgomery       RB     player   2467.356016      2505.646914         29.0
56           57          Justin Herbert       QB     player   2398.590623      2472.429150         28.0
57           58         Trevor Lawrence       QB     player   2265.044908      2192.795199         26.0
58           59             Rome Odunze       WR     player   2234.245549      2272.893387         24.0
59           60           Davante Adams       WR     player   2228.499090      2288.918354         33.0
60           61         Patrick Mahomes       QB     player   2213.056175      2236.917842         30.0
61           62          Terry McLaurin       WR     player   2161.174358      2181.179436         30.0
62           63            Tucker Kraft       TE     player   2066.429700      2197.919550         25.0
63           64        Jameson Williams       WR     player   2063.525298      2281.634278         25.0
64           65             Jaxson Dart       QB     player   1995.295325      2092.619863         23.0
65           66     Marvin Harrison Jr.       WR     player   1917.212915      1915.452828         24.0
66           67              D.J. Moore       WR     player   1769.585834      1773.411759         29.0
67           68        Brian Thomas Jr.       WR     player   1730.079600      1679.397415         23.0
68           69             Sam LaPorta       TE     player   1674.849307      1630.534157         25.0
69           70          Bhayshul Tuten       RB     player   1673.184113      1898.473684         23.0
70           71           Harold Fannin       TE     player   1670.119310      1853.335991         22.0
71           72                  Bo Nix       QB     player   1598.409578      1476.987793         26.0
72           73              Mike Evans       WR     player   1587.401102      1604.819061         33.0
73           74           Jaylen Warren       RB     player   1572.863007      1610.398131          NaN
74           75              Kyle Pitts       TE     player   1553.857997      1506.886977         25.0
75           76            Dak Prescott       QB     player   1492.099198      1741.301088         33.0
76           77              DK Metcalf       WR     player   1485.234850      1462.258527         28.0
77           78        Christian Watson       WR     player   1468.321104      1456.828579         27.0
78           79             Brock Purdy       QB     player   1446.640585      1808.439455         26.0
79           80            Jordyn Tyson       WR     player   1424.082976      1715.646424         22.0
80           81          Jeremiyah Love       RB     player   1413.245467      5642.280334         21.0
81           82               RJ Harvey       RB     player   1217.589580      1194.440130         25.0
82           83           George Kittle       TE     player   1202.147809      1181.295424         32.0
83           84             Jordan Love       QB     player   1183.097903      1238.310606         27.0
84           85     Rhamondre Stevenson       RB     player   1162.850105      1189.523249         28.0
85           86         Michael Pittman       WR     player   1157.385277      1184.225739         28.0
86           87           Chuba Hubbard       RB     player   1151.005421      1312.633317         27.0
87           88          Baker Mayfield       QB     player   1096.881442      1121.230069         31.0
88           89            Travis Kelce       TE     player   1057.830020      1097.208175         36.0
89           90             Rico Dowdle       RB     player   1045.463608      1007.824561          NaN
90           91       Parker Washington       WR     player   1034.240857      1034.502924         24.0
91           92            J.K. Dobbins       RB     player   1034.023851      1032.038748         27.0
92           93             Makai Lemon       WR     player   1025.064243      1198.976383         22.0
93           94             Alec Pierce       WR     player    996.028269      1030.537787         26.0
94           95        Matthew Stafford       QB     player    988.780544      1246.058214         38.0
95           96              Jared Goff       QB     player    968.596243       820.260806         31.0
96           97        Courtland Sutton       WR     player    925.483418       873.575635         30.0
97           98             Blake Corum       RB     player    887.373383       961.969636         25.0
98           99          Michael Wilson       WR     player    864.169335       892.204678         26.0
99          100        Quentin Johnston       WR     player    843.725975       807.127101         25.0
100         101            Carnell Tate       WR     player    835.431150      2582.840909         21.0
101         102       Wan'Dale Robinson       WR     player    818.380561       797.438228         25.0
102         103            Chris Godwin       WR     player    818.286988       856.176236         30.0
103         104        Fernando Mendoza       QB     player    787.945427       375.020734         22.0
104         105             Aaron Jones       RB     player    778.597552       797.892897         31.0
105         106            Tony Pollard       RB     player    770.633119       764.341594         29.0
106         107           Jake Ferguson       TE     player    764.790034       766.934589         27.0
107         108            Stefon Diggs       WR     player    743.689006       708.726578         32.0
108         109          Matthew Golden       WR     player    741.402431       713.406883         23.0
109         110              Josh Downs       WR     player    736.025744       882.747209         25.0
110         111           KC Concepcion       WR     player    730.565910       757.834417         21.0
111         112          Dalton Kincaid       TE     player    730.044784       698.735779         26.0
112         113          Jordan Addison       WR     player    721.739753       766.417525         24.0
113         114  Jacory Croskey-Merritt       RB     player    696.702873       765.163191         25.0
114         115            Mark Andrews       TE     player    691.351501       708.001472         31.0
115         116             Jayden Reed       WR     player    688.898933       699.177238         26.0
116         117           Kyle Monangai       RB     player    688.318728       708.157895         24.0
117         118        Kenneth Gainwell       RB     player    686.447825       757.507668         27.0
118         119          Jadarian Price       RB     player    659.177228      2123.690682         22.0
119         120           Isaiah Likely       TE     player    644.824543       756.329499         26.0
120         121            Deebo Samuel       WR     player    639.439128       621.961477         30.0
121         122            Jordan Mason       RB     player    639.144796       684.400319          NaN
122         123           Jakobi Meyers       WR     player    636.769361       594.681532          NaN
123         124           Rachaad White       RB     player    618.864968       605.922954         27.0
124         125            Kenyon Sadiq       TE     player    612.883860       481.232732         21.0
125         126            Kyler Murray       QB     player    596.107586       539.465260         29.0
126         127             Romeo Doubs       WR     player    590.435030       607.737456         26.0
127         128          Jayden Higgins       WR     player    574.870392       594.996115         23.0
128         129             C.J. Stroud       QB     player    568.788452       533.315513         24.0
129         130           Denzel Boston       WR     player    564.061302       564.021838         22.0
130         131           Xavier Worthy       WR     player    556.552781       649.464391         23.0
131         132         Jonathon Brooks       RB     player    534.309239       551.572363         23.0
132         133             Sam Darnold       QB     player    531.657560       594.240073         29.0
133         134          Oronde Gadsden       TE     player    529.826779       508.567395         23.0
134         135         Zach Charbonnet       RB     player    512.004359       491.622500         25.0
135         136                Cam Ward       QB     player    497.794164       582.839406         24.0
136         137          Dallas Goedert       TE     player    468.645074       484.335112         31.0
137         138           Khalil Shakir       WR     player    438.884012       445.951969         26.0
138         139          Rashid Shaheed       WR     player    383.006594       392.138572          NaN
139         140         Brenton Strange       TE     player    378.567202       392.800761         25.0
140         141            Daniel Jones       QB     player    375.542889       318.042929         29.0
141         142            Tyrone Tracy       RB     player    365.977505       357.149460         26.0
142         143         Omar Cooper Jr.       WR     player    330.540414       314.190590         22.0
143         144       Chigoziem Okonkwo       TE     player    319.226295       340.235329         26.0
144         145             Bryce Young       QB     player    317.825130       337.763158         25.0
145         146            Hunter Henry       TE     player    311.063822       302.554492         31.0
146         147          Tyler Allgeier       RB     player    279.223509       252.873666         26.0
147         148          T.J. Hockenson       TE     player    266.155611       249.663743         29.0
148         149           Jonah Coleman       RB     player    260.613891       365.186971         23.0
149         150           Juwan Johnson       TE     player    251.547988       253.668292          NaN
150         151         Chris Rodriguez       RB     player    250.168891       225.219073         25.0
151         152             Jalen Coker       WR     player    244.844111       247.426901          NaN
152         153             Woody Marks       RB     player    234.899432       214.836257         25.0
153         154            Tyler Shough       QB     player    213.652143       202.188627         26.0
154         155          Jauan Jennings       WR     player    192.808826       181.772359         29.0
155         156            Alvin Kamara       RB     player    191.615491       165.727355         31.0
156         157           Isiah Pacheco       RB     player    184.127626       166.433689         27.0
157         158            Tyjae Spears       RB     player    178.522246       175.276132         25.0
158         159        Antonio Williams       WR     player    159.547699        63.356224         22.0
159         160           Dylan Sampson       RB     player    150.987100       134.547029         21.0
160         161            Ja'Kobi Lane       WR     player    142.706840       141.095285         22.0
161         162          Brian Robinson       RB     player    134.935621       131.405635         27.0
162         163            Jalen Nailor       WR     player    130.063729       150.421053         27.0
163         164           Aaron Rodgers       QB     player    121.516059        99.986505         42.0
164         165            Malik Willis       QB     player    101.143469       103.989378         27.0
165         166         Keaton Mitchell       RB     player     65.540789        59.812865          NaN
166         167               AJ Barner       TE     player     58.365372        52.590643         24.0
167         168         Jacoby Brissett       QB     player     43.733885        29.789474         33.0
168         169              Tre Tucker       WR     player     37.108591         8.964912         25.0

## Stage 9 -- Divergence tables

Largest model-vs-consensus gaps, player rows only (picks are priced directly from blended market
data, not model-predicted, so they always show zero residual and carry no signal here). These are
**candidates to investigate** -- fundamentals the model weighs differently than the market
currently prices them -- never a claim that the model is right and the market is wrong.

In [19]:
divergence_tables = tcp.build_all_divergence_tables(boards)
for (fmt, team_size), div_df in divergence_tables.items():
    print(f"\n=== {fmt} - {team_size} team ===")
    display(div_df)

=== sf_dynasty - 10 team ===

                 name position  model_value  consensus_value     residual  residual_pct
0     Omar Cooper Jr.       WR  2652.160150      1960.922112   691.238038     35.250663
1         C.J. Stroud       QB  3381.451811      3202.613988   178.837823      5.584120
2        Dak Prescott       QB  4083.537489      3914.681191   168.856298      4.313411
3       J.J. McCarthy       QB  1549.309291      1385.585096   163.724195     11.816250
4   Tetairoa McMillan       WR  5263.893109      5104.292371   159.600738      3.126795
5           Joe Mixon       RB   255.401529       109.736181   145.665348    132.741405
6       Harold Fannin       TE  3390.100404      3246.488983   143.611421      4.423592
7        Jack Endries       TE   207.944890        68.609399   139.335490    203.085134
8       Will Kacmarek       TE   364.689983       236.840452   127.849531     53.981290
9         Jalen Hurts       QB  5222.509149      5107.755639   114.753510      2.246652
10       Josh Cameron       WR   327.545893       216.801508   110.744385     51.081003
11             Bo Nix       QB  4925.499187      4814.827952   110.671235      2.298550
12          Sam Roush       TE   207.297287        99.000000   108.297287    109.391199
13      Justin Fields       QB   787.532839       682.923708   104.609131     15.317836
14  Ja'Tavion Sanders       TE   696.668968       605.976791    90.692177     14.966279
15     Jeremiyah Love       RB  4494.874502      6862.726563 -2367.852061    -34.503080
16        Cyrus Allen       WR   407.982123      1452.878770 -1044.896647    -71.919053
17        Eli Stowers       TE   960.290214      1980.960371 -1020.670157    -51.524007
18        Eli Raridon       TE   608.591724      1298.010726  -689.419002    -53.113506
19      Derrick Henry       RB  2509.636091      3145.809912  -636.173821    -20.222895
20   Demond Claiborne       RB   585.856626      1164.011563  -578.154938    -49.669175
21          Ted Hurst       WR   837.871334      1377.617733  -539.746399    -39.179693
22   Fernando Mendoza       QB  3433.089503      3951.351850  -518.262347    -13.116077
23      Kaytron Allen       RB   592.727283      1020.563116  -427.835833    -41.921546
24        Chris Olave       WR  3939.825248      4354.241041  -414.415793     -9.517521
25          Max Klare       TE   448.140387       844.401889  -396.261503    -46.928069
26      Jonah Coleman       RB  1308.838569      1691.294971  -382.456402    -22.613229
27       Kaelon Black       RB   791.354902      1157.797073  -366.442171    -31.649948
28     Malachi Fields       WR  1021.944473      1380.660896  -358.716423    -25.981501
29   Zachariah Branch       WR  1202.542457      1526.905200  -324.362743    -21.243149

=== sf_dynasty - 12 team ===

                 name position   model_value  consensus_value     residual  residual_pct
0         C.J. Stroud       QB   3516.672658      3258.202867   258.469791      7.932894
1     Omar Cooper Jr.       WR   2189.983172      1970.384422   219.598749     11.144970
2       J.J. McCarthy       QB   1637.469423      1423.613598   213.855825     15.022041
3       Justin Fields       QB    874.110492       685.005930   189.104562     27.606266
4           Sam Roush       TE    283.137835       100.632186   182.505649    181.359122
5        Brock Bowers       TE   8001.179628      7839.832817   161.346811      2.058039
6        Jahmyr Gibbs       RB  10362.818432     10208.844721   153.973711      1.508238
7         Breece Hall       RB   4013.540949      3863.386566   150.154383      3.886600
8      Baker Mayfield       QB   3462.280051      3313.333177   148.946874      4.495379
9   Tetairoa McMillan       WR   5143.774607      4999.390235   144.384372      2.888040
10          Joe Mixon       RB    252.643817       109.472362   143.171455    130.783198
11   Colston Loveland       TE   5468.535558      5325.732870   142.802688      2.681372
12      Harold Fannin       TE   3421.545465      3287.491627   134.053838      4.077694
13       Tyler Warren       TE   5003.393565      4880.524112   122.869454      2.517546
14       Dak Prescott       QB   4098.842745      3983.158089   115.684655      2.904345
15     Jeremiyah Love       RB   4870.548387      6986.469740 -2115.921353    -30.285988
16        Cyrus Allen       WR    355.296434      1460.582036 -1105.285602    -75.674325
17   Fernando Mendoza       QB   3173.650590      4095.351013  -921.700422    -22.506018
18        Eli Stowers       TE   1117.366490      2011.480521  -894.114030    -44.450544
19        Eli Raridon       TE    499.626213      1285.590238  -785.964025    -61.136434
20      Derrick Henry       RB   2438.645544      3134.380346  -695.734802    -22.196885
21        Chris Olave       WR   3673.299982      4291.537354  -618.237372    -14.405965
22   Demond Claiborne       RB    583.335299      1165.001904  -581.666605    -49.928382
23          Ted Hurst       WR    822.324818      1385.022166  -562.697349    -40.627317
24   Zachariah Branch       WR   1001.145787      1517.091232  -515.945446    -34.008861
25          Max Klare       TE    383.528379       841.847999  -458.319620    -54.442087
26     Jadarian Price       RB   2854.277328      3308.299358  -454.022030    -13.723729
27   Antonio Williams       WR   1213.168991      1646.056331  -432.887340    -26.298452
28      Kaytron Allen       RB    645.771937      1026.563116  -380.791180    -37.093791
29     Jayden Daniels       QB   6686.107294      7048.060656  -361.953362     -5.135503

=== oneqb_dynasty - 10 team ===

                 name position  model_value  consensus_value     residual  residual_pct
0     Omar Cooper Jr.       WR  2428.427286      1946.291508   482.135778     24.772023
1        Tyler Warren       TE  4606.742671      4426.560117   180.182554      4.070487
2       J.J. McCarthy       QB   905.846159       742.373561   163.472597     22.020261
3         Breece Hall       RB  4225.053764      4064.373454   160.680310      3.953384
4           Sam Roush       TE   202.108271        80.732694   121.375577    150.342533
5           Joe Mixon       RB   238.961211       117.690955   121.270257    103.041272
6    Nate Boerkircher       TE   238.733610       126.670854   112.062756     88.467672
7         Jalen Hurts       QB  2952.051478      2841.000000   111.051478      3.908887
8      Germie Bernard       WR  1502.073827      1396.601977   105.471850      7.552034
9   Tetairoa McMillan       WR  5280.899474      5178.057314   102.842160      1.986115
10  Amon-Ra St. Brown       WR  7368.683118      7266.905820   101.777297      1.400559
11  Michael Penix Jr.       QB   946.094802       845.933445   100.161358     11.840335
12     Baker Mayfield       QB  1864.251329      1771.275935    92.975393      5.249063
13      Harold Fannin       TE  3142.651899      3052.975182    89.676717      2.937355
14     George Pickens       WR  4872.832553      4788.390475    84.442078      1.763475
15     Jeremiyah Love       RB  3677.915121      7276.127777 -3598.212657    -49.452302
16        Cyrus Allen       WR   481.845671      1344.931797  -863.086127    -64.173226
17   Fernando Mendoza       QB  1372.778060      2194.353429  -821.575369    -37.440430
18        Eli Raridon       TE   340.992195      1144.506537  -803.514342    -70.206182
19   Demond Claiborne       RB   378.694184      1160.200349  -781.506165    -67.359587
20        Eli Stowers       TE  1040.689383      1819.897349  -779.207966    -42.816039
21     Jadarian Price       RB  2966.315252      3583.852244  -617.536991    -17.231095
22       Carnell Tate       WR  3918.323221      4518.327281  -600.004059    -13.279340
23          Ted Hurst       WR   796.164512      1314.460270  -518.295758    -39.430310
24       Kaelon Black       RB   667.640551      1165.105405  -497.464854    -42.696983
25   Antonio Williams       WR  1179.827982      1649.640171  -469.812189    -28.479677
26          Max Klare       TE   325.736333       784.185641  -458.449308    -58.461834
27   Zachariah Branch       WR   994.313146      1439.024257  -444.711111    -30.903656
28      Derrick Henry       RB  2809.212174      3236.491129  -427.278955    -13.201920
29         Chris Bell       WR  1074.535930      1409.628459  -335.092529    -23.771692

=== oneqb_dynasty - 12 team ===

                 name position  model_value  consensus_value     residual  residual_pct
0     Omar Cooper Jr.       WR  2380.135644      1958.291508   421.844136     21.541437
1      Germie Bernard       WR  1739.517255      1405.601977   333.915278     23.756034
2    Nate Boerkircher       TE   283.739515       127.839196   155.900319    121.950328
3           Sam Roush       TE   220.765200        85.022071   135.743129    159.656343
4       J.J. McCarthy       QB   901.990826       769.812128   132.178698     17.170254
5         Jalen Hurts       QB  3102.123428      2970.697839   131.425589      4.424065
6      Caleb Williams       QB  3928.983379      3808.495439   120.487940      3.163662
7        Dak Prescott       QB  2344.779754      2226.127204   118.652550      5.329999
8        Brock Bowers       TE  7309.398689      7195.210709   114.187980      1.587000
9       Harold Fannin       TE  3214.445082      3103.293586   111.151496      3.581727
10  Amon-Ra St. Brown       WR  7333.105523      7233.085765   100.019758      1.382809
11       Tyler Warren       TE  4603.511962      4504.588651    98.923311      2.196056
12          Joe Mixon       RB   215.632334       117.381910    98.250424     83.701505
13        C.J. Stroud       QB  1884.071960      1790.913000    93.158960      5.201758
14         Puka Nacua       WR  8364.843255      8279.937128    84.906128      1.025444
15     Jeremiyah Love       RB  4288.180373      7237.515526 -2949.335153    -40.750657
16        Cyrus Allen       WR   478.764160      1364.443941  -885.679781    -64.911409
17        Eli Raridon       TE   382.181431      1151.506537  -769.325106    -66.810312
18   Demond Claiborne       RB   458.404585      1155.000000  -696.595415    -60.311291
19        Eli Stowers       TE  1132.495855      1826.979636  -694.483780    -38.012672
20      KC Concepcion       WR  2098.314087      2717.132851  -618.818764    -22.774697
21   Fernando Mendoza       QB  1663.933719      2229.415446  -565.481727    -25.364574
22     Jadarian Price       RB  2991.396876      3545.635714  -554.238838    -15.631579
23          Ted Hurst       WR   847.483358      1320.350471  -472.867114    -35.813757
24          Max Klare       TE   344.061074       781.495042  -437.433968    -55.973992
25   Zachariah Branch       WR  1028.695051      1465.048513  -436.353463    -29.784233
26   Antonio Williams       WR  1219.269812      1649.924789  -430.654978    -26.101491
27       Kaelon Black       RB   729.014676      1155.000000  -425.985324    -36.881846
28      Derrick Henry       RB  2826.823546      3217.539698  -390.716152    -12.143320
29     Elijah Sarratt       WR   828.387847      1181.621191  -353.233344    -29.893958

=== redraft - 10 team ===

                  name position   model_value  consensus_value     residual  residual_pct
0     Fernando Mendoza       QB    774.368701       372.020734   402.347968    108.152028
1        Ja'Marr Chase       WR  10065.583275      9757.817630   307.765646      3.154042
2         Jahmyr Gibbs       RB  10455.525928     10200.000000   255.525928      2.505156
3   Kenneth Walker III       RB   6627.023043      6391.154245   235.868798      3.690551
4         Trey McBride       TE   6958.765651      6768.586032   190.179619      2.809739
5       Travis Etienne       RB   3043.638005      2857.231505   186.406499      6.524025
6               Bo Nix       QB   1643.069974      1456.802028   186.267946     12.786085
7    Amon-Ra St. Brown       WR   8821.936336      8650.483990   171.452347      1.981997
8           Jared Goff       QB    966.697119       820.597636   146.099483     17.804034
9      Trevor Lawrence       QB   2316.780307      2182.665154   134.115153      6.144559
10        Kenyon Sadiq       TE    579.947248       471.438188   108.509060     23.016604
11     Jonathan Taylor       RB   8446.587374      8348.486178    98.101196      1.175078
12          Drake Maye       QB   3499.387342      3403.174253    96.213089      2.827157
13        Stefon Diggs       WR    814.803700       719.604363    95.199337     13.229400
14        Brock Bowers       TE   6789.288296      6694.902292    94.386004      1.409819
15      Jeremiyah Love       RB   1364.496112      5609.280334 -4244.784222    -75.674311
16        Carnell Tate       WR    929.751110      2564.871795 -1635.120685    -63.750582
17      Jadarian Price       RB    731.122784      2176.043267 -1444.920483    -66.401275
18         Chris Olave       WR   4078.973504      4565.987609  -487.014105    -10.666128
19       Lamar Jackson       QB   4697.577108      5093.765601  -396.188494     -7.777910
20         Makai Lemon       WR    798.108408      1191.991341  -393.882932    -33.044110
21      Caleb Williams       QB   2600.590350      2973.213052  -372.622701    -12.532661
22         Brock Purdy       QB   1367.366671      1725.065769  -357.699099    -20.735389
23        Dak Prescott       QB   1362.852589      1685.301088  -322.448499    -19.132991
24        Jordyn Tyson       WR   1370.002689      1666.091768  -296.089079    -17.771475
25      Bhayshul Tuten       RB   1609.156513      1888.701754  -279.545242    -14.800920
26       Derrick Henry       RB   4847.272746      5123.762749  -276.490003     -5.396230
27    Colston Loveland       TE   3653.675667      3915.261348  -261.585681     -6.681181
28       Ladd McConkey       WR   3484.606784      3744.738503  -260.131719     -6.946592
29          Josh Allen       QB   6171.753481      6418.861541  -247.108060     -3.849718

=== redraft - 12 team ===

                   name position   model_value  consensus_value     residual  residual_pct
0      Fernando Mendoza       QB    787.945427       375.020734   412.924694    110.107164
1          Jahmyr Gibbs       RB  10317.784987     10093.000000   224.784987      2.227137
2         Ja'Marr Chase       WR   9983.273758      9766.883164   216.390594      2.215554
3   Christian McCaffrey       RB   8199.223681      8012.616734   186.606947      2.328914
4            Drake Maye       QB   3760.382851      3592.812416   167.570435      4.664046
5         De'Von Achane       RB   7694.688127      7540.749908   153.938219      2.041418
6            Jared Goff       QB    968.596243       820.260806   148.335436     18.083936
7          Trey McBride       TE   6845.004853      6698.266194   146.738658      2.190696
8     Amon-Ra St. Brown       WR   9076.265512      8931.980820   144.284692      1.615372
9          Kenyon Sadiq       TE    612.883860       481.232732   131.651128     27.357060
10               Bo Nix       QB   1598.409578      1476.987793   121.421785      8.220906
11     Antonio Williams       WR    159.547699        63.356224    96.191474    151.826400
12       George Pickens       WR   5733.705991      5644.355192    89.350800      1.583012
13      Jonathan Taylor       RB   8344.475328      8260.942052    83.533276      1.011183
14      Trevor Lawrence       QB   2265.044908      2192.795199    72.249709      3.294868
15       Jeremiyah Love       RB   1413.245467      5642.280334 -4229.034866    -74.952583
16         Carnell Tate       WR    835.431150      2582.840909 -1747.409759    -67.654564
17       Jadarian Price       RB    659.177228      2123.690682 -1464.513454    -68.960770
18          Chris Olave       WR   3872.232927      4528.326954  -656.094027    -14.488663
19           Josh Allen       QB   6202.815340      6683.212438  -480.397098     -7.188117
20          Brock Purdy       QB   1446.640585      1808.439455  -361.798871    -20.006137
21       Caleb Williams       QB   2630.012296      2991.213052  -361.200756    -12.075394
22         Jordyn Tyson       WR   1424.082976      1715.646424  -291.563447    -16.994379
23     Matthew Stafford       QB    988.780544      1246.058214  -257.277669    -20.647323
24         Dak Prescott       QB   1492.099198      1741.301088  -249.201890    -14.311246
25       Bhayshul Tuten       RB   1673.184113      1898.473684  -225.289571    -11.866879
26     Jameson Williams       WR   2063.525298      2281.634278  -218.108980     -9.559331
27        Derrick Henry       RB   4735.603394      4953.301251  -217.697857     -4.395005
28     Justin Jefferson       WR   7644.093683      7851.083875  -206.990192     -2.636454
29     Colston Loveland       TE   3681.252797      3886.852564  -205.599767     -5.289621

## Stage 10 -- Sanity panel

~20 fixed, real-world-unambiguous checks (absolute top-N and pairwise orderings), run every
execution, with each player's raw feature values printed alongside any failure so the "why" is
inspectable rather than just a pass/fail flag.

In [20]:
sanity_results = tcp.run_sanity_panel(boards, feature_table)
sanity_results

!!! SANITY CHECK FAILED !!! Josh Jacobs rank 69 (needed top-60) on ('oneqb_dynasty', 10)
    feature decomposition: position='RB', current_age=np.float64(28.0), career_games=np.float64(105.0), seasons_played=np.float64(7.0), ppg_ppr=np.float64(15.806666666666668), round=np.float64(1.0), pick=np.float64(24.0), dominator_rating=np.float64(nan), speed_score=np.float64(nan)

[sanity_panel] 18 passed, 1 failed, 1 skipped (player not found) of 20 checks

                              check                board passed                                            detail
0                 Puka Nacua top-10     (sf_dynasty, 12)   True             rank=7 (need <= 10), model_value=8371
1              Bijan Robinson top-5     (sf_dynasty, 12)   True             rank=2 (need <= 5), model_value=10248
2                Jahmyr Gibbs top-8     (sf_dynasty, 12)   True             rank=1 (need <= 8), model_value=10363
3              Ja'Marr Chase top-10     (sf_dynasty, 12)   True            rank=3 (need <= 10), model_value=10036
4           Justin Jefferson top-30     (sf_dynasty, 12)   True            rank=15 (need <= 30), model_value=6872
5          Amon-Ra St. Brown top-15     (sf_dynasty, 12)   True             rank=9 (need <= 15), model_value=7377
6                CeeDee Lamb top-20     (sf_dynasty, 12)   True            rank=17 (need <= 20), model_value=6522
7                 Josh Allen top-20  (oneqb_dynasty, 12)   True            rank=15 (need <= 20), model_value=5726
8              Lamar Jackson top-20     (sf_dynasty, 12)   True            rank=12 (need <= 20), model_value=7068
9               Brock Bowers top-10     (sf_dynasty, 12)   True             rank=8 (need <= 10), model_value=8001
10              Trey McBride top-30     (sf_dynasty, 12)   True            rank=18 (need <= 30), model_value=6439
11            Saquon Barkley top-25        (redraft, 12)   True            rank=17 (need <= 25), model_value=6563
12           Jonathan Taylor top-15        (redraft, 12)   True             rank=7 (need <= 15), model_value=8344
13               Josh Jacobs top-60  (oneqb_dynasty, 10)  False            rank=69 (need <= 60), model_value=2906
14         Brock Bowers > Noah Fant     (sf_dynasty, 12)   True         Brock Bowers rank=8 vs Noah Fant rank=375
15          Josh Allen > Joe Flacco  (oneqb_dynasty, 12)   True         Josh Allen rank=15 vs Joe Flacco rank=359
16  Bijan Robinson > Kenny Gainwell     (sf_dynasty, 12)   None    'Kenny Gainwell' not found on board -- SKIPPED
17      Puka Nacua > Xavier Legette     (sf_dynasty, 12)   True      Puka Nacua rank=7 vs Xavier Legette rank=281
18   Ja'Marr Chase > Andrei Iosivas     (sf_dynasty, 12)   True   Ja'Marr Chase rank=3 vs Andrei Iosivas rank=342
19  Jahmyr Gibbs > Devin Singletary     (sf_dynasty, 12)   True  Jahmyr Gibbs rank=1 vs Devin Singletary rank=379

## Stage 11 -- In-season update

`recompute_board(through_week=None, ...)` reproduces the preseason boards unchanged -- this is the
identity case, confirmed exactly equal below. Once the 2026 season is underway, calling
`tcp.recompute_board(through_week=<int>, feature_table, crosswalk, consensus_targets,
pick_universe, fit_results)` blends that many weeks of real partial-season production into the
feature snapshot (empirical-Bayes shrinkage against the prior-season baseline, with a `MIN_GAMES`
guard against small-sample noise) and re-predicts with the already-fitted models -- no retraining
required. Each call snapshots every board to `snapshots/{date}_{format}_{team_size}.csv` for
week-over-week movement tracking.

In [21]:
preseason_again = tcp.recompute_board(
    None, feature_table, crosswalk, consensus_targets, pick_universe, fit_results, write_snapshot=False
)
import numpy as np
same = np.allclose(
    preseason_again[("sf_dynasty", 12)]["model_value"].sort_index(),
    boards[("sf_dynasty", 12)]["model_value"].sort_index(),
)
print(f"recompute_board(through_week=None) reproduces the original boards exactly: {same}")
assert same

recompute_board(through_week=None) reproduces the original boards exactly: True

---

## Scope, exclusions, and setup

See `README.md` in this directory for full methodology, known exclusions (K/DST/IDP not modeled,
TE premium not modeled, CFBD rookie college-production features degrade gracefully when the
free-tier monthly quota is exhausted), and setup instructions.

**Setup reminder:** this notebook requires a `CFBD_API_KEY` set in a gitignored `.env` file in this
directory (`CFBD_API_KEY=your_key_here`) -- get a free key at
[collegefootballdata.com/key](https://collegefootballdata.com/key). The key is never hardcoded or
printed anywhere in this notebook or in `trade_calculator_pipeline.py`.