<a href="https://colab.research.google.com/github/TylerWichman/Tyler_Wichman_Portfolio/blob/main/Fantasy_Trade_Calculator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Fantasy Trade Calculator

A dynasty/redraft fantasy football trade calculator that trains supervised gradient-boosting
models to predict market consensus value (FantasyCalc, blended with KeepTradeCut) from player
fundamentals, producing one unified value board per format that puts every player and draft pick
on the same directly-comparable scale.

**Consensus value is the training target, not a benchmark to beat.** These models are trained to
reflect the fantasy trade market as closely as possible -- agreement with FantasyCalc/KeepTradeCut
consensus is the design goal, not an independent finding. Where a player's model-predicted value
diverges from their current market price, that divergence is reported as a residual: a candidate
worth investigating, never a claim that the model is right and the market is wrong.

Full methodology, scope, and known exclusions: see `README.md` in this directory.

This notebook is a thin orchestration layer -- all real logic lives in
`trade_calculator_pipeline.py`, which is imported and called stage by stage below.

In [ ]:
import pandas as pd

import trade_calculator_pipeline as tcp

pd.set_option("display.max_rows", 250)
pd.set_option("display.max_columns", 50)
pd.set_option("display.width", 160)

## Stage 1 -- ID crosswalk

Built from nflreadpy's `load_ff_playerids()`, the backbone every source join uses.

In [ ]:
crosswalk = tcp.build_crosswalk()
print(f"crosswalk rows: {len(crosswalk)}")
crosswalk.head()

crosswalk rows: 12472

   mfl_id  sleeper_id    espn_id     gsis_id  ktc_id    pfr_id                name position          merge_name
0   17462     13269.0  4837248.0  00-0041562  1924.0  MendFe00    Fernando Mendoza       QB    fernando mendoza
1   17463     13275.0  4685522.0  00-0041568  1925.0  SimpTy00          Ty Simpson       QB          ty simpson
2   17464         NaN        NaN         NaN     NaN       NaN  Trinidad Chambliss       XX  trinidad chambliss
3   17465     13404.0  4567747.0  00-0040906  1927.0  NussGa00   Garrett Nussmeier       QB   garrett nussmeier
4   17466     13272.0  4430841.0  00-0041561  1928.0  BeckCa01         Carson Beck       QB         carson beck

## Stage 2 -- Pull FantasyCalc (6 format-teamsize combos) and KeepTradeCut (dynasty + redraft)

In [ ]:
fc_all = tcp.pull_all_fantasycalc()
for k, v in fc_all.items():
    print(f"  {k}: {len(v)} rows")

ktc_dyn = tcp.pull_ktc_dynasty()
ktc_redraft = tcp.pull_ktc_redraft()
print(f"ktc_dynasty: {len(ktc_dyn)} rows, ktc_redraft: {len(ktc_redraft)} rows")

  ('sf_dynasty', 10): 475 rows
  ('sf_dynasty', 12): 475 rows
  ('oneqb_dynasty', 10): 475 rows
  ('oneqb_dynasty', 12): 475 rows
  ('redraft', 10): 171 rows
  ('redraft', 12): 171 rows

ktc_dynasty: 500 rows, ktc_redraft: 300 rows

### Blend example -- SF dynasty, 12 team

A quick look at one format's crosswalk join + percentile blend before running the full 6-combo
version in Stage 7.

In [ ]:
fc_joined_demo = tcp.join_fantasycalc_crosswalk(fc_all[("sf_dynasty", 12)], crosswalk, label="FC-SF12")
ktc_joined_demo = tcp.join_ktc_crosswalk(ktc_dyn, crosswalk, label="KTC-dyn")
blended_demo = tcp.blend_consensus(fc_joined_demo, ktc_joined_demo, ktc_value_col="sf_value")
blended_demo[["name", "position", "value", "ktc_percentile", "fc_percentile", "consensus_value"]] \
    .sort_values("consensus_value", ascending=False).head(15)

[FC-SF12] 2 rows matched via normalized-name fallback (documented last resort)
[FC-SF12] top-200 join coverage: 100.0%
[KTC-dyn] 7 unmatched after fallback: ['Hassan Haskins', 'Stetson Bennett', 'Dylan Laube', 'Thomas Fidone', 'Sterling Shepard', 'Foster Moreau', 'Tim Patrick']
[KTC-dyn] top-200 join coverage: 100.0%

                  name position  value  ktc_percentile  fc_percentile  consensus_value
0       Bijan Robinson       RB  10438       99.781182     100.000000     10373.074617
2         Jahmyr Gibbs       RB  10189      100.000000      99.498747     10214.317293
1           Josh Allen       QB  10225       99.343545      99.749373     10204.738734
3        Ja'Marr Chase       WR  10080       99.562363      99.248120     10128.533254
4   Jaxon Smith-Njigba       WR   8777       99.124726      98.997494      9021.000136
5           Drake Maye       QB   8595       98.905908      98.746867      8637.601712
6           Puka Nacua       WR   8308       98.687090      98.496241      8388.615548
7         Brock Bowers       TE   7606       98.468271      98.245614      7836.049246
9    Amon-Ra St. Brown       WR   7264       98.249453      97.744361      7287.962937
8        Lamar Jackson       QB   7297       97.592998      97.994987      7279.182592
10       Ashton Jeanty       RB   7243       97.811816      97.493734      7252.831164
11      Caleb Williams       QB   7143       98.030635      97.243108      7245.616469
12      Jayden Daniels       QB   7060       96.717724      96.992481      7047.656858
13          Joe Burrow       QB   7025       96.498906      96.741855      6993.497849
14    Justin Jefferson       WR   6922       96.936543      96.491228      6989.507328

## Stage 3 -- Feature assembly

Draft capital, season-level production/efficiency, continuous position-specific aging curves, and
combine metrics (RB speed score).

In [ ]:
draft_capital = tcp.load_draft_capital(crosswalk)
print(f"draft_capital rows: {len(draft_capital)}")

weekly = tcp.load_weekly_features()
print(f"weekly/season feature rows: {len(weekly)}, cols: {len(weekly.columns)}")

curve_params, peak_ages, aged = tcp.fit_aging_curves(weekly, draft_capital)
print(f"peak ages by position: { {k: round(v, 1) for k, v in peak_ages.items()} }")

combine_feats = tcp.load_combine_features()
print(f"combine feature rows: {len(combine_feats)}")
combine_feats.dropna(subset=["speed_score"]).head(3)

[draft_capital] 2 duplicate gsis_id rows in load_draft_picks -- keeping first (data-entry dupes, e.g. supplemental draft)
[draft_capital] 73 rows had a non-gsis id from load_draft_picks (new/unplayed draft class) -- 73/73 repaired via crosswalk name match
[draft_capital] 1 rows still unresolved after repair attempt: ['Mike Washington Jr.']
draft_capital rows: 3551

[snap_share] 1.0% of player-season snap rows unmatched to gsis_id via pfr_id (dropped)
weekly/season feature rows: 4191, cols: 27
[aging_curve] 1261 / 4191 player-seasons have no draft-capital age match (undrafted players) -- age kept as NaN, excluded only from curve fitting
peak ages by position: {'QB': 27.0, 'RB': np.float64(26.0), 'WR': np.float64(27.2), 'TE': np.float64(32.2)}

[combine] gsis_id coverage: 64.9% (pfr_id only) -> 70.2% after normalized-name fallback (160 rows recovered)
combine feature rows: 2103

        gsis_id  forty_time  combine_weight combine_height  speed_score
56   00-0019641        4.45           216.0           5-10   110.165016
125  00-0020270        4.53           226.0            6-0   107.336054
118  00-0020514        4.38           207.0            5-9   112.487405

### Rookie college-production features (CollegeFootballData)

Dominator rating (80% yardage / 20% TD weighted share of team receiving output) and breakout age
for the current draft class. **Note:** CFBD's free-tier monthly call quota can be exhausted at
build time -- if so, this degrades gracefully to `NaN` for affected rookies, who then fall back to
draft capital + age + combine speed score alone (`HistGradientBoostingRegressor` handles missing
features natively; see README's "Known exclusions").

In [ ]:
rookie_college = tcp.compute_rookie_college_features(draft_capital, draft_year=2026)
coverage = (rookie_college["college_seasons_found"] > 0).mean()
print(f"2026 rookie CFBD college-production coverage: {coverage:.1%}"
      + ("  (degraded -- CFBD quota likely exhausted this cycle)" if coverage < 0.3 else ""))
rookie_college.sort_values("dominator_rating", ascending=False).head(10)

[cfbd_rookie] 0.0% of 2026 skill draftees matched to >=1 CFBD college season with usable receiving-dominator data (QBs excluded from this stat by design)
[cfbd_rookie] failure breakdown: 73/73 hit CFBD's monthly call quota (expected, documented free-tier limit -- resets monthly on CFBD's own cycle, re-run once available; low coverage from this alone is NOT a bug), 0/73 failed for a DIFFERENT reason (network error, non-quota HTTP error, or a parsing bug -- investigate this count specifically if it's nonzero, it means something other than the quota is the problem)
2026 rookie CFBD college-production coverage: 0.0%  (degraded -- CFBD quota likely exhausted this cycle)

      gsis_id  dominator_rating  breakout_age  college_seasons_found
0  00-0041562               NaN           NaN                      0
1  00-0041027               NaN           NaN                      0
2  00-0041438               NaN           NaN                      0
3  00-0041029               NaN           NaN                      0
4  00-0041568               NaN           NaN                      0
5  00-0041032               NaN           NaN                      0
6  00-0040867               NaN           NaN                      0
7  00-0041547               NaN           NaN                      0
8  00-0041511               NaN           NaN                      0
9  00-0041512               NaN           NaN                      0

## Stage 4 -- Draft pick valuation

2027-2029 x rounds 1-3 x {Early, Mid, Late} tiers, priced from native FantasyCalc/KeepTradeCut
market data where available, constructed via a year-discount/class-strength/format-multiplier
formula elsewhere. Redraft formats have no pick assets.

In [ ]:
pick_universe = tcp.build_pick_universe(fc_all, ktc_dyn)
print(f"pick_universe rows: {len(pick_universe)}")
pick_universe[(pick_universe["format"] == "sf_dynasty") & (pick_universe["team_size"] == 12)] \
    .sort_values("pick_value", ascending=False)[["year", "round", "tier", "fc_value", "pick_value"]]

[format_multiplier] overall mean SF/1QB pick-value ratio: 1.060
[format_multiplier] by round: {1: 1.061, 2: 1.061, 3: 1.06, 4: 1.059}
[format_multiplier] NOTE: spec §6 cites a 30-60% player-level SF premium for elite QBs; picks came out much lower (~6%). That's expected, not a bug -- a pick is position-agnostic (might become a WR/RB/etc.), so it can't carry a specific elite-QB premium the way a known franchise QB player does.

[pick_universe] 36 native FC tier prices, 72 FC-derived (aggregate x tier-ratio), 0 fully constructed (of 108 total)
pick_universe rows: 108

    year  round   tier     fc_value   pick_value
27  2027      1  Early  4532.000000  5388.800000
36  2028      1  Early  3190.750270  3886.987676
28  2027      1    Mid  2984.000000  3863.900000
29  2027      1   Late  2297.000000  3232.550000
37  2028      1    Mid  2101.090720  2963.808968
45  2029      1  Early  2910.832307  2910.832307
30  2027      2  Early  1843.000000  2495.400000
38  2028      1   Late  1617.233964  2475.002076
31  2027      2    Mid  1528.000000  2180.400000
39  2028      2  Early  1583.333802  2143.216971
32  2027      2   Late  1316.000000  1929.200000
46  2029      1    Mid  1916.766350  1916.766350
40  2028      2    Mid  1312.155871  1900.451316
41  2028      2   Late  1130.277642  1723.080467
33  2027      3  Early  1154.000000  1647.850000
48  2029      2  Early  1526.917570  1526.917570
34  2027      3    Mid  1027.000000  1526.450000
47  2029      1   Late  1475.357352  1475.357352
42  2028      3  Early  1070.648419  1473.971472
35  2027      3   Late   945.000000  1388.100000
43  2028      3    Mid   952.766470  1365.498206
49  2029      2    Mid  1265.402060  1265.402060
44  2028      3   Late   876.816018  1261.880412
50  2029      2   Late  1090.004387  1090.004387
51  2029      3  Early  1063.872163  1063.872163
52  2029      3    Mid   946.736303   946.736303
53  2029      3   Late   871.266550   871.266550

## Stage 5 -- Unified feature table

One row per player, scoped to the *active* FantasyCalc asset universe (spec §2a) -- not however far back the historical production pull happens to reach. Earlier runs let long-retired players leak into the intermediate feature table (ages 44-49 observed); this version filters to the actual set of gsis_ids FantasyCalc prices across all 6 pulls before anything downstream touches it.

In [ ]:
active_ids = tcp.active_asset_gsis_ids(fc_all, crosswalk)
print(f"active FantasyCalc asset universe: {len(active_ids)} gsis_ids")
snapshot = tcp.build_player_snapshot(aged, draft_capital, peak_ages, active_ids=active_ids)
feature_table = tcp.build_feature_table(snapshot, draft_capital, combine_feats, rookie_college)
feature_table[["gsis_id", "position", "current_age", "career_games", "ppg_ppr"]].head()

[active-universe-sf_dynasty10] 2 rows matched via normalized-name fallback (documented last resort)
[active-universe-sf_dynasty10] top-200 join coverage: 100.0%
[active-universe-sf_dynasty12] 2 rows matched via normalized-name fallback (documented last resort)
[active-universe-sf_dynasty12] top-200 join coverage: 100.0%

[active-universe-oneqb_dynasty10] 2 rows matched via normalized-name fallback (documented last resort)
[active-universe-oneqb_dynasty10] top-200 join coverage: 100.0%

[active-universe-oneqb_dynasty12] 2 rows matched via normalized-name fallback (documented last resort)
[active-universe-oneqb_dynasty12] top-200 join coverage: 100.0%
[active-universe-redraft10] top-200 join coverage: 100.0%

[active-universe-redraft12] top-200 join coverage: 100.0%
active FantasyCalc asset universe: 399 gsis_ids

[snapshot] WARNING: 17 of 73 2026 rookies are NOT in the active FantasyCalc universe -- unexpected, since FantasyCalc prices rookies too; they will be dropped along with everyone else outside the active universe
[snapshot] scoped to active FantasyCalc asset universe: 1422 -> 380 rows
[snapshot] 380 player rows (73 zero-snap 2026 rookies appended with NaN production/career features)
[feature_table] 380 rows, 44 columns

      gsis_id position  current_age  career_games    ppg_ppr
0  00-0023459       QB         42.0          99.0  14.192500
1  00-0026158       QB         41.0          45.0  11.281538
2  00-0026498       QB         38.0          98.0  20.610588
3  00-0028118       QB         37.0          32.0   9.910000
4  00-0029604       QB         38.0          96.0  10.354000

## Stage 6 -- Consensus targets for all 6 format-teamsize combos

In [ ]:
consensus_targets = tcp.build_all_consensus_targets(fc_all, ktc_dyn, ktc_redraft, crosswalk)
for k, v in consensus_targets.items():
    print(f"  {k}: {len(v)} players with a consensus target")

[KTC-dyn] 7 unmatched after fallback: ['Hassan Haskins', 'Stetson Bennett', 'Dylan Laube', 'Thomas Fidone', 'Sterling Shepard', 'Foster Moreau', 'Tim Patrick']
[KTC-dyn] top-200 join coverage: 100.0%
[ktc_redraft_bridge] 281/300 rows bridged to dynasty-page playerID by name (93.7%)
[KTC-redraft] 14 unmatched after fallback: ['Joe Mixon', 'Nick Chubb', 'Miles Sanders', 'DeAndre Hopkins', 'Adam Thielen', 'Jermaine Burton', 'Tyler Lockett', 'Hunter Renfrow', 'Austin Ekeler', 'Brandin Cooks', 'Zay Jones', 'Taysom Hill', 'Russell Wilson', 'Raheem Mostert']
[KTC-redraft] top-200 join coverage: 99.5%

[FC-sf_dynasty10] 2 rows matched via normalized-name fallback (documented last resort)
[FC-sf_dynasty10] top-200 join coverage: 100.0%

[FC-sf_dynasty12] 2 rows matched via normalized-name fallback (documented last resort)
[FC-sf_dynasty12] top-200 join coverage: 100.0%
[FC-oneqb_dynasty10] 2 rows matched via normalized-name fallback (documented last resort)
[FC-oneqb_dynasty10] top-200 join coverage: 100.0%

[FC-oneqb_dynasty12] 2 rows matched via normalized-name fallback (documented last resort)

[FC-oneqb_dynasty12] top-200 join coverage: 100.0%
[FC-redraft10] top-200 join coverage: 100.0%

[FC-redraft12] top-200 join coverage: 100.0%
  ('sf_dynasty', 10): 399 players with a consensus target
  ('sf_dynasty', 12): 399 players with a consensus target
  ('oneqb_dynasty', 10): 399 players with a consensus target
  ('oneqb_dynasty', 12): 399 players with a consensus target
  ('redraft', 10): 171 players with a consensus target
  ('redraft', 12): 171 players with a consensus target

## Stage 7 -- Fit all 6 models

One `HistGradientBoostingRegressor` per format-teamsize combo, trained on `log(consensus_value)`
with `position` as a native categorical feature, validated via 10-fold out-of-fold cross-validated
predictions (not train-set fit metrics). A `RandomForestRegressor` (imputed/encoded) serves as a
comparison baseline. Zero-snap rookies get an auxiliary lower-quantile prediction as their final
value instead of the mean -- a genuine predictive-uncertainty discount, never a neutral risk
multiplier.

**Sample-weighted training.** `HistGradientBoostingRegressor`'s default `min_samples_leaf=20`,
combined with this project's ~379-row training pool, structurally forces the top ~15-20 "elite tier"
players -- in any position, any format -- into leaves blended with lower-value neighbors, since every
leaf must average at least 20 samples. That systematically compresses predictions for the most
valuable assets (first surfaced as superflex elite-QB underprediction -- Josh Allen, Lamar Jackson,
Jayden Daniels were predicted well below their own training target -- then confirmed as a general,
position-agnostic effect across the whole board). The fix: every training row is weighted by its own
percentile rank in that format's `consensus_value` distribution (`weight = 1 + percentile**3`,
purely a function of where a row sits in its own format's target -- no position or format is
special-cased anywhere), combined with a lower `min_samples_leaf` (10). Verified across all 6 formats
with a multi-seed robustness check: this fixes the elite-QB compression as well as an earlier
QB-only board-assembly blend did, *and* also fixes the smaller RB/WR/TE top-of-board compression that
blend never touched, with Spearman/MAE flat-to-improved everywhere -- not a tradeoff against overall
accuracy. See `trade_calculator_pipeline.py`'s module comment above `fit_format_model` for the full
diagnosis, including the two earlier fixes (a QB-only model split, a starter-status feature) that
were tried and honestly ruled out first.

In [ ]:
fit_results = tcp.fit_all_format_models(feature_table, consensus_targets)

validation_rows = []
for (fmt, team_size), res in fit_results.items():
    hm, rm = res["hgb_metrics"], res["rf_metrics"]
    validation_rows.append({
        "format": fmt, "team_size": team_size,
        "hgb_spearman": hm["spearman"], "hgb_mae": hm["mae"], "hgb_top50_mae": hm["top50_mae"],
        "rf_spearman": rm["spearman"], "rf_mae": rm["mae"],
    })
validation_df = pd.DataFrame(validation_rows)
validation_df

[sf_dynasty-10] dropping 2 feature(s) with <2 distinct values in this group: ['breakout_age', 'dominator_rating']

[sf_dynasty-10] rookie quantile discount: 56 rookies in training pool, mean-model vs quantile-model prediction reduced by 2.5% on average
[sf_dynasty-10] n=380  HGBR: spearman=0.824 mae=660 top50_mae=1605  |  RF baseline: spearman=0.833 mae=631 top50_mae=1730
[sf_dynasty-12] dropping 2 feature(s) with <2 distinct values in this group: ['breakout_age', 'dominator_rating']

[sf_dynasty-12] rookie quantile discount: 56 rookies in training pool, mean-model vs quantile-model prediction reduced by 3.1% on average
[sf_dynasty-12] n=380  HGBR: spearman=0.823 mae=658 top50_mae=1590  |  RF baseline: spearman=0.831 mae=639 top50_mae=1755
[oneqb_dynasty-10] dropping 2 feature(s) with <2 distinct values in this group: ['breakout_age', 'dominator_rating']

[oneqb_dynasty-10] rookie quantile discount: 56 rookies in training pool, mean-model vs quantile-model prediction reduced by 4.6% on average
[oneqb_dynasty-10] n=380  HGBR: spearman=0.836 mae=544 top50_mae=1314  |  RF baseline: spearman=0.835 mae=577 top50_mae=1709
[oneqb_dynasty-12] dropping 2 feature(s) with <2 distinct values in this group: ['breakout_age', 'dominator_rating']

[oneqb_dynasty-12] rookie quantile discount: 56 rookies in training pool, mean-model vs quantile-model prediction reduced by 6.2% on average
[oneqb_dynasty-12] n=380  HGBR: spearman=0.828 mae=557 top50_mae=1370  |  RF baseline: spearman=0.834 mae=575 top50_mae=1709
[redraft-10] dropping 2 feature(s) with <2 distinct values in this group: ['breakout_age', 'dominator_rating']

[redraft-10] rookie quantile discount: 13 rookies in training pool, mean-model vs quantile-model prediction reduced by 11.4% on average
[redraft-10] n=169  HGBR: spearman=0.751 mae=915 top50_mae=1712  |  RF baseline: spearman=0.763 mae=991 top50_mae=1983
[redraft-12] dropping 2 feature(s) with <2 distinct values in this group: ['breakout_age', 'dominator_rating']

[redraft-12] rookie quantile discount: 13 rookies in training pool, mean-model vs quantile-model prediction reduced by 14.6% on average
[redraft-12] n=169  HGBR: spearman=0.752 mae=908 top50_mae=1656  |  RF baseline: spearman=0.760 mae=994 top50_mae=1957

          format  team_size  hgb_spearman     hgb_mae  hgb_top50_mae  rf_spearman      rf_mae
0     sf_dynasty         10      0.823642  660.146610    1604.945051     0.832779  630.737997
1     sf_dynasty         12      0.822548  657.691022    1589.671815     0.831399  638.884803
2  oneqb_dynasty         10      0.836388  544.228060    1313.753733     0.835340  576.505584
3  oneqb_dynasty         12      0.828104  557.285482    1370.222670     0.833904  575.476279
4        redraft         10      0.750902  915.111652    1711.978995     0.763182  990.620102
5        redraft         12      0.751875  908.487251    1656.231438     0.760382  993.990372

## Stage 8 -- Board assembly

Every player the model produced a final prediction for, plus (dynasty formats only) the 27 pick
assets, all on the same `model_value` scale -- the trade-calculator itself: any two assets, player
or pick, are now directly comparable.

In [ ]:
boards = tcp.build_all_boards(feature_table, crosswalk, consensus_targets, pick_universe, fit_results)
for (fmt, team_size), board in boards.items():
    n_players = (board["asset_type"] == "player").sum()
    n_picks = (board["asset_type"] == "pick").sum()
    print(f"  {fmt}-{team_size}: {len(board)} rows ({n_players} players, {n_picks} picks)")

  sf_dynasty-10: 407 rows (380 players, 27 picks)
  sf_dynasty-12: 407 rows (380 players, 27 picks)
  oneqb_dynasty-10: 407 rows (380 players, 27 picks)
  oneqb_dynasty-12: 407 rows (380 players, 27 picks)
  redraft-10: 169 rows (169 players, 0 picks)
  redraft-12: 169 rows (169 players, 0 picks)

### Top 15, SF dynasty (12-team) -- eye-test sanity check

Should be recognizable star players, maybe a high pick mixed in near the very top -- **not** a
bottom-tier pick outranking Bijan Robinson.

In [ ]:
boards[("sf_dynasty", 12)][["board_rank", "name", "position", "asset_type", "model_value", "consensus_value"]].head(15)

    board_rank                name position asset_type   model_value  consensus_value
0            1        Jahmyr Gibbs       RB     player  10360.832614     10214.317293
1            2      Bijan Robinson       RB     player  10167.173204     10373.074617
2            3       Ja'Marr Chase       WR     player  10166.628076     10128.533254
3            4          Josh Allen       QB     player   9686.623359     10204.738734
4            5  Jaxon Smith-Njigba       WR     player   8884.012524      9021.000136
5            6          Drake Maye       QB     player   8726.869730      8637.601712
6            7          Puka Nacua       WR     player   8340.308640      8388.615548
7            8        Brock Bowers       TE     player   7872.213374      7836.049246
8            9   Amon-Ra St. Brown       WR     player   7371.649480      7287.962937
9           10      Caleb Williams       QB     player   7299.233430      7245.616469
10          11       Ashton Jeanty       RB     player   7173.137715      7252.831164
11          12       Lamar Jackson       QB     player   7068.462510      7279.182592
12          13          Joe Burrow       QB     player   6941.325489      6993.497849
13          14        Malik Nabers       WR     player   6918.171552      6868.493814
14          15    Justin Jefferson       WR     player   6901.231684      6989.507328

## Top 200 -- every board

The full trade-calculator board for each of the 6 format-teamsize combos.

### Superflex Dynasty -- 10 team -- Top 200

In [ ]:
boards[("sf_dynasty", 10)][
    ["board_rank", "name", "position", "asset_type", "model_value", "consensus_value", "current_age"]
].head(200)

     board_rank                    name position asset_type   model_value  consensus_value  current_age
0             1            Jahmyr Gibbs       RB     player  10516.887564     10385.258897         24.0
1             2          Bijan Robinson       RB     player  10243.481059     10471.491685         24.0
2             3           Ja'Marr Chase       WR     player  10003.743141     10047.748288         26.0
3             4              Josh Allen       QB     player   9769.384532      9915.415205         30.0
4             5      Jaxon Smith-Njigba       WR     player   8737.508926      8945.469040         24.0
5             6              Drake Maye       QB     player   8423.947820      8415.034589         24.0
6             7              Puka Nacua       WR     player   8249.336056      8276.853425         25.0
7             8            Brock Bowers       TE     player   7847.238734      7790.738424         23.0
8             9           Ashton Jeanty       RB     player   7280.301733      7296.959469         22.0
9            10       Amon-Ra St. Brown       WR     player   7269.614423      7293.162663         26.0
10           11          Caleb Williams       QB     player   7086.340628      7083.685814         24.0
11           12           Lamar Jackson       QB     player   6970.552086      7089.807195         29.0
12           13              Joe Burrow       QB     player   6815.252752      6813.512009         29.0
13           14        Justin Jefferson       WR     player   6804.387440      6879.703335         27.0
14           15            Malik Nabers       WR     player   6785.971005      6822.558426         23.0
15           16          Jayden Daniels       QB     player   6763.390558      6834.000000         25.0
16           17             CeeDee Lamb       WR     player   6458.648748      6476.370685         27.0
17           18            Trey McBride       TE     player   6268.708612      6492.121267         26.0
18           19          Justin Herbert       QB     player   5976.223425      5884.489600         28.0
19           20           De'Von Achane       RB     player   5954.706423      5916.096837         24.0
20           21         Omarion Hampton       RB     player   5905.588080      5947.704074         23.0
21           22            Drake London       WR     player   5818.094606      5853.661134         25.0
22           23        Colston Loveland       TE     player   5443.714801      5375.805921         22.0
23           24         Jonathan Taylor       RB     player   5401.392863      5381.191187         27.0
24           25    2027 Round 1 (Early)     PICK       pick   5397.250000      5397.250000          NaN
25           26       Tetairoa McMillan       WR     player   5334.465910      5103.365342         23.0
26           27         Patrick Mahomes       QB     player   5234.523691      5206.236293         30.0
27           28              James Cook       RB     player   5228.700283      5219.279341         26.0
28           29             Jalen Hurts       QB     player   5213.967660      5106.697233         28.0
29           30          George Pickens       WR     player   4960.953623      4871.202108         25.0
30           31         Trevor Lawrence       QB     player   4927.631058      5003.076563         26.0
31           32            Tyler Warren       TE     player   4920.441995      4832.441901         24.0
32           33                  Bo Nix       QB     player   4857.373382      4814.167329         26.0
33           34            Emeka Egbuka       WR     player   4830.541161      4853.114662         23.0
34           35             Jaxson Dart       QB     player   4654.711682      4835.634754         23.0
35           36      Kenneth Walker III       RB     player   4477.167226      4453.167573         25.0
36           37            Nico Collins       WR     player   4351.354074      4337.387670         27.0
37           38     Christian McCaffrey       RB     player   4347.601047      4292.376693         30.0
38           39             Brock Purdy       QB     player   4329.525646      4453.854687         26.0
39           40             Chase Brown       RB     player   4282.234836      4357.432089         26.0
40           41          Jeremiyah Love       RB     player   4108.090765      6862.282773         21.0
41           42          Garrett Wilson       WR     player   4099.559752      4130.453519         26.0
42           43            Carnell Tate       WR     player   4022.000271      4517.638527         21.0
43           44             Breece Hall       RB     player   3985.156447      3839.997196         25.0
44           45             Zay Flowers       WR     player   3979.170170      3916.695342         25.0
45           46             Jordan Love       QB     player   3975.804789      4104.054071         27.0
46           47           Ladd McConkey       WR     player   3910.395351      3940.835637         24.0
47           48          Saquon Barkley       RB     player   3907.722251      3937.389263         29.0
48           49            Dak Prescott       QB     player   3902.426000      3913.848338         33.0
49           50            Jordyn Tyson       WR     player   3900.960441      3889.012911         22.0
50           51    2028 Round 1 (Early)     PICK       pick   3893.120710      3893.120710          NaN
51           52      2027 Round 1 (Mid)     PICK       pick   3869.750000      3869.750000          NaN
52           53           DeVonta Smith       WR     player   3808.563516      3838.927783         27.0
53           54             Chris Olave       WR     player   3756.086016      4353.991390         26.0
54           55              A.J. Brown       WR     player   3753.248863      3796.047887         29.0
55           56           Luther Burden       WR     player   3752.385782      3839.880968         22.0
56           57        Quinshon Judkins       RB     player   3642.435429      3840.243896         22.0
57           58             Rome Odunze       WR     player   3633.648854      3720.000000         24.0
58           59                Cam Ward       QB     player   3503.754326      3829.788276         24.0
59           60          Kyren Williams       RB     player   3489.305907      3424.113658         26.0
60           61        Fernando Mendoza       QB     player   3485.351349      3955.688425         22.0
61           62              Jared Goff       QB     player   3460.081922      3374.866208         31.0
62           63             Rashee Rice       WR     player   3441.927176      3467.745148         26.0
63           64            Tyler Shough       QB     player   3422.695027      3373.316491         26.0
64           65      TreVeyon Henderson       RB     player   3420.411876      3438.318865         23.0
65           66             Tee Higgins       WR     player   3394.736519      3377.863055         27.0
66           67           Harold Fannin       TE     player   3387.755543      3245.237393         22.0
67           68             C.J. Stroud       QB     player   3375.094151      3198.929494         24.0
68           69            Tucker Kraft       TE     player   3370.395789      3385.058160         25.0
69           70            Cam Skattebo       RB     player   3343.700417      3376.752061         24.0
70           71           Jaylen Waddle       WR     player   3304.212472      3367.675766         27.0
71           72          Baker Mayfield       QB     player   3297.428205      3220.584780         31.0
72           73     2027 Round 1 (Late)     PICK       pick   3237.100000      3237.100000          NaN
73           74     Marvin Harrison Jr.       WR     player   3196.771737      3151.350998         24.0
74           75        Javonte Williams       RB     player   3180.343830      3137.958010         26.0
75           76        Brian Thomas Jr.       WR     player   3147.399295      3150.586398         23.0
76           77            Bucky Irving       RB     player   3094.633459      3137.415609         24.0
77           78             Makai Lemon       WR     player   3083.062587      3250.920597         22.0
78           79             Sam LaPorta       TE     player   3075.872218      3147.670000         25.0
79           80        Jameson Williams       WR     player   3022.425666      3064.576687         25.0
80           81             Josh Jacobs       RB     player   3006.766864      3006.864908         28.0
81           82      2028 Round 1 (Mid)     PICK       pick   2967.847536      2967.847536          NaN
82           83              Kyle Pitts       TE     player   2957.298264      3054.499731         25.0
83           84    2029 Round 1 (Early)     PICK       pick   2918.695171      2918.695171          NaN
84           85             Sam Darnold       QB     player   2860.154791      3039.761370         29.0
85           86          Jadarian Price       RB     player   2840.853147      3327.190760         22.0
86           87           KC Concepcion       WR     player   2774.430513      2766.484204         21.0
87           88            Kenyon Sadiq       TE     player   2767.586386      2767.104091         21.0
88           89       Parker Washington       WR     player   2756.110172      2768.013403         24.0
89           90          Travis Etienne       RB     player   2742.258533      2766.949119         27.0
90           91            Kyler Murray       QB     player   2741.337692      2766.039806         29.0
91           92        Matthew Stafford       QB     player   2697.965276      2769.852546         38.0
92           93          Bhayshul Tuten       RB     player   2653.013103      2689.687452         23.0
93           94        Christian Watson       WR     player   2585.831028      2630.652243         27.0
94           95            Daniel Jones       QB     player   2534.216931      2599.259941         29.0
95           96           D'Andre Swift       RB     player   2512.648453      2600.789140         27.0
96           97    2027 Round 2 (Early)     PICK       pick   2498.650000      2498.650000          NaN
97           98            Malik Willis       QB     player   2486.893970      2448.929491         27.0
98           99     2028 Round 1 (Late)     PICK       pick   2478.110609      2478.110609          NaN
99          100           Denzel Boston       WR     player   2446.802521      2442.711252         22.0
100         101             Bryce Young       QB     player   2444.845495      2642.986059         25.0
101         102           Derrick Henry       RB     player   2433.777619      3144.937410         32.0
102         103              D.J. Moore       WR     player   2420.351640      2395.758509         29.0
103         104          Jordan Addison       WR     player   2309.982633      2336.361768         24.0
104         105          Michael Wilson       WR     player   2304.370057      2307.000000         26.0
105         106          Terry McLaurin       WR     player   2298.775976      2307.000000         30.0
106         107              DK Metcalf       WR     player   2215.296140      2149.279201         28.0
107         108      2027 Round 2 (Mid)     PICK       pick   2183.000000      2183.000000          NaN
108         109           George Kittle       TE     player   2176.645549      2154.142600         32.0
109         110             Alec Pierce       WR     player   2159.447608      2159.622377         26.0
110         111        David Montgomery       RB     player   2157.554454      2242.319033         29.0
111         112         Jonathon Brooks       RB     player   2151.815640      2114.687671         23.0
112         113    2028 Round 2 (Early)     PICK       pick   2145.608529      2145.608529          NaN
113         114          Matthew Golden       WR     player   2139.621450      2160.435978         23.0
114         115        Quentin Johnston       WR     player   2119.100921      2049.168082         25.0
115         116           Jaylen Warren       RB     player   2091.641415      2058.169080          NaN
116         117               RJ Harvey       RB     player   2089.903034      2030.583612         25.0
117         118         Omar Cooper Jr.       WR     player   2087.982816      1961.252909         22.0
118         119           Davante Adams       WR     player   2061.132515      2100.901152         33.0
119         120              Ty Simpson       QB     player   2014.730869      1964.405393         23.0
120         121           Isaiah Likely       TE     player   1995.678415      2110.890319         26.0
121         122              Josh Downs       WR     player   1964.479868      2063.057454         25.0
122         123     2027 Round 2 (Late)     PICK       pick   1931.800000      1931.800000          NaN
123         124          Jayden Higgins       WR     player   1927.808916      1940.317329         23.0
124         125      2029 Round 1 (Mid)     PICK       pick   1921.944000      1921.944000          NaN
125         126         Michael Pittman       WR     player   1917.249885      1929.149219         28.0
126         127      2028 Round 2 (Mid)     PICK       pick   1902.433271      1902.433271          NaN
127         128          Dalton Kincaid       TE     player   1893.289516      1875.679150         26.0
128         129           Jake Ferguson       TE     player   1881.165566      1868.419610         27.0
129         130             Blake Corum       RB     player   1866.150084      1867.691461         25.0
130         131             Rico Dowdle       RB     player   1840.165478      1810.179296          NaN
131         132             Jayden Reed       WR     player   1837.892938      1870.749752         26.0
132         133           Chuba Hubbard       RB     player   1837.752190      1875.490564         27.0
133         134              Mike Evans       WR     player   1835.322207      1958.042741         33.0
134         135         Zach Charbonnet       RB     player   1817.366323      1788.471310         25.0
135         136           Kyle Monangai       RB     player   1813.885585      1869.272500         24.0
136         137          Oronde Gadsden       TE     player   1813.683834      1803.759536         23.0
137         138       Wan'Dale Robinson       WR     player   1790.152207      1785.645368         25.0
138         139            J.K. Dobbins       RB     player   1737.927646      1754.643614         27.0
139         140     2028 Round 2 (Late)     PICK       pick   1724.787703      1724.787703          NaN
140         141     Rhamondre Stevenson       RB     player   1695.602509      1689.681754         28.0
141         142        Kenneth Gainwell       RB     player   1683.784596      1691.520897         27.0
142         143        Courtland Sutton       WR     player   1674.744943      1691.781839         30.0
143         144  Jacory Croskey-Merritt       RB     player   1672.355962      1750.769322         25.0
144         145           Xavier Worthy       WR     player   1671.583999      1786.719911         23.0
145         146    2027 Round 3 (Early)     PICK       pick   1649.800000      1649.800000          NaN
146         147           J.J. McCarthy       QB     player   1623.450460      1383.251172         23.0
147         148       Terrance Ferguson       TE     player   1609.220659      1594.770084         23.0
148         149           Jonah Coleman       RB     player   1594.237840      1691.094725         23.0
149         150           Rachaad White       RB     player   1588.749643      1554.650822         27.0
150         151         Brenton Strange       TE     player   1586.780317      1675.911397         25.0
151         152            Chris Godwin       WR     player   1574.359651      1593.811770         30.0
152         153           Khalil Shakir       WR     player   1568.736660      1553.457446         26.0
153         154          Tua Tagovailoa       QB     player   1558.102809      1550.713702         28.0
154         155               AJ Barner       TE     player   1557.503853      1565.000000         24.0
155         156             Romeo Doubs       WR     player   1550.771248      1571.805554         26.0
156         157            Mark Andrews       TE     player   1550.567016      1616.986779         31.0
157         158            Jordan Mason       RB     player   1541.637224      1624.948951          NaN
158         159       Chigoziem Okonkwo       TE     player   1534.982782      1554.960765         26.0
159         160           Jakobi Meyers       WR     player   1533.214336      1553.906973          NaN
160         161    2029 Round 2 (Early)     PICK       pick   1530.596890      1530.596890          NaN
161         162      2027 Round 3 (Mid)     PICK       pick   1528.400000      1528.400000          NaN
162         163          Jalen McMillan       WR     player   1527.869766      1550.876640         24.0
163         164            Tony Pollard       RB     player   1518.031774      1565.000000         29.0
164         165            Stefon Diggs       WR     player   1513.409306      1577.091916         32.0
165         166          T.J. Hockenson       TE     player   1492.334496      1452.630347         29.0
166         167          Rashid Shaheed       WR     player   1489.648233      1477.256264          NaN
167         168     2029 Round 1 (Late)     PICK       pick   1479.342650      1479.342650          NaN
168         169            Ja'Kobi Lane       WR     player   1476.886411      1627.909347         22.0
169         170    2028 Round 3 (Early)     PICK       pick   1475.439661      1475.439661          NaN
170         171          Germie Bernard       WR     player   1471.994041      1451.767744         22.0
171         172          Dallas Goedert       TE     player   1466.237722      1452.170562         31.0
172         173          Ricky Pearsall       WR     player   1450.074029      1454.542864         25.0
173         174            Tyrone Tracy       RB     player   1433.233598      1414.426158         26.0
174         175            Travis Kelce       TE     player   1432.681605      1512.738888         36.0
175         176             Jalen Coker       WR     player   1425.048443      1756.936813          NaN
176         177              Tre Harris       WR     player   1419.765373      1412.016130         24.0
177         178        Antonio Williams       WR     player   1413.476623      1626.282144         22.0
178         179             Woody Marks       RB     player   1413.291685      1412.116971         25.0
179         180              Pat Bryant       WR     player   1412.233344      1435.360705         23.0
180         181          Tyler Allgeier       RB     player   1406.499392      1451.356960         26.0
181         182       Michael Penix Jr.       QB     player   1404.215367      1420.048816         26.0
182         183         Shedeur Sanders       QB     player   1399.931603      1574.475433         24.0
183         184     2027 Round 3 (Late)     PICK       pick   1389.400000      1389.400000          NaN
184         185             Tank Bigsby       RB     player   1383.851028      1446.183905         25.0
185         186              Chris Bell       WR     player   1375.128361      1438.629036         22.0
186         187         Chris Rodriguez       RB     player   1372.694983      1375.950782         25.0
187         188      2028 Round 3 (Mid)     PICK       pick   1366.804742      1366.804742          NaN
188         189               Tank Dell       WR     player   1357.607205      1380.045737         26.0
189         190            Deebo Samuel       WR     player   1355.747473      1327.144574         30.0
190         191          Kayshon Boutte       WR     player   1327.520736      1300.383135         24.0

### Superflex Dynasty -- 12 team -- Top 200

In [ ]:
boards[("sf_dynasty", 12)][
    ["board_rank", "name", "position", "asset_type", "model_value", "consensus_value", "current_age"]
].head(200)

     board_rank                    name position asset_type   model_value  consensus_value  current_age
0             1            Jahmyr Gibbs       RB     player  10360.832614     10214.317293         24.0
1             2          Bijan Robinson       RB     player  10167.173204     10373.074617         24.0
2             3           Ja'Marr Chase       WR     player  10166.628076     10128.533254         26.0
3             4              Josh Allen       QB     player   9686.623359     10204.738734         30.0
4             5      Jaxon Smith-Njigba       WR     player   8884.012524      9021.000136         24.0
5             6              Drake Maye       QB     player   8726.869730      8637.601712         24.0
6             7              Puka Nacua       WR     player   8340.308640      8388.615548         25.0
7             8            Brock Bowers       TE     player   7872.213374      7836.049246         23.0
8             9       Amon-Ra St. Brown       WR     player   7371.649480      7287.962937         26.0
9            10          Caleb Williams       QB     player   7299.233430      7245.616469         24.0
10           11           Ashton Jeanty       RB     player   7173.137715      7252.831164         22.0
11           12           Lamar Jackson       QB     player   7068.462510      7279.182592         29.0
12           13              Joe Burrow       QB     player   6941.325489      6993.497849         29.0
13           14            Malik Nabers       WR     player   6918.171552      6868.493814         23.0
14           15        Justin Jefferson       WR     player   6901.231684      6989.507328         27.0
15           16          Jayden Daniels       QB     player   6816.636603      7047.656858         25.0
16           17             CeeDee Lamb       WR     player   6471.960115      6514.370685         27.0
17           18            Trey McBride       TE     player   6442.871705      6530.121267         26.0
18           19          Justin Herbert       QB     player   6314.635576      6286.723038         28.0
19           20           De'Von Achane       RB     player   5956.995573      5886.463596         24.0
20           21         Omarion Hampton       RB     player   5926.517407      5915.113889         23.0
21           22            Drake London       WR     player   5858.396112      5882.937990         25.0
22           23    2027 Round 1 (Early)     PICK       pick   5388.800000      5388.800000          NaN
23           24         Jonathan Taylor       RB     player   5384.762919      5352.737426         27.0
24           25         Patrick Mahomes       QB     player   5334.524003      5354.170914         30.0
25           26             Jalen Hurts       QB     player   5307.629186      5293.366787         28.0
26           27        Colston Loveland       TE     player   5242.430507      5324.924243         22.0
27           28              James Cook       RB     player   5236.381380      5310.494852         26.0
28           29         Trevor Lawrence       QB     player   5199.784065      5272.635180         26.0
29           30       Tetairoa McMillan       WR     player   5173.247670      4998.549122         23.0
30           31          George Pickens       WR     player   4979.378220      4941.681760         25.0
31           32             Jaxson Dart       QB     player   4947.253402      4988.172350         23.0
32           33            Emeka Egbuka       WR     player   4944.388103      4955.071312         23.0
33           34            Tyler Warren       TE     player   4942.763856      4879.765171         24.0
34           35                  Bo Nix       QB     player   4929.977152      4869.802020         26.0
35           36             Brock Purdy       QB     player   4489.546966      4532.687500         26.0
36           37      Kenneth Walker III       RB     player   4488.785480      4482.843305         25.0
37           38     Christian McCaffrey       RB     player   4289.602636      4223.930660         30.0
38           39             Chase Brown       RB     player   4244.931896      4323.096507         26.0
39           40            Nico Collins       WR     player   4212.459581      4246.041617         27.0
40           41             Jordan Love       QB     player   4178.965188      4215.520064         27.0
41           42            Dak Prescott       QB     player   4144.961590      3982.149993         33.0
42           43          Garrett Wilson       WR     player   4108.874932      4148.518682         26.0
43           44             Zay Flowers       WR     player   3997.529716      3934.906426         25.0
44           45           Ladd McConkey       WR     player   3985.306729      3982.923105         24.0
45           46             Breece Hall       RB     player   3966.700662      3863.348826         25.0
46           47            Jordyn Tyson       WR     player   3923.936150      3892.090045         22.0
47           48          Saquon Barkley       RB     player   3911.251266      3963.578914         29.0
48           49    2028 Round 1 (Early)     PICK       pick   3886.987676      3886.987676          NaN
49           50      2027 Round 1 (Mid)     PICK       pick   3863.900000      3863.900000          NaN
50           51           Luther Burden       WR     player   3854.744458      3877.762805         22.0
51           52            Carnell Tate       WR     player   3853.677642      4543.596415         21.0
52           53              A.J. Brown       WR     player   3838.270905      3862.473126         29.0
53           54           DeVonta Smith       WR     player   3772.310798      3862.927783         27.0
54           55             Chris Olave       WR     player   3761.284636      4289.428884         26.0
55           56        Quinshon Judkins       RB     player   3745.894520      3863.271340         22.0
56           57             Rome Odunze       WR     player   3595.323648      3687.214004         24.0
57           58                Cam Ward       QB     player   3538.427859      3876.888852         24.0
58           59          Kyren Williams       RB     player   3519.303013      3452.361552         26.0
59           60             Rashee Rice       WR     player   3518.660406      3510.944703         26.0
60           61              Jared Goff       QB     player   3516.653134      3433.374794         31.0
61           62          Jeremiyah Love       RB     player   3507.593132      6985.516808         21.0
62           63            Tucker Kraft       TE     player   3501.573882      3485.712914         25.0
63           64          Baker Mayfield       QB     player   3488.024410      3304.289531         31.0
64           65            Tyler Shough       QB     player   3454.751698      3473.266287         26.0
65           66           Harold Fannin       TE     player   3429.315363      3286.540419         22.0
66           67      TreVeyon Henderson       RB     player   3427.693093      3448.487260         23.0
67           68             C.J. Stroud       QB     player   3396.659326      3256.916398         24.0
68           69             Tee Higgins       WR     player   3351.123918      3340.406073         27.0
69           70           Jaylen Waddle       WR     player   3348.390862      3338.360119         27.0
70           71        Fernando Mendoza       QB     player   3286.610699      4110.663395         22.0
71           72            Cam Skattebo       RB     player   3248.442418      3339.406178         24.0
72           73     2027 Round 1 (Late)     PICK       pick   3232.550000      3232.550000          NaN
73           74     Marvin Harrison Jr.       WR     player   3231.194463      3210.403801         24.0
74           75        Brian Thomas Jr.       WR     player   3190.684405      3175.157181         23.0
75           76             Makai Lemon       WR     player   3182.192601      3305.129871         22.0
76           77        Javonte Williams       RB     player   3130.672862      3146.979005         26.0
77           78            Bucky Irving       RB     player   3112.342382      3146.707805         24.0
78           79             Sam LaPorta       TE     player   3093.424156      3158.515000         25.0
79           80        Jameson Williams       WR     player   3034.223717      3079.631902         25.0
80           81              Kyle Pitts       TE     player   3015.174790      3072.499731         25.0
81           82      2028 Round 1 (Mid)     PICK       pick   2963.808968      2963.808968          NaN
82           83          Jadarian Price       RB     player   2943.856353      3307.067017         22.0
83           84    2029 Round 1 (Early)     PICK       pick   2910.832307      2910.832307          NaN
84           85             Sam Darnold       QB     player   2889.000066      3034.418634         29.0
85           86             Josh Jacobs       RB     player   2838.828246      2814.210871         28.0
86           87       Parker Washington       WR     player   2783.427555      2791.060315         24.0
87           88          Travis Etienne       RB     player   2776.952158      2778.978288         27.0
88           89           KC Concepcion       WR     player   2776.651750      2784.178918         21.0
89           90            Kenyon Sadiq       TE     player   2775.678560      2781.627652         21.0
90           91            Kyler Murray       QB     player   2761.750980      2793.849805         29.0
91           92        Matthew Stafford       QB     player   2739.989420      2884.609417         38.0
92           93          Bhayshul Tuten       RB     player   2672.438369      2743.916602         23.0
93           94            Daniel Jones       QB     player   2633.850693      2634.819723         29.0
94           95             Bryce Young       QB     player   2626.685623      2751.839037         25.0
95           96        Christian Watson       WR     player   2598.061203      2618.125017         27.0
96           97            Malik Willis       QB     player   2580.727743      2571.729589         27.0
97           98           D'Andre Swift       RB     player   2526.131224      2608.916898         27.0
98           99           Derrick Henry       RB     player   2524.081589      3132.448125         32.0
99          100    2027 Round 2 (Early)     PICK       pick   2495.400000      2495.400000          NaN
100         101     2028 Round 1 (Late)     PICK       pick   2475.002076      2475.002076          NaN
101         102           Denzel Boston       WR     player   2448.911721      2447.533623         22.0
102         103              D.J. Moore       WR     player   2435.765234      2403.331811         29.0
103         104          Jordan Addison       WR     player   2385.706059      2378.608141         24.0
104         105          Michael Wilson       WR     player   2352.587250      2361.692453         26.0
105         106          Terry McLaurin       WR     player   2331.189111      2335.431739         30.0
106         107         Omar Cooper Jr.       WR     player   2255.462890      1970.450582         22.0
107         108        David Montgomery       RB     player   2201.594276      2255.319033         29.0
108         109           George Kittle       TE     player   2196.168844      2134.046935         32.0
109         110      2027 Round 2 (Mid)     PICK       pick   2180.400000      2180.400000          NaN
110         111             Alec Pierce       WR     player   2163.608945      2148.659672         26.0
111         112          Matthew Golden       WR     player   2158.710344      2187.073954         23.0
112         113         Jonathon Brooks       RB     player   2157.264808      2095.477036         23.0
113         114              DK Metcalf       WR     player   2151.830305      2161.677293         28.0
114         115    2028 Round 2 (Early)     PICK       pick   2143.216971      2143.216971          NaN
115         116           Jaylen Warren       RB     player   2108.637900      2062.896125          NaN
116         117        Quentin Johnston       WR     player   2100.753802      2063.113195         25.0
117         118              Ty Simpson       QB     player   2097.028016      1974.917510         23.0
118         119           Davante Adams       WR     player   2092.332324      2085.681322         33.0
119         120              Josh Downs       WR     player   2005.796569      2084.301965         25.0
120         121          Jayden Higgins       WR     player   1937.888738      1949.588246         23.0
121         122     2027 Round 2 (Late)     PICK       pick   1929.200000      1929.200000          NaN
122         123             Rico Dowdle       RB     player   1923.873784      1813.576017          NaN
123         124      2029 Round 1 (Mid)     PICK       pick   1916.766350      1916.766350          NaN
124         125               RJ Harvey       RB     player   1905.048686      1986.906299         25.0
125         126      2028 Round 2 (Mid)     PICK       pick   1900.451316      1900.451316          NaN
126         127           Jake Ferguson       TE     player   1883.142221      1879.419610         27.0
127         128         Michael Pittman       WR     player   1882.677236      1886.828992         28.0
128         129             Blake Corum       RB     player   1881.773475      1874.834363         25.0
129         130          Dalton Kincaid       TE     player   1870.163725      1886.679150         26.0
130         131           Chuba Hubbard       RB     player   1855.217575      1886.490564         27.0
131         132           Isaiah Likely       TE     player   1852.861215      2107.028373         26.0
132         133          Oronde Gadsden       TE     player   1826.431978      1844.632437         23.0
133         134             Jayden Reed       WR     player   1824.814961      1884.991606         26.0
134         135       Wan'Dale Robinson       WR     player   1815.101130      1813.945766         25.0
135         136         Zach Charbonnet       RB     player   1808.850640      1778.581084         25.0
136         137           Kyle Monangai       RB     player   1777.374116      1868.274566         24.0
137         138     2028 Round 2 (Late)     PICK       pick   1723.080467      1723.080467          NaN
138         139              Mike Evans       WR     player   1704.226230      1947.983034         33.0
139         140            J.K. Dobbins       RB     player   1699.181966      1728.727062         27.0
140         141     Rhamondre Stevenson       RB     player   1679.872395      1684.516692         28.0
141         142        Courtland Sutton       WR     player   1678.717728      1691.791355         30.0
142         143           Xavier Worthy       WR     player   1654.841152      1805.591593         23.0
143         144    2027 Round 3 (Early)     PICK       pick   1647.850000      1647.850000          NaN
144         145           Jonah Coleman       RB     player   1639.555879      1684.898991         23.0
145         146       Terrance Ferguson       TE     player   1628.659476      1626.803112         23.0
146         147        Kenneth Gainwell       RB     player   1624.670714      1684.139521         27.0
147         148               AJ Barner       TE     player   1622.353892      1575.000000         24.0
148         149  Jacory Croskey-Merritt       RB     player   1615.905227      1720.228301         25.0
149         150           Rachaad White       RB     player   1592.975460      1560.000000         27.0
150         151            Chris Godwin       WR     player   1583.443912      1605.730071         30.0
151         152       Chigoziem Okonkwo       TE     player   1583.243739      1562.665687         26.0
152         153          Tua Tagovailoa       QB     player   1581.887680      1563.504596         28.0
153         154           Khalil Shakir       WR     player   1580.629141      1561.402558         26.0
154         155         Shedeur Sanders       QB     player   1576.682282      1645.399999         24.0
155         156           J.J. McCarthy       QB     player   1572.399451      1422.057674         23.0
156         157         Brenton Strange       TE     player   1553.088246      1673.843473         25.0
157         158             Romeo Doubs       WR     player   1541.558797      1575.000000         26.0
158         159            Jordan Mason       RB     player   1539.165840      1576.192745          NaN
159         160          Germie Bernard       WR     player   1532.101248      1460.767744         22.0
160         161          Dallas Goedert       TE     player   1532.040493      1461.170562         31.0
161         162            Tony Pollard       RB     player   1530.807836      1567.000000         29.0
162         163    2029 Round 2 (Early)     PICK       pick   1526.917570      1526.917570          NaN
163         164      2027 Round 3 (Mid)     PICK       pick   1526.450000      1526.450000          NaN
164         165          Jalen McMillan       WR     player   1523.134918      1558.579898         24.0
165         166            Mark Andrews       TE     player   1519.869247      1636.624442         31.0
166         167            Stefon Diggs       WR     player   1517.528673      1576.425203         32.0
167         168           Jakobi Meyers       WR     player   1510.535434      1560.000000          NaN
168         169          T.J. Hockenson       TE     player   1496.912293      1461.630347         29.0
169         170            Ja'Kobi Lane       WR     player   1487.755911      1646.114966         22.0
170         171          Rashid Shaheed       WR     player   1482.270428      1484.865983          NaN
171         172          Ricky Pearsall       WR     player   1476.808425      1461.320404         25.0
172         173     2029 Round 1 (Late)     PICK       pick   1475.357352      1475.357352          NaN
173         174    2028 Round 3 (Early)     PICK       pick   1473.971472      1473.971472          NaN
174         175              Chris Bell       WR     player   1458.522294      1459.696758         22.0
175         176          Tyler Allgeier       RB     player   1456.886423      1453.690634         26.0
176         177       Michael Penix Jr.       QB     player   1454.091052      1459.890473         26.0
177         178             Woody Marks       RB     player   1447.174417      1422.781239         25.0
178         179              Pat Bryant       WR     player   1446.818466      1453.721410         23.0
179         180              Tre Harris       WR     player   1441.160827      1442.812711         24.0
180         181            Tyrone Tracy       RB     player   1432.264188      1396.834323         26.0
181         182            Travis Kelce       TE     player   1406.844075      1517.000000         36.0
182         183         Chris Rodriguez       RB     player   1405.306103      1375.265969         25.0
183         184             Jalen Coker       WR     player   1388.742825      1777.516800          NaN
184         185     2027 Round 3 (Late)     PICK       pick   1388.100000      1388.100000          NaN
185         186             Tank Bigsby       RB     player   1383.229162      1423.478611         25.0
186         187      2028 Round 3 (Mid)     PICK       pick   1365.498206      1365.498206          NaN
187         188        Antonio Williams       WR     player   1361.266629      1645.921883         22.0
188         189            Deebo Samuel       WR     player   1349.491742      1340.295155         30.0
189         190               Tank Dell       WR     player   1345.399045      1388.369923         26.0
190         191            Isaac TeSlaa       WR     player   1312.306505      1327.427721         24.0

### 1QB Dynasty -- 10 team -- Top 200

In [ ]:
boards[("oneqb_dynasty", 10)][
    ["board_rank", "name", "position", "asset_type", "model_value", "consensus_value", "current_age"]
].head(200)

     board_rank                    name position asset_type   model_value  consensus_value  current_age
0             1            Jahmyr Gibbs       RB     player  11218.069399     11127.789959         24.0
1             2          Bijan Robinson       RB     player  11098.299781     11302.850109         24.0
2             3           Ja'Marr Chase       WR     player  10144.295302      9993.607123         26.0
3             4      Jaxon Smith-Njigba       WR     player   8716.428940      8783.488972         24.0
4             5              Puka Nacua       WR     player   8258.666404      8230.139726         25.0
5             6           Ashton Jeanty       RB     player   7727.755146      7675.337060         22.0
6             7       Amon-Ra St. Brown       WR     player   7293.373581      7265.846961         26.0
7             8            Brock Bowers       TE     player   7187.360409      7187.172426         23.0
8             9        Justin Jefferson       WR     player   6614.880056      6713.637183         27.0
9            10            Malik Nabers       WR     player   6532.657105      6698.953617         23.0
10           11         Omarion Hampton       RB     player   6380.223293      6382.244346         23.0
11           12             CeeDee Lamb       WR     player   6367.559204      6391.988493         27.0
12           13           De'Von Achane       RB     player   6195.279875      6325.213896         24.0
13           14            Trey McBride       TE     player   6175.289071      6281.783032         26.0
14           15            Drake London       WR     player   5844.259566      5811.723363         25.0
15           16         Jonathan Taylor       RB     player   5804.584262      5781.987490         27.0
16           17              James Cook       RB     player   5595.877975      5636.354657         26.0
17           18              Josh Allen       QB     player   5558.708014      5818.997864         30.0
18           19    2027 Round 1 (Early)     PICK       pick   5347.650000      5347.650000          NaN
19           20       Tetairoa McMillan       WR     player   5264.036570      5171.810649         23.0
20           21        Colston Loveland       TE     player   4832.870598      4788.279119         22.0
21           22          George Pickens       WR     player   4770.022634      4788.356605         25.0
22           23            Emeka Egbuka       WR     player   4687.851956      4705.105393         23.0
23           24      Kenneth Walker III       RB     player   4664.585753      4689.874405         25.0
24           25            Tyler Warren       TE     player   4587.292404      4425.394910         24.0
25           26              Drake Maye       QB     player   4535.819927      4511.541755         24.0
26           27     Christian McCaffrey       RB     player   4486.589448      4444.921341         30.0
27           28             Chase Brown       RB     player   4398.265878      4454.361407         26.0
28           29             Breece Hall       RB     player   4213.970516      4063.865364         25.0
29           30            Nico Collins       WR     player   4176.658578      4196.839134         27.0
30           31          Garrett Wilson       WR     player   4034.889594      4068.411927         26.0
31           32          Saquon Barkley       RB     player   4015.044773      4018.782678         29.0
32           33      2027 Round 1 (Mid)     PICK       pick   3994.450000      3994.450000          NaN
33           34             Chris Olave       WR     player   3974.473421      4234.611891         26.0
34           35    2028 Round 1 (Early)     PICK       pick   3953.959580      3953.959580          NaN
35           36           Lamar Jackson       QB     player   3940.232000      4005.881286         29.0
36           37        Quinshon Judkins       RB     player   3912.572968      4024.326844         22.0
37           38           Ladd McConkey       WR     player   3856.701665      3866.238544         24.0
38           39             Zay Flowers       WR     player   3847.445562      3836.387890         25.0
39           40          Caleb Williams       QB     player   3829.002776      3700.363957         24.0
40           41            Jordyn Tyson       WR     player   3806.066089      3799.505395         22.0
41           42            Carnell Tate       WR     player   3780.656857      4516.074676         21.0
42           43           Luther Burden       WR     player   3720.391635      3784.513430         22.0
43           44              A.J. Brown       WR     player   3691.615286      3685.197906         29.0
44           45          Kyren Williams       RB     player   3689.950509      3626.113101         26.0
45           46      TreVeyon Henderson       RB     player   3624.684004      3616.543481         23.0
46           47              Joe Burrow       QB     player   3606.422253      3609.964601         29.0
47           48            Cam Skattebo       RB     player   3586.933841      3607.701578         24.0
48           49             Rome Odunze       WR     player   3576.754452      3593.697455         24.0
49           50          Jayden Daniels       QB     player   3555.306229      3650.258343         25.0
50           51           DeVonta Smith       WR     player   3546.387357      3634.296915         27.0
51           52          Jeremiyah Love       RB     player   3542.278923      7274.719090         21.0
52           53             Rashee Rice       WR     player   3462.706809      3453.158563         26.0
53           54             Tee Higgins       WR     player   3417.933485      3404.270836         27.0
54           55           Jaylen Waddle       WR     player   3372.492262      3385.645860         27.0
55           56        Javonte Williams       RB     player   3354.590233      3372.398831         26.0
56           57     2027 Round 1 (Late)     PICK       pick   3338.600000      3338.600000          NaN
57           58             Makai Lemon       WR     player   3241.537775      3265.402146         22.0
58           59            Tucker Kraft       TE     player   3233.240440      3202.253523         25.0
59           60            Bucky Irving       RB     player   3227.630427      3241.777031         24.0
60           61     Marvin Harrison Jr.       WR     player   3181.003133      3164.401688         24.0
61           62           Harold Fannin       TE     player   3154.997882      3061.845915         22.0
62           63          Justin Herbert       QB     player   3124.167781      3189.482111         28.0
63           64      2028 Round 1 (Mid)     PICK       pick   3103.134034      3103.134034          NaN
64           65        Brian Thomas Jr.       WR     player   3077.976038      3095.690303         23.0
65           66           Derrick Henry       RB     player   3009.471183      3234.422206         32.0
66           67          Jadarian Price       RB     player   2970.839563      3583.741370         22.0
67           68        Jameson Williams       WR     player   2951.336595      2986.117463         25.0
68           69         Patrick Mahomes       QB     player   2950.444991      2891.082256         30.0
69           70             Sam LaPorta       TE     player   2916.498998      2940.554453         25.0
70           71             Jalen Hurts       QB     player   2888.600158      2841.000000         28.0
71           72             Josh Jacobs       RB     player   2831.828491      2869.504960         28.0
72           73          Travis Etienne       RB     player   2818.636180      2841.000000         27.0
73           74    2029 Round 1 (Early)     PICK       pick   2761.437888      2761.437888          NaN
74           75    2027 Round 2 (Early)     PICK       pick   2726.250000      2726.250000          NaN
75           76              Kyle Pitts       TE     player   2718.281757      2737.701074         25.0
76           77           KC Concepcion       WR     player   2711.423598      2710.190948         21.0
77           78           D'Andre Swift       RB     player   2692.420545      2690.685055         27.0
78           79          Bhayshul Tuten       RB     player   2683.795108      2755.936665         23.0
79           80     2028 Round 1 (Late)     PICK       pick   2658.602758      2658.602758          NaN
80           81       Parker Washington       WR     player   2657.079677      2706.000000         24.0
81           82         Trevor Lawrence       QB     player   2645.305641      2664.580404         26.0
82           83             Jaxson Dart       QB     player   2634.543435      2706.000000         23.0
83           84        Christian Watson       WR     player   2555.440261      2549.191485         27.0
84           85            Kenyon Sadiq       TE     player   2548.598430      2553.918741         21.0
85           86                  Bo Nix       QB     player   2539.006784      2565.189330         26.0
86           87      2027 Round 2 (Mid)     PICK       pick   2406.300000      2406.300000          NaN
87           88              D.J. Moore       WR     player   2340.815924      2347.304271         29.0
88           89             Brock Purdy       QB     player   2338.298793      2387.461434         26.0
89           90    2028 Round 2 (Early)     PICK       pick   2332.705517      2332.705517          NaN
90           91           Denzel Boston       WR     player   2299.772776      2302.896529         22.0
91           92          Michael Wilson       WR     player   2253.994630      2262.984759         26.0
92           93          Terry McLaurin       WR     player   2235.866639      2267.977387         30.0
93           94          Jordan Addison       WR     player   2217.892754      2269.199481         24.0
94           95             Jordan Love       QB     player   2212.615889      2213.885127         27.0
95           96            Dak Prescott       QB     player   2207.824256      2177.663150         33.0
96           97     2027 Round 2 (Late)     PICK       pick   2160.150000      2160.150000          NaN
97           98             Alec Pierce       WR     player   2155.681312      2131.593366         26.0
98           99         Jonathon Brooks       RB     player   2118.035710      2212.975815         23.0
99          100               RJ Harvey       RB     player   2104.391874      2085.891073         25.0
100         101        David Montgomery       RB     player   2097.311769      2278.958158         29.0
101         102              DK Metcalf       WR     player   2094.338575      2068.079320         28.0
102         103          Matthew Golden       WR     player   2074.339856      2133.220569         23.0
103         104           Jaylen Warren       RB     player   2071.458754      2143.199217          NaN
104         105        Quentin Johnston       WR     player   2069.381984      2040.949787         25.0
105         106      2028 Round 2 (Mid)     PICK       pick   2065.137653      2065.137653          NaN
106         107           Davante Adams       WR     player   2037.364520      2070.532839         33.0
107         108             Blake Corum       RB     player   2006.798381      1979.124648         25.0
108         109         Omar Cooper Jr.       WR     player   2001.576378      1944.498261         22.0
109         110           George Kittle       TE     player   1999.115902      1975.078905         32.0
110         111              Josh Downs       WR     player   1998.708271      2066.180917         25.0
111         112           Chuba Hubbard       RB     player   1921.576422      1962.400520         27.0
112         113                Cam Ward       QB     player   1916.166466      2094.047301         24.0
113         114           Kyle Monangai       RB     player   1911.462675      1942.638601         24.0
114         115         Zach Charbonnet       RB     player   1898.841225      1885.360562         25.0
115         116             Rico Dowdle       RB     player   1877.608636      1864.084540          NaN
116         117     2028 Round 2 (Late)     PICK       pick   1864.852201      1864.852201          NaN
117         118          Baker Mayfield       QB     player   1855.129641      1770.573538         31.0
118         119         Michael Pittman       WR     player   1842.894530      1842.573015         28.0
119         120          Jayden Higgins       WR     player   1829.449795      1846.295718         23.0
120         121              Mike Evans       WR     player   1829.332884      1856.158131         33.0
121         122      2029 Round 1 (Mid)     PICK       pick   1818.390983      1818.390983          NaN
122         123           Isaiah Likely       TE     player   1818.378666      1942.700153         26.0
123         124            Tyler Shough       QB     player   1809.319734      1819.451244         26.0
124         125    2027 Round 3 (Early)     PICK       pick   1808.000000      1808.000000          NaN
125         126            J.K. Dobbins       RB     player   1806.692680      1829.812859         27.0
126         127             C.J. Stroud       QB     player   1797.861140      1759.845915         24.0
127         128             Jayden Reed       WR     player   1790.459188      1819.201980         26.0
128         129       Wan'Dale Robinson       WR     player   1772.895861      1764.044199         25.0
129         130          Dalton Kincaid       TE     player   1771.837711      1744.126135         26.0
130         131  Jacory Croskey-Merritt       RB     player   1754.387991      1817.451452         25.0
131         132              Jared Goff       QB     player   1750.693654      1819.054702         31.0
132         133        Kenneth Gainwell       RB     player   1749.522486      1766.678718         27.0
133         134     Rhamondre Stevenson       RB     player   1736.426714      1764.064716         28.0
134         135          Oronde Gadsden       TE     player   1710.401078      1695.971055         23.0
135         136           Rachaad White       RB     player   1667.041717      1644.931866         27.0
136         137            Tony Pollard       RB     player   1657.092978      1650.724933         29.0
137         138      2027 Round 3 (Mid)     PICK       pick   1646.750000      1646.750000          NaN
138         139            Jordan Mason       RB     player   1644.235537      1695.177971          NaN
139         140            Chris Godwin       WR     player   1643.570419      1650.110175         30.0
140         141           Jake Ferguson       TE     player   1641.510291      1696.912395         27.0
141         142           Jonah Coleman       RB     player   1634.547240      1784.030119         23.0
142         143        Courtland Sutton       WR     player   1610.352596      1684.141648         30.0
143         144           Xavier Worthy       WR     player   1597.217129      1750.140869         23.0
144         145    2028 Round 3 (Early)     PICK       pick   1591.300847      1591.300847          NaN
145         146             Sam Darnold       QB     player   1558.386818      1641.048407         29.0
146         147          Germie Bernard       WR     player   1556.333758      1395.961212         22.0
147         148        Fernando Mendoza       QB     player   1554.275697      2192.563131         22.0
148         149           Jakobi Meyers       WR     player   1549.835893      1531.672650          NaN
149         150             Romeo Doubs       WR     player   1536.894874      1557.799873         26.0
150         151     2027 Round 3 (Late)     PICK       pick   1533.700000      1533.700000          NaN
151         152           Khalil Shakir       WR     player   1528.515078      1516.588502         26.0
152         153             Jalen Coker       WR     player   1518.026173      1743.284049          NaN
153         154            Kyler Murray       QB     player   1501.305016      1514.026886         29.0
154         155          Tyler Allgeier       RB     player   1493.426760      1492.256498         26.0
155         156          Jalen McMillan       WR     player   1487.021681      1482.027594         24.0
156         157       Terrance Ferguson       TE     player   1473.729510      1439.678703         23.0
157         158            Stefon Diggs       WR     player   1472.789399      1539.854025         32.0
158         159            Ja'Kobi Lane       WR     player   1471.225633      1567.094602         22.0
159         160               AJ Barner       TE     player   1468.519645      1423.004393         24.0
160         161            Tyrone Tracy       RB     player   1467.233283      1439.572733         26.0
161         162      2028 Round 3 (Mid)     PICK       pick   1460.888066      1460.888066          NaN
162         163             Eli Stowers       TE     player   1457.633809      1819.204545         23.0
163         164        Matthew Stafford       QB     player   1447.543754      1543.295269         38.0
164         165    2029 Round 2 (Early)     PICK       pick   1447.198982      1447.198982          NaN
165         166             Woody Marks       RB     player   1436.640602      1433.695342         25.0
166         167            Mark Andrews       TE     player   1435.853129      1478.306031         31.0
167         168         Brenton Strange       TE     player   1421.803751      1528.740027         25.0
168         169          Ricky Pearsall       WR     player   1416.368530      1419.148702         25.0
169         170            Daniel Jones       QB     player   1412.184876      1361.719604         29.0
170         171              Tre Harris       WR     player   1404.202206      1404.565332         24.0
171         172          Rashid Shaheed       WR     player   1402.690296      1423.306915          NaN
172         173             Bryce Young       QB     player   1401.832420      1429.000000         25.0
173         174     2029 Round 1 (Late)     PICK       pick   1399.636688      1399.636688          NaN
174         175             Tank Bigsby       RB     player   1399.044321      1485.553200         25.0
175         176       Chigoziem Okonkwo       TE     player   1396.772352      1413.751108         26.0
176         177         Chris Rodriguez       RB     player   1391.045003      1405.615622         25.0
177         178              Chris Bell       WR     player   1387.308733      1407.165884         22.0
178         179            Deebo Samuel       WR     player   1384.331109      1307.395533         30.0
179         180              Pat Bryant       WR     player   1384.307584      1393.468239         23.0
180         181     2028 Round 3 (Late)     PICK       pick   1362.621983      1362.621983          NaN
181         182           Dylan Sampson       RB     player   1358.179890      1355.735734         21.0
182         183         Keaton Mitchell       RB     player   1354.266089      1431.877394          NaN
183         184        Antonio Williams       WR     player   1326.602012      1649.539290         22.0
184         185               Tank Dell       WR     player   1316.109409      1315.421847         26.0
185         186            Travis Kelce       TE     player   1315.662376      1395.131949         36.0
186         187            Malik Willis       QB     player   1305.151690      1363.572292         27.0
187         188           Braelon Allen       RB     player   1302.956200      1325.502813         22.0
188         189          T.J. Hockenson       TE     player   1300.770111      1323.616961         29.0
189         190            Tyjae Spears       RB     player   1300.019548      1316.506649         25.0
190         191          Dallas Goedert       TE     player   1287.222382      1358.615806         31.0

### 1QB Dynasty -- 12 team -- Top 200

In [ ]:
boards[("oneqb_dynasty", 12)][
    ["board_rank", "name", "position", "asset_type", "model_value", "consensus_value", "current_age"]
].head(200)

     board_rank                    name position asset_type   model_value  consensus_value  current_age
0             1            Jahmyr Gibbs       RB     player  11167.526411     11011.192293         24.0
1             2          Bijan Robinson       RB     player  10997.875567     11184.307330         24.0
2             3           Ja'Marr Chase       WR     player   9975.500107     10035.315479         26.0
3             4      Jaxon Smith-Njigba       WR     player   8781.732164      8834.612534         24.0
4             5              Puka Nacua       WR     player   8180.895210      8278.514246         25.0
5             6           Ashton Jeanty       RB     player   7528.985883      7595.214824         22.0
6             7       Amon-Ra St. Brown       WR     player   7324.179070      7232.577143         26.0
7             8            Brock Bowers       TE     player   7115.261807      7194.785882         23.0
8             9        Justin Jefferson       WR     player   6676.597652      6753.072305         27.0
9            10            Malik Nabers       WR     player   6589.121942      6738.272511         23.0
10           11             CeeDee Lamb       WR     player   6416.266032      6424.833490         27.0
11           12           De'Von Achane       RB     player   6279.250116      6263.770625         24.0
12           13         Omarion Hampton       RB     player   6214.952924      6267.567431         23.0
13           14            Trey McBride       TE     player   6178.080736      6219.760536         26.0
14           15            Drake London       WR     player   5771.497292      5755.839597         25.0
15           16         Jonathan Taylor       RB     player   5735.594732      5740.935792         27.0
16           17              Josh Allen       QB     player   5667.759336      5784.710275         30.0
17           18              James Cook       RB     player   5588.530866      5650.981711         26.0
18           19    2027 Round 1 (Early)     PICK       pick   5339.200000      5339.200000          NaN
19           20       Tetairoa McMillan       WR     player   5337.046059      5328.786162         23.0
20           21          George Pickens       WR     player   4815.217229      4816.633367         25.0
21           22        Colston Loveland       TE     player   4781.263956      4816.439652         22.0
22           23            Tyler Warren       TE     player   4695.643566      4503.793351         24.0
23           24              Drake Maye       QB     player   4687.155979      4676.692945         24.0
24           25      Kenneth Walker III       RB     player   4684.310321      4647.691197         25.0
25           26     Christian McCaffrey       RB     player   4632.736944      4452.226604         30.0
26           27            Emeka Egbuka       WR     player   4584.262991      4604.643656         23.0
27           28             Chase Brown       RB     player   4460.448739      4495.684185         26.0
28           29          Jeremiyah Love       RB     player   4406.918822      7236.838864         21.0
29           30            Carnell Tate       WR     player   4196.936516      4518.566299         21.0
30           31            Nico Collins       WR     player   4163.089976      4166.791099         27.0
31           32             Breece Hall       RB     player   4149.429836      4087.865364         25.0
32           33          Garrett Wilson       WR     player   4087.364271      4092.411927         26.0
33           34          Caleb Williams       QB     player   4000.006690      3808.432319         24.0
34           35      2027 Round 1 (Mid)     PICK       pick   3989.250000      3989.250000          NaN
35           36           Lamar Jackson       QB     player   3964.433635      4085.540789         29.0
36           37          Saquon Barkley       RB     player   3963.408295      3976.782678         29.0
37           38    2028 Round 1 (Early)     PICK       pick   3948.848718      3948.848718          NaN
38           39             Zay Flowers       WR     player   3937.520103      3838.558101         25.0
39           40             Chris Olave       WR     player   3898.032952      4194.874550         26.0
40           41           Ladd McConkey       WR     player   3843.159576      3847.932687         24.0
41           42            Jordyn Tyson       WR     player   3834.388384      3826.975169         22.0
42           43        Quinshon Judkins       RB     player   3804.960438      3982.326844         22.0
43           44           Luther Burden       WR     player   3765.373303      3809.951260         22.0
44           45          Jayden Daniels       QB     player   3731.021319      3809.574089         25.0
45           46              A.J. Brown       WR     player   3718.124069      3711.418887         29.0
46           47              Joe Burrow       QB     player   3660.444282      3706.629608         29.0
47           48      TreVeyon Henderson       RB     player   3630.764464      3640.600563         23.0
48           49          Kyren Williams       RB     player   3621.437103      3607.008180         26.0
49           50             Rome Odunze       WR     player   3603.728563      3600.964285         24.0
50           51           DeVonta Smith       WR     player   3587.731865      3702.871144         27.0
51           52            Cam Skattebo       RB     player   3583.584370      3560.534081         24.0
52           53             Rashee Rice       WR     player   3490.487833      3460.707267         26.0
53           54           Jaylen Waddle       WR     player   3461.863672      3415.621823         27.0
54           55             Tee Higgins       WR     player   3391.563555      3397.271430         27.0
55           56        Javonte Williams       RB     player   3348.635123      3365.197954         26.0
56           57     2027 Round 1 (Late)     PICK       pick   3334.700000      3334.700000          NaN
57           58          Justin Herbert       QB     player   3252.009267      3222.435617         28.0
58           59             Makai Lemon       WR     player   3221.985737      3230.428009         22.0
59           60            Tucker Kraft       TE     player   3218.992803      3213.522301         25.0
60           61            Bucky Irving       RB     player   3188.573815      3219.253023         24.0
61           62     Marvin Harrison Jr.       WR     player   3178.695866      3155.233111         24.0
62           63           Harold Fannin       TE     player   3171.158605      3105.119928         22.0
63           64        Brian Thomas Jr.       WR     player   3132.524135      3152.947279         23.0
64           65             Jalen Hurts       QB     player   3102.653879      2968.160715         28.0
65           66      2028 Round 1 (Mid)     PICK       pick   3099.768561      3099.768561          NaN
66           67         Patrick Mahomes       QB     player   3016.860615      2988.804906         30.0
67           68           Derrick Henry       RB     player   2928.186014      3217.009164         32.0
68           69             Josh Jacobs       RB     player   2881.888774      2877.003307         28.0
69           70        Jameson Williams       WR     player   2860.251136      2913.211675         25.0
70           71          Travis Etienne       RB     player   2805.455606      2826.498961         27.0
71           72             Sam LaPorta       TE     player   2797.681760      2845.892170         25.0
72           73    2029 Round 1 (Early)     PICK       pick   2753.575024      2753.575024          NaN
73           74             Jaxson Dart       QB     player   2738.037407      2790.772401         23.0
74           75              Kyle Pitts       TE     player   2737.187719      2785.771182         25.0
75           76          Bhayshul Tuten       RB     player   2730.038505      2803.811818         23.0
76           77    2027 Round 2 (Early)     PICK       pick   2723.000000      2723.000000          NaN
77           78         Trevor Lawrence       QB     player   2701.915796      2751.588698         26.0
78           79           KC Concepcion       WR     player   2699.814406      2713.827871         21.0
79           80     2028 Round 1 (Late)     PICK       pick   2656.012314      2656.012314          NaN
80           81       Parker Washington       WR     player   2637.202335      2672.158981         24.0
81           82           D'Andre Swift       RB     player   2615.205405      2618.349522         27.0
82           83                  Bo Nix       QB     player   2583.075368      2612.423218         26.0
83           84        Christian Watson       WR     player   2556.367745      2567.134440         27.0
84           85          Jadarian Price       RB     player   2553.037863      3545.598752         22.0
85           86             Brock Purdy       QB     player   2503.757905      2567.599355         26.0
86           87      2027 Round 2 (Mid)     PICK       pick   2403.700000      2403.700000          NaN
87           88            Kenyon Sadiq       TE     player   2389.459023      2571.722038         21.0
88           89              D.J. Moore       WR     player   2340.660632      2386.450178         29.0
89           90    2028 Round 2 (Early)     PICK       pick   2330.313960      2330.313960          NaN
90           91           Denzel Boston       WR     player   2296.880166      2290.742510         22.0
91           92            Dak Prescott       QB     player   2237.487933      2225.853132         33.0
92           93          Michael Wilson       WR     player   2233.645149      2240.772089         26.0
93           94          Jordan Addison       WR     player   2228.924698      2239.067400         24.0
94           95         Jonathon Brooks       RB     player   2222.942590      2224.788847         23.0
95           96          Terry McLaurin       WR     player   2208.002686      2237.845307         30.0
96           97             Jordan Love       QB     player   2193.132726      2289.944297         27.0
97           98             Alec Pierce       WR     player   2183.260947      2162.910495         26.0
98           99           Jaylen Warren       RB     player   2166.648533      2169.542410          NaN
99          100     2027 Round 2 (Late)     PICK       pick   2158.200000      2158.200000          NaN
100         101          Matthew Golden       WR     player   2126.519198      2163.840325         23.0
101         102        Quentin Johnston       WR     player   2115.399384      2055.264194         25.0
102         103        David Montgomery       RB     player   2110.477314      2265.794511         29.0
103         104              DK Metcalf       WR     player   2093.584540      2093.605423         28.0
104         105      2028 Round 2 (Mid)     PICK       pick   2063.155698      2063.155698          NaN
105         106           Davante Adams       WR     player   2042.576795      2094.479012         33.0
106         107               RJ Harvey       RB     player   2023.242620      2093.837880         25.0
107         108         Omar Cooper Jr.       WR     player   2022.479436      1956.498261         22.0
108         109              Josh Downs       WR     player   1989.863066      2092.791821         25.0
109         110           George Kittle       TE     player   1971.465115      1987.078905         32.0
110         111             Blake Corum       RB     player   1948.433190      1957.428091         25.0
111         112           Kyle Monangai       RB     player   1929.707680      1942.174527         24.0
112         113                Cam Ward       QB     player   1905.907536      2167.559645         24.0
113         114           Chuba Hubbard       RB     player   1904.727599      1944.474696         27.0
114         115          Baker Mayfield       QB     player   1887.334280      1794.177775         31.0
115         116         Zach Charbonnet       RB     player   1879.499771      1861.940939         25.0
116         117             Rico Dowdle       RB     player   1872.070155      1864.804127          NaN
117         118         Michael Pittman       WR     player   1870.598840      1851.959656         28.0
118         119            Tyler Shough       QB     player   1867.284920      1865.140263         26.0
119         120     2028 Round 2 (Late)     PICK       pick   1863.144966      1863.144966          NaN
120         121             Jayden Reed       WR     player   1856.499065      1839.007020         26.0
121         122           Isaiah Likely       TE     player   1842.442229      1970.261055         26.0
122         123              Jared Goff       QB     player   1822.744186      1864.416698         31.0
123         124      2029 Round 1 (Mid)     PICK       pick   1813.213332      1813.213332          NaN
124         125       Wan'Dale Robinson       WR     player   1812.376405      1779.305249         25.0
125         126          Jayden Higgins       WR     player   1811.296257      1855.817690         23.0
126         127    2027 Round 3 (Early)     PICK       pick   1806.050000      1806.050000          NaN
127         128             C.J. Stroud       QB     player   1804.183136      1786.619523         24.0
128         129            J.K. Dobbins       RB     player   1793.979828      1800.951675         27.0
129         130              Mike Evans       WR     player   1786.651841      1863.641840         33.0
130         131     Rhamondre Stevenson       RB     player   1771.514717      1754.345391         28.0
131         132  Jacory Croskey-Merritt       RB     player   1731.656310      1799.588670         25.0
132         133        Kenneth Gainwell       RB     player   1730.504435      1773.516766         27.0
133         134          Oronde Gadsden       TE     player   1714.067435      1716.536882         23.0
134         135          Dalton Kincaid       TE     player   1713.349391      1754.422877         26.0
135         136           Jake Ferguson       TE     player   1712.547232      1724.722453         27.0
136         137           Jonah Coleman       RB     player   1707.403916      1782.379036         23.0
137         138           Rachaad White       RB     player   1673.336789      1624.301749         27.0
138         139            Jordan Mason       RB     player   1662.217099      1694.584487          NaN
139         140            Chris Godwin       WR     player   1656.418572      1660.110175         30.0
140         141            Tony Pollard       RB     player   1646.580372      1660.724933         29.0
141         142        Courtland Sutton       WR     player   1645.553075      1694.695587         30.0
142         143      2027 Round 3 (Mid)     PICK       pick   1645.450000      1645.450000          NaN
143         144           Xavier Worthy       WR     player   1618.426543      1759.628030         23.0
144         145    2028 Round 3 (Early)     PICK       pick   1589.832659      1589.832659          NaN
145         146             Sam Darnold       QB     player   1578.060232      1660.376246         29.0
146         147        Matthew Stafford       QB     player   1567.221754      1631.126320         38.0
147         148            Kyler Murray       QB     player   1539.471691      1550.941558         29.0
148         149           Khalil Shakir       WR     player   1537.871534      1526.426721         26.0
149         150             Romeo Doubs       WR     player   1535.679716      1547.883160         26.0
150         151     2027 Round 3 (Late)     PICK       pick   1532.400000      1532.400000          NaN
151         152             Jalen Coker       WR     player   1515.360552      1752.642025          NaN
152         153           Jakobi Meyers       WR     player   1502.659923      1525.187493          NaN
153         154       Terrance Ferguson       TE     player   1494.054290      1467.327074         23.0
154         155        Fernando Mendoza       QB     player   1467.233034      2229.287592         22.0
155         156               AJ Barner       TE     player   1466.928357      1432.007321         24.0
156         157            Stefon Diggs       WR     player   1463.840318      1548.854025         32.0
157         158          Tyler Allgeier       RB     player   1463.775777      1473.180044         26.0
158         159            Tyrone Tracy       RB     player   1459.959666      1448.627620         26.0
159         160      2028 Round 3 (Mid)     PICK       pick   1459.581530      1459.581530          NaN
160         161         Brenton Strange       TE     player   1458.767544      1501.605448         25.0
161         162          Germie Bernard       WR     player   1456.105786      1404.961212         22.0
162         163          Jalen McMillan       WR     player   1453.995098      1486.752109         24.0
163         164          Rashid Shaheed       WR     player   1448.871596      1437.374307          NaN
164         165             Woody Marks       RB     player   1448.866410      1434.836100         25.0
165         166    2029 Round 2 (Early)     PICK       pick   1443.519663      1443.519663          NaN
166         167             Bryce Young       QB     player   1443.337501      1467.745552         25.0
167         168          Ricky Pearsall       WR     player   1428.755498      1430.340830         25.0
168         169              Tre Harris       WR     player   1415.808544      1413.565332         24.0
169         170            Daniel Jones       QB     player   1413.759349      1387.000443         29.0
170         171         Chris Rodriguez       RB     player   1397.370332      1404.833305         25.0
171         172             Tank Bigsby       RB     player   1396.778547      1479.979434         25.0
172         173     2029 Round 1 (Late)     PICK       pick   1395.651390      1395.651390          NaN
173         174              Pat Bryant       WR     player   1390.540323      1402.189737         23.0
174         175            Ja'Kobi Lane       WR     player   1389.582846      1576.069584         22.0
175         176            Mark Andrews       TE     player   1365.981649      1484.799029         31.0
176         177     2028 Round 3 (Late)     PICK       pick   1361.419599      1361.419599          NaN
177         178       Chigoziem Okonkwo       TE     player   1357.791982      1420.940222         26.0
178         179            Travis Kelce       TE     player   1353.249046      1404.131949         36.0
179         180            Malik Willis       QB     player   1351.618360      1397.875303         27.0
180         181            Deebo Samuel       WR     player   1348.359470      1314.076823         30.0
181         182              Chris Bell       WR     player   1341.696176      1415.082942         22.0
182         183           Dylan Sampson       RB     player   1322.244217      1325.424409         21.0
183         184           Braelon Allen       RB     player   1311.941502      1323.626301         22.0
184         185          T.J. Hockenson       TE     player   1309.480966      1334.661157         29.0
185         186            Tyjae Spears       RB     player   1308.433559      1316.133729         25.0
186         187               Tank Dell       WR     player   1306.807155      1319.306696         26.0
187         188         Keaton Mitchell       RB     player   1306.618039      1421.919850          NaN
188         189          Dallas Goedert       TE     player   1294.253245      1368.743064         31.0
189         190         Adonai Mitchell       WR     player   1280.709783      1261.215582         23.0
190         191          Kayshon Boutte       WR     player   1258.298902      1257.000000         24.0

### Redraft -- 10 team -- Top 200

In [ ]:
boards[("redraft", 10)][
    ["board_rank", "name", "position", "asset_type", "model_value", "consensus_value", "current_age"]
].head(200)

     board_rank                    name position asset_type   model_value  consensus_value  current_age
0             1            Jahmyr Gibbs       RB     player  10414.498872     10200.000000         24.0
1             2           Ja'Marr Chase       WR     player  10007.110349      9757.817630         26.0
2             3          Bijan Robinson       RB     player   9823.374040     10056.487548         24.0
3             4              Puka Nacua       WR     player   9382.529765      9436.893633         25.0
4             5      Jaxon Smith-Njigba       WR     player   9167.186509      9321.934016         24.0
5             6       Amon-Ra St. Brown       WR     player   8818.652624      8650.483990         26.0
6             7         Jonathan Taylor       RB     player   8515.584889      8348.486178         27.0
7             8     Christian McCaffrey       RB     player   8386.366439      8217.410706         30.0
8             9             CeeDee Lamb       WR     player   8014.465345      8080.936695         27.0
9            10              James Cook       RB     player   8013.733156      8149.510939         26.0
10           11           Ashton Jeanty       RB     player   8000.025977      8136.355457         22.0
11           12        Justin Jefferson       WR     player   7712.918583      7828.848321         27.0
12           13         Omarion Hampton       RB     player   7632.750205      7661.780375         23.0
13           14           De'Von Achane       RB     player   7580.490013      7512.248006         24.0
14           15            Brock Bowers       TE     player   6898.913297      6694.902292         23.0
15           16            Trey McBride       TE     player   6896.885426      6768.586032         26.0
16           17          Saquon Barkley       RB     player   6527.680252      6664.915399         29.0
17           18      Kenneth Walker III       RB     player   6467.575248      6391.154245         25.0
18           19            Drake London       WR     player   6466.401996      6516.848444         25.0
19           20              Josh Allen       QB     player   6145.695082      6418.861541         30.0
20           21             Chase Brown       RB     player   5929.360348      5987.266061         26.0
21           22          George Pickens       WR     player   5665.680887      5611.355192         25.0
22           23            Malik Nabers       WR     player   5260.884866      5343.119505         23.0
23           24            Nico Collins       WR     player   5212.330846      5295.337525         27.0
24           25              A.J. Brown       WR     player   5205.142852      5307.448626         29.0
25           26             Breece Hall       RB     player   4896.804186      4880.468531         25.0
26           27           Lamar Jackson       QB     player   4812.797325      5093.765601         29.0
27           28           Derrick Henry       RB     player   4708.462760      5123.762749         32.0
28           29          Kyren Williams       RB     player   4546.326708      4513.403775         26.0
29           30             Chris Olave       WR     player   4046.654141      4565.987609         26.0
30           31             Rashee Rice       WR     player   4015.929557      4048.857932         26.0
31           32           DeVonta Smith       WR     player   3998.342683      4062.625199         27.0
32           33              Joe Burrow       QB     player   3807.838637      3856.991162         29.0
33           34            Emeka Egbuka       WR     player   3802.795562      3732.651474         23.0
34           35             Tee Higgins       WR     player   3770.451004      3745.188913         27.0
35           36            Cam Skattebo       RB     player   3768.541951      3746.756093         24.0
36           37       Tetairoa McMillan       WR     player   3767.453552      3731.084294         23.0
37           38        Javonte Williams       RB     player   3748.665763      3799.053910         26.0
38           39             Josh Jacobs       RB     player   3723.020482      3741.388194         28.0
39           40        Quinshon Judkins       RB     player   3715.539760      3787.934671         22.0
40           41        Colston Loveland       TE     player   3635.776705      3915.261348         22.0
41           42          Garrett Wilson       WR     player   3575.581146      3577.581830         26.0
42           43              Drake Maye       QB     player   3497.321486      3403.174253         24.0
43           44           Ladd McConkey       WR     player   3421.234447      3744.738503         24.0
44           45             Zay Flowers       WR     player   3280.637400      3343.383307         25.0
45           46            Tyler Warren       TE     player   3118.328103      2984.057130         24.0
46           47          Travis Etienne       RB     player   3081.280988      2857.231505         27.0
47           48           Jaylen Waddle       WR     player   3042.273847      2956.719237         27.0
48           49      TreVeyon Henderson       RB     player   3019.977862      2955.593516         23.0
49           50            Bucky Irving       RB     player   2977.579979      3026.128072         24.0
50           51          Jayden Daniels       QB     player   2776.783684      2958.004509         25.0
51           52           D'Andre Swift       RB     player   2621.303309      2506.351491         27.0
52           53        David Montgomery       RB     player   2513.017934      2567.104813         29.0
53           54             Jalen Hurts       QB     player   2509.183065      2492.733346         28.0
54           55           Luther Burden       WR     player   2482.416301      2572.641475         22.0
55           56          Caleb Williams       QB     player   2450.115128      2973.213052         24.0
56           57          Justin Herbert       QB     player   2397.320386      2462.987670         28.0
57           58         Trevor Lawrence       QB     player   2229.990395      2182.665154         26.0
58           59             Rome Odunze       WR     player   2186.451185      2224.716190         24.0
59           60           Davante Adams       WR     player   2170.515319      2233.214278         33.0
60           61         Patrick Mahomes       QB     player   2118.153662      2207.728397         30.0
61           62          Terry McLaurin       WR     player   2083.481839      2170.690140         30.0
62           63            Tucker Kraft       TE     player   2051.065021      2153.031775         25.0
63           64        Jameson Williams       WR     player   2016.106312      2229.351511         25.0
64           65             Jaxson Dart       QB     player   1964.273172      2025.702470         23.0
65           66     Marvin Harrison Jr.       WR     player   1962.207854      1911.514538         24.0
66           67              D.J. Moore       WR     player   1729.858094      1755.543093         29.0
67           68           Harold Fannin       TE     player   1719.689830      1863.299064         22.0
68           69                  Bo Nix       QB     player   1673.038792      1456.802028         26.0
69           70        Brian Thomas Jr.       WR     player   1668.120326      1648.755286         23.0
70           71             Sam LaPorta       TE     player   1642.123377      1627.562733         25.0
71           72          Bhayshul Tuten       RB     player   1621.648055      1888.701754         23.0
72           73           Jaylen Warren       RB     player   1595.844807      1627.172024          NaN
73           74              Mike Evans       WR     player   1572.770487      1597.085245         33.0
74           75              Kyle Pitts       TE     player   1546.069628      1482.871907         25.0
75           76              DK Metcalf       WR     player   1493.049070      1460.196786         28.0
76           77        Christian Watson       WR     player   1464.081072      1451.609496         27.0
77           78             Brock Purdy       QB     player   1382.168510      1725.065769         26.0
78           79            Jordyn Tyson       WR     player   1364.613464      1666.091768         22.0
79           80            Dak Prescott       QB     player   1355.876488      1685.301088         33.0
80           81          Jeremiyah Love       RB     player   1302.103048      5609.280334         21.0
81           82               RJ Harvey       RB     player   1211.279536      1190.328048         25.0
82           83           George Kittle       TE     player   1205.834475      1187.553981         32.0
83           84     Rhamondre Stevenson       RB     player   1168.573529      1188.525191         28.0
84           85         Michael Pittman       WR     player   1168.026961      1186.582771         28.0
85           86             Jordan Love       QB     player   1149.224483      1205.747086         27.0
86           87        Matthew Stafford       QB     player   1108.623815      1231.239725         38.0
87           88            Travis Kelce       TE     player   1070.266188      1090.208175         36.0
88           89            J.K. Dobbins       RB     player   1048.565234      1032.491228         27.0
89           90           Chuba Hubbard       RB     player   1046.920596      1304.633317         27.0
90           91             Makai Lemon       WR     player   1022.340711      1191.991341         22.0
91           92       Parker Washington       WR     player   1020.228196      1028.017544         24.0
92           93             Rico Dowdle       RB     player   1017.253768      1009.964912          NaN
93           94             Alec Pierce       WR     player   1013.763706      1045.523504         26.0
94           95          Baker Mayfield       QB     player    984.258369      1044.555837         31.0
95           96              Jared Goff       QB     player    980.513451       820.597636         31.0
96           97            Carnell Tate       WR     player    943.065307      2564.871795         21.0
97           98             Blake Corum       RB     player    904.433007       987.233632         25.0
98           99          Michael Wilson       WR     player    904.166909       890.192982         26.0
99          100            Chris Godwin       WR     player    891.298377       868.112440         30.0
100         101        Courtland Sutton       WR     player    872.317677       867.715127         30.0
101         102        Quentin Johnston       WR     player    832.911402       817.319715         25.0
102         103        Fernando Mendoza       QB     player    809.992320       372.020734         22.0
103         104       Wan'Dale Robinson       WR     player    806.864360       796.677448         25.0
104         105              Josh Downs       WR     player    794.374638       868.925316         25.0
105         106            Stefon Diggs       WR     player    778.222952       719.604363         32.0
106         107             Aaron Jones       RB     player    771.647823       800.509017         31.0
107         108  Jacory Croskey-Merritt       RB     player    756.031766       753.876692         25.0
108         109           Jake Ferguson       TE     player    755.397282       786.656371         27.0
109         110            Tony Pollard       RB     player    746.292373       751.012391         29.0
110         111          Matthew Golden       WR     player    740.238379       714.019906         23.0
111         112          Jordan Addison       WR     player    736.885802       768.301543         24.0
112         113          Dalton Kincaid       TE     player    715.903919       686.400104         26.0
113         114           Kyle Monangai       RB     player    694.238691       720.304094         24.0
114         115        Kenneth Gainwell       RB     player    690.086818       740.761502         27.0
115         116           KC Concepcion       WR     player    688.381638       741.251626         21.0
116         117            Mark Andrews       TE     player    676.177533       703.515458         31.0
117         118             Jayden Reed       WR     player    660.624268       689.038727         26.0
118         119            Deebo Samuel       WR     player    652.237014       627.961477         30.0
119         120           Isaiah Likely       TE     player    638.563078       739.627500         26.0
120         121           Jakobi Meyers       WR     player    636.934637       600.681532          NaN
121         122           Rachaad White       RB     player    631.226960       627.431726         27.0
122         123            Kyler Murray       QB     player    622.557982       535.465260         29.0
123         124            Jordan Mason       RB     player    617.989505       678.475279          NaN
124         125             Romeo Doubs       WR     player    597.544847       613.737456         26.0
125         126            Kenyon Sadiq       TE     player    572.738644       471.438188         21.0
126         127          Jayden Higgins       WR     player    565.601909       598.915695         23.0
127         128             Sam Darnold       QB     player    562.576906       600.240073         29.0
128         129             C.J. Stroud       QB     player    562.214944       531.323151         24.0
129         130           Xavier Worthy       WR     player    562.017068       645.464391         23.0
130         131         Jonathon Brooks       RB     player    547.912658       547.572363         23.0
131         132                Cam Ward       QB     player    516.622094       582.329775         24.0
132         133          Oronde Gadsden       TE     player    516.249438       506.821310         23.0
133         134           Denzel Boston       WR     player    514.350980       560.021838         22.0
134         135          Jadarian Price       RB     player    513.075323      2176.043267         22.0
135         136         Zach Charbonnet       RB     player    483.904855       484.228929         25.0
136         137          Dallas Goedert       TE     player    456.607632       475.057631         31.0
137         138           Khalil Shakir       WR     player    440.736584       448.568780         26.0
138         139          Rashid Shaheed       WR     player    378.833651       389.138572          NaN
139         140            Tyrone Tracy       RB     player    359.483736       354.149460         26.0
140         141            Daniel Jones       QB     player    353.930772       316.042929         29.0
141         142         Omar Cooper Jr.       WR     player    347.837461       312.190590         22.0
142         143         Brenton Strange       TE     player    345.835152       389.800761         25.0
143         144       Chigoziem Okonkwo       TE     player    325.586592       337.861377         26.0
144         145            Hunter Henry       TE     player    304.802627       300.554492         31.0
145         146             Bryce Young       QB     player    302.606487       335.565789         25.0
146         147          Tyler Allgeier       RB     player    299.649931       250.873666         26.0
147         148          T.J. Hockenson       TE     player    269.301428       247.663743         29.0
148         149           Jonah Coleman       RB     player    253.883839       362.186971         23.0
149         150         Chris Rodriguez       RB     player    248.792393       218.735942         25.0
150         151             Woody Marks       RB     player    248.422335       213.701754         25.0
151         152             Jalen Coker       WR     player    245.179873       245.426901          NaN
152         153           Juwan Johnson       TE     player    244.114177       251.668292          NaN
153         154            Tyler Shough       QB     player    197.488628       193.726639         26.0
154         155          Jauan Jennings       WR     player    186.115899       177.448963         29.0
155         156            Alvin Kamara       RB     player    176.081314       161.772758         31.0
156         157           Isiah Pacheco       RB     player    173.343354       162.037633         27.0
157         158            Tyjae Spears       RB     player    170.658593       169.276132         25.0
158         159            Ja'Kobi Lane       WR     player    167.946710       141.047642         22.0
159         160           Dylan Sampson       RB     player    146.661330       134.274752         21.0
160         161        Antonio Williams       WR     player    143.463953        63.356224         22.0
161         162           Aaron Rodgers       QB     player    137.100962        99.324336         42.0
162         163          Brian Robinson       RB     player    131.354082       130.182749         27.0
163         164            Jalen Nailor       WR     player    127.603541       149.421053         27.0
164         165            Malik Willis       QB     player     97.865425       102.989378         27.0
165         166         Keaton Mitchell       RB     player     65.759172        59.812865          NaN
166         167               AJ Barner       TE     player     58.042301        51.590643         24.0
167         168         Jacoby Brissett       QB     player     41.413958        28.789474         33.0
168         169              Tre Tucker       WR     player     34.386500         8.947368         25.0

### Redraft -- 12 team -- Top 200

In [ ]:
boards[("redraft", 12)][
    ["board_rank", "name", "position", "asset_type", "model_value", "consensus_value", "current_age"]
].head(200)

     board_rank                    name position asset_type   model_value  consensus_value  current_age
0             1            Jahmyr Gibbs       RB     player  10389.072402     10093.000000         24.0
1             2           Ja'Marr Chase       WR     player  10170.361082      9766.883164         26.0
2             3          Bijan Robinson       RB     player   9729.714654      9951.196029         24.0
3             4              Puka Nacua       WR     player   9281.202798      9492.122868         25.0
4             5      Jaxon Smith-Njigba       WR     player   9147.055616      9376.516174         24.0
5             6       Amon-Ra St. Brown       WR     player   9104.971168      8931.980820         26.0
6             7         Jonathan Taylor       RB     player   8419.735601      8260.942052         27.0
7             8     Christian McCaffrey       RB     player   8094.800763      8012.616734         30.0
8             9             CeeDee Lamb       WR     player   8080.611975      8036.159367         27.0
9            10              James Cook       RB     player   7975.649358      8074.358443         26.0
10           11           Ashton Jeanty       RB     player   7937.291302      8067.030221         22.0
11           12        Justin Jefferson       WR     player   7681.450040      7851.083875         27.0
12           13           De'Von Achane       RB     player   7625.756839      7540.749908         24.0
13           14         Omarion Hampton       RB     player   7559.052580      7599.813683         23.0
14           15            Trey McBride       TE     player   6869.721531      6698.266194         26.0
15           16            Brock Bowers       TE     player   6679.428517      6625.352758         23.0
16           17          Saquon Barkley       RB     player   6502.522550      6595.658897         29.0
17           18      Kenneth Walker III       RB     player   6401.288702      6324.154245         25.0
18           19            Drake London       WR     player   6295.020717      6449.038850         25.0
19           20              Josh Allen       QB     player   6195.112775      6683.212438         30.0
20           21             Chase Brown       RB     player   5934.219062      5978.310064         26.0
21           22          George Pickens       WR     player   5718.139111      5644.355192         25.0
22           23            Malik Nabers       WR     player   5451.823338      5427.088875         23.0
23           24            Nico Collins       WR     player   5145.871600      5303.794177         27.0
24           25              A.J. Brown       WR     player   5145.556077      5332.290885         29.0
25           26             Breece Hall       RB     player   4938.722995      4909.115569         25.0
26           27           Lamar Jackson       QB     player   4690.768874      5080.737650         29.0
27           28           Derrick Henry       RB     player   4666.774161      4953.301251         32.0
28           29          Kyren Williams       RB     player   4464.442063      4466.531438         26.0
29           30           DeVonta Smith       WR     player   4187.172159      4162.277512         27.0
30           31             Rashee Rice       WR     player   4159.535440      4112.125322         26.0
31           32             Chris Olave       WR     player   4051.553735      4528.326954         26.0
32           33              Joe Burrow       QB     player   3987.161038      4052.875000         29.0
33           34            Emeka Egbuka       WR     player   3801.539216      3741.204433         23.0
34           35            Cam Skattebo       RB     player   3784.917398      3743.190999         24.0
35           36             Tee Higgins       WR     player   3761.204972      3742.970269         27.0
36           37       Tetairoa McMillan       WR     player   3723.385486      3740.983703         23.0
37           38        Colston Loveland       TE     player   3704.429686      3886.852564         22.0
38           39              Drake Maye       QB     player   3693.036217      3592.812416         24.0
39           40             Josh Jacobs       RB     player   3682.686672      3742.434957         28.0
40           41        Javonte Williams       RB     player   3670.959427      3759.944465         26.0
41           42        Quinshon Judkins       RB     player   3570.255441      3690.602564         22.0
42           43           Ladd McConkey       WR     player   3454.585395      3742.906831         24.0
43           44             Zay Flowers       WR     player   3441.326918      3372.440989         25.0
44           45          Garrett Wilson       WR     player   3349.276851      3551.980923         26.0
45           46            Tyler Warren       TE     player   3066.523295      3002.057130         24.0
46           47      TreVeyon Henderson       RB     player   3036.786527      2973.275488         23.0
47           48           Jaylen Waddle       WR     player   3029.282868      2995.958737         27.0
48           49          Travis Etienne       RB     player   3028.437605      2873.797663         27.0
49           50            Bucky Irving       RB     player   3008.992440      2978.212183         24.0
50           51          Jayden Daniels       QB     player   2858.461201      2999.209719         25.0
51           52           D'Andre Swift       RB     player   2634.743371      2492.527870         27.0
52           53          Caleb Williams       QB     player   2610.817625      2991.213052         24.0
53           54           Luther Burden       WR     player   2572.154534      2663.611244         22.0
54           55             Jalen Hurts       QB     player   2476.771331      2500.577782         28.0
55           56        David Montgomery       RB     player   2471.936301      2505.646914         29.0
56           57          Justin Herbert       QB     player   2397.624523      2472.429150         28.0
57           58         Trevor Lawrence       QB     player   2335.886865      2192.795199         26.0
58           59             Rome Odunze       WR     player   2280.067193      2272.893387         24.0
59           60           Davante Adams       WR     player   2275.068339      2288.918354         33.0
60           61         Patrick Mahomes       QB     player   2161.150023      2236.917842         30.0
61           62            Tucker Kraft       TE     player   2154.408043      2197.919550         25.0
62           63          Terry McLaurin       WR     player   2125.953512      2181.179436         30.0
63           64        Jameson Williams       WR     player   2062.103174      2281.634278         25.0
64           65     Marvin Harrison Jr.       WR     player   1984.071637      1915.452828         24.0
65           66             Jaxson Dart       QB     player   1977.340012      2092.619863         23.0
66           67              D.J. Moore       WR     player   1751.076559      1773.411759         29.0
67           68        Brian Thomas Jr.       WR     player   1705.925815      1679.397415         23.0
68           69           Harold Fannin       TE     player   1689.929245      1853.335991         22.0
69           70                  Bo Nix       QB     player   1688.359193      1476.987793         26.0
70           71              Mike Evans       WR     player   1598.418716      1602.738641         33.0
71           72          Bhayshul Tuten       RB     player   1592.804252      1898.473684         23.0
72           73             Sam LaPorta       TE     player   1587.932480      1630.534157         25.0
73           74           Jaylen Warren       RB     player   1585.111259      1610.398131          NaN
74           75            Dak Prescott       QB     player   1552.136457      1741.301088         33.0
75           76              Kyle Pitts       TE     player   1533.357261      1506.886977         25.0
76           77              DK Metcalf       WR     player   1504.152739      1462.258527         28.0
77           78             Brock Purdy       QB     player   1479.565999      1808.439455         26.0
78           79        Christian Watson       WR     player   1412.209422      1446.981229         27.0
79           80            Jordyn Tyson       WR     player   1338.715822      1715.646424         22.0
80           81          Jeremiyah Love       RB     player   1251.258810      5642.280334         21.0
81           82           George Kittle       TE     player   1242.433660      1208.438596         32.0
82           83               RJ Harvey       RB     player   1177.823562      1194.440130         25.0
83           84             Jordan Love       QB     player   1174.883464      1238.310606         27.0
84           85     Rhamondre Stevenson       RB     player   1170.981422      1189.523249         28.0
85           86         Michael Pittman       WR     player   1149.180201      1184.225739         28.0
86           87          Baker Mayfield       QB     player   1102.705608      1121.230069         31.0
87           88           Chuba Hubbard       RB     player   1093.082052      1312.633317         27.0
88           89            J.K. Dobbins       RB     player   1052.744344      1039.112174         27.0
89           90        Matthew Stafford       QB     player   1033.767218      1246.058214         38.0
90           91             Rico Dowdle       RB     player   1016.029090      1007.824561          NaN
91           92            Travis Kelce       TE     player   1012.428028      1097.208175         36.0
92           93       Parker Washington       WR     player    996.277556      1034.502924         24.0
93           94             Alec Pierce       WR     player    985.351829      1030.537787         26.0
94           95             Makai Lemon       WR     player    951.842211      1198.976383         22.0
95           96             Blake Corum       RB     player    941.272297       961.969636         25.0
96           97            Carnell Tate       WR     player    936.627967      2582.840909         21.0
97           98        Courtland Sutton       WR     player    901.942772       873.575635         30.0
98           99              Jared Goff       QB     player    900.193392       820.260806         31.0
99          100          Michael Wilson       WR     player    860.536069       892.204678         26.0
100         101            Chris Godwin       WR     player    851.022439       856.176236         30.0
101         102        Quentin Johnston       WR     player    840.200379       810.455772         25.0
102         103       Wan'Dale Robinson       WR     player    821.746466       796.189977         25.0
103         104             Aaron Jones       RB     player    784.168011       797.892897         31.0
104         105            Tony Pollard       RB     player    762.546531       764.341594         29.0
105         106            Stefon Diggs       WR     player    759.715977       708.726578         32.0
106         107           Jake Ferguson       TE     player    755.164032       766.934589         27.0
107         108           KC Concepcion       WR     player    755.045624       757.834417         21.0
108         109          Jadarian Price       RB     player    744.251147      2123.690682         22.0
109         110          Jordan Addison       WR     player    738.988911       766.417525         24.0
110         111  Jacory Croskey-Merritt       RB     player    737.729299       765.163191         25.0
111         112              Josh Downs       WR     player    730.044379       879.626580         25.0
112         113          Dalton Kincaid       TE     player    727.493500       693.533472         26.0
113         114          Matthew Golden       WR     player    727.282819       709.038001         23.0
114         115            Mark Andrews       TE     player    707.837523       708.001472         31.0
115         116        Kenneth Gainwell       RB     player    699.053365       757.507668         27.0
116         117           Isaiah Likely       TE     player    673.279295       756.329499         26.0
117         118             Jayden Reed       WR     player    663.687699       697.096818         26.0
118         119           Kyle Monangai       RB     player    659.661086       708.157895         24.0
119         120            Jordan Mason       RB     player    644.321496       684.400319          NaN
120         121            Deebo Samuel       WR     player    639.071841       621.961477         30.0
121         122        Fernando Mendoza       QB     player    634.832272       375.020734         22.0
122         123           Jakobi Meyers       WR     player    628.697323       594.681532          NaN
123         124            Kyler Murray       QB     player    619.658757       539.465260         29.0
124         125             Romeo Doubs       WR     player    607.943403       607.737456         26.0
125         126           Rachaad White       RB     player    605.751569       605.922954         27.0
126         127          Jayden Higgins       WR     player    577.548227       592.915695         23.0
127         128             C.J. Stroud       QB     player    563.284925       533.315513         24.0
128         129             Sam Darnold       QB     player    557.981067       594.240073         29.0
129         130           Xavier Worthy       WR     player    553.353386       649.464391         23.0
130         131         Jonathon Brooks       RB     player    543.573795       551.572363         23.0
131         132           Denzel Boston       WR     player    515.806345       564.021838         22.0
132         133          Oronde Gadsden       TE     player    514.811054       508.567395         23.0
133         134         Zach Charbonnet       RB     player    493.600592       491.622500         25.0
134         135            Kenyon Sadiq       TE     player    486.926107       481.232732         21.0
135         136                Cam Ward       QB     player    481.546026       582.839406         24.0
136         137          Dallas Goedert       TE     player    472.945603       484.335112         31.0
137         138         Omar Cooper Jr.       WR     player    436.406149       314.190590         22.0
138         139           Khalil Shakir       WR     player    430.116125       445.951969         26.0
139         140            Tyrone Tracy       RB     player    385.125950       357.149460         26.0
140         141            Daniel Jones       QB     player    378.611741       318.042929         29.0
141         142          Rashid Shaheed       WR     player    376.305162       392.138572          NaN
142         143         Brenton Strange       TE     player    362.784281       392.800761         25.0
143         144       Chigoziem Okonkwo       TE     player    318.374647       340.235329         26.0
144         145            Hunter Henry       TE     player    306.811454       302.554492         31.0
145         146             Bryce Young       QB     player    288.234989       337.763158         25.0
146         147          Tyler Allgeier       RB     player    276.979216       252.873666         26.0
147         148          T.J. Hockenson       TE     player    269.509503       249.663743         29.0
148         149         Chris Rodriguez       RB     player    259.470910       225.219073         25.0
149         150             Woody Marks       RB     player    257.549400       214.836257         25.0
150         151             Jalen Coker       WR     player    247.483957       247.426901          NaN
151         152           Juwan Johnson       TE     player    246.072501       253.668292          NaN
152         153           Jonah Coleman       RB     player    238.912238       365.186971         23.0
153         154            Tyler Shough       QB     player    216.426356       202.188627         26.0
154         155          Jauan Jennings       WR     player    193.803400       181.772359         29.0
155         156            Tyjae Spears       RB     player    183.182024       175.276132         25.0
156         157            Alvin Kamara       RB     player    180.538999       165.727355         31.0
157         158           Isiah Pacheco       RB     player    176.049869       166.433689         27.0
158         159            Ja'Kobi Lane       WR     player    163.933128       141.095285         22.0
159         160           Dylan Sampson       RB     player    149.728943       134.547029         21.0
160         161        Antonio Williams       WR     player    148.407755        63.356224         22.0
161         162           Aaron Rodgers       QB     player    135.191275        99.986505         42.0
162         163          Brian Robinson       RB     player    133.483807       131.405635         27.0
163         164            Jalen Nailor       WR     player    126.329636       150.421053         27.0
164         165            Malik Willis       QB     player    100.759573       103.989378         27.0
165         166         Keaton Mitchell       RB     player     65.517852        59.812865          NaN
166         167               AJ Barner       TE     player     58.815068        52.590643         24.0
167         168         Jacoby Brissett       QB     player     43.441163        29.789474         33.0
168         169              Tre Tucker       WR     player     35.069381         8.964912         25.0

## Stage 9 -- Divergence tables

Largest model-vs-consensus gaps, player rows only (picks are priced directly from blended market
data, not model-predicted, so they always show zero residual and carry no signal here). These are
**candidates to investigate** -- fundamentals the model weighs differently than the market
currently prices them -- never a claim that the model is right and the market is wrong.

In [ ]:
divergence_tables = tcp.build_all_divergence_tables(boards)
for (fmt, team_size), div_df in divergence_tables.items():
    print(f"\n=== {fmt} - {team_size} team ===")
    display(div_df)

[divergence] excluding 56 rookie row(s) with college_seasons_found==0 from divergence table (no independent signal until CFBD's quota resets)
[divergence] excluding 56 rookie row(s) with college_seasons_found==0 from divergence table (no independent signal until CFBD's quota resets)
[divergence] excluding 56 rookie row(s) with college_seasons_found==0 from divergence table (no independent signal until CFBD's quota resets)
[divergence] excluding 56 rookie row(s) with college_seasons_found==0 from divergence table (no independent signal until CFBD's quota resets)
[divergence] excluding 13 rookie row(s) with college_seasons_found==0 from divergence table (no independent signal until CFBD's quota resets)
[divergence] excluding 13 rookie row(s) with college_seasons_found==0 from divergence table (no independent signal until CFBD's quota resets)

=== sf_dynasty - 10 team ===

                  name position   model_value  consensus_value    residual  residual_pct
0        J.J. McCarthy       QB   1623.450460      1383.251172  240.199288     17.364835
1    Tetairoa McMillan       WR   5334.465910      5103.365342  231.100568      4.528396
2          C.J. Stroud       QB   3375.094151      3198.929494  176.164657      5.506988
3            Joe Mixon       RB    284.375334       109.736842  174.638492    159.142990
4        Justin Fields       QB    836.631805       679.795734  156.836071     23.071058
5          Breece Hall       RB   3985.156447      3839.997196  145.159251      3.780192
6        Harold Fannin       TE   3387.755543      3245.237393  142.518150      4.391609
7         Jahmyr Gibbs       RB  10516.887564     10385.258897  131.628667      1.267457
8          Jalen Hurts       QB   5213.967660      5106.697233  107.270427      2.100583
9       Justin Herbert       QB   5976.223425      5884.489600   91.733825      1.558909
10      George Pickens       WR   4960.953623      4871.202108   89.751515      1.842492
11        Tyler Warren       TE   4920.441995      4832.441901   88.000094      1.821027
12          Jared Goff       QB   3460.081922      3374.866208   85.215714      2.525010
13      Baker Mayfield       QB   3297.428205      3220.584780   76.843425      2.386008
14        Mason Taylor       TE   1164.143899      1087.987478   76.156421      6.999752
15       Derrick Henry       RB   2433.777619      3144.937410 -711.159791    -22.612844
16         Chris Olave       WR   3756.086016      4353.991390 -597.905375    -13.732351
17         Jalen Coker       WR   1425.048443      1756.936813 -331.888369    -18.890171
18            Cam Ward       QB   3503.754326      3829.788276 -326.033950     -8.513106
19         Gunnar Helm       TE   1212.450060      1458.833459 -246.383399    -16.889070
20      Bijan Robinson       RB  10243.481059     10471.491685 -228.010626     -2.177442
21        Trey McBride       TE   6268.708612      6492.121267 -223.412655     -3.441289
22  Jaxon Smith-Njigba       WR   8737.508926      8945.469040 -207.960114     -2.324754
23         Bryce Young       QB   2444.845495      2642.986059 -198.140565     -7.496845
24    Quinshon Judkins       RB   3642.435429      3840.243896 -197.808467     -5.150935
25         Jaxson Dart       QB   4654.711682      4835.634754 -180.923072     -3.741454
26         Sam Darnold       QB   2860.154791      3039.761370 -179.606579     -5.908575
27     Shedeur Sanders       QB   1399.931603      1574.475433 -174.543829    -11.085840
28        Hunter Henry       TE   1158.396908      1327.299545 -168.902638    -12.725284
29  Anthony Richardson       QB    712.182044       873.074389 -160.892345    -18.428252

=== sf_dynasty - 12 team ===

                 name position   model_value  consensus_value    residual  residual_pct
0           Joe Mixon       RB    314.626718       109.473684  205.153034    187.399406
1      Baker Mayfield       QB   3488.024410      3304.289531  183.734879      5.560496
2   Tetairoa McMillan       WR   5173.247670      4998.549122  174.698548      3.494985
3        Dak Prescott       QB   4144.961590      3982.149993  162.811597      4.088535
4       J.J. McCarthy       QB   1572.399451      1422.057674  150.341777     10.572129
5        Jahmyr Gibbs       RB  10360.832614     10214.317293  146.515320      1.434411
6       Harold Fannin       TE   3429.315363      3286.540419  142.774945      4.344232
7         C.J. Stroud       QB   3396.659326      3256.916398  139.742928      4.290651
8         Rico Dowdle       RB   1923.873784      1813.576017  110.297767      6.081783
9         Breece Hall       RB   3966.700662      3863.348826  103.351837      2.675188
10      Justin Fields       QB    783.608246       682.086545  101.521701     14.883991
11         Drake Maye       QB   8726.869730      8637.601712   89.268018      1.033482
12  Amon-Ra St. Brown       WR   7371.649480      7287.962937   83.686543      1.148284
13         Jared Goff       QB   3516.653134      3433.374794   83.278340      2.425553
14       Keenan Allen       WR    320.860980       238.000000   82.860980     34.815538
15      Derrick Henry       RB   2524.081589      3132.448125 -608.366536    -19.421440
16        Chris Olave       WR   3761.284636      4289.428884 -528.144248    -12.312694
17         Josh Allen       QB   9686.623359     10204.738734 -518.115376     -5.077204
18        Jalen Coker       WR   1388.742825      1777.516800 -388.773974    -21.871747
19           Cam Ward       QB   3538.427859      3876.888852 -338.460994     -8.730222
20      Isaiah Likely       TE   1852.861215      2107.028373 -254.167158    -12.062826
21         Mike Evans       WR   1704.226230      1947.983034 -243.756804    -12.513292
22     Jayden Daniels       QB   6816.636603      7047.656858 -231.020255     -3.277973
23      Lamar Jackson       QB   7068.462510      7279.182592 -210.720081     -2.894832
24     Bijan Robinson       RB  10167.173204     10373.074617 -205.901413     -1.984960
25         Geno Smith       QB   1115.751147      1302.524978 -186.773831    -14.339367
26    Jacoby Brissett       QB   1235.967614      1422.424586 -186.456972    -13.108391
27        Gunnar Helm       TE   1297.404017      1467.833459 -170.429442    -11.610952
28      Xavier Worthy       WR   1654.841152      1805.591593 -150.750441     -8.349089
29        Sam Darnold       QB   2889.000066      3034.418634 -145.418568     -4.792304

=== oneqb_dynasty - 10 team ===

                 name position   model_value  consensus_value    residual  residual_pct
0        Tyler Warren       TE   4587.292404      4425.394910  161.897494      3.658374
1       Ja'Marr Chase       WR  10144.295302      9993.607123  150.688179      1.507846
2         Breece Hall       RB   4213.970516      4063.865364  150.105152      3.693655
3      Caleb Williams       QB   3829.002776      3700.363957  128.638818      3.476383
4       J.J. McCarthy       QB    866.055459       740.435626  125.619833     16.965666
5           Joe Mixon       RB    224.607292       117.691729  106.915563     90.843735
6          DJ Giddens       RB    774.150112       677.827704   96.322408     14.210456
7       Harold Fannin       TE   3154.997882      3061.845915   93.151967      3.042347
8   Tetairoa McMillan       WR   5264.036570      5171.810649   92.225921      1.783242
9        Jahmyr Gibbs       RB  11218.069399     11127.789959   90.279440      0.811297
10     Baker Mayfield       QB   1855.129641      1770.573538   84.556103      4.775634
11       Deebo Samuel       WR   1384.331109      1307.395533   76.935577      5.884644
12  Michael Penix Jr.       QB    923.864405       847.394449   76.469956      9.024128
13     Kyren Williams       RB   3689.950509      3626.113101   63.837408      1.760491
14    Patrick Mahomes       QB   2950.444991      2891.082256   59.362735      2.053305
15         Josh Allen       QB   5558.708014      5818.997864 -260.289851     -4.473104
16        Chris Olave       WR   3974.473421      4234.611891 -260.138469     -6.143148
17        Gunnar Helm       TE   1117.752377      1357.672880 -239.920503    -17.671451
18        Jalen Coker       WR   1518.026173      1743.284049 -225.257876    -12.921467
19      Derrick Henry       RB   3009.471183      3234.422206 -224.951023     -6.954906
20     Bijan Robinson       RB  11098.299781     11302.850109 -204.550328     -1.809723
21   David Montgomery       RB   2097.311769      2278.958158 -181.646389     -7.970589
22           Cam Ward       QB   1916.166466      2094.047301 -177.880835     -8.494595
23       Malik Nabers       WR   6532.657105      6698.953617 -166.296512     -2.482425
24    Shedeur Sanders       QB    692.059251       854.021257 -161.962006    -18.964634
25      Xavier Worthy       WR   1597.217129      1750.140869 -152.923739     -8.737796
26      De'Von Achane       RB   6195.279875      6325.213896 -129.934021     -2.054223
27      Isaiah Likely       TE   1818.378666      1942.700153 -124.321487     -6.399417
28       Hunter Henry       TE   1096.522662      1209.787230 -113.264567     -9.362354
29   Quinshon Judkins       RB   3912.572968      4024.326844 -111.753876     -2.776958

=== oneqb_dynasty - 12 team ===

                   name position   model_value  consensus_value    residual  residual_pct
0          Tyler Warren       TE   4695.643566      4503.793351  191.850215      4.259747
1        Caleb Williams       QB   4000.006690      3808.432319  191.574371      5.030268
2   Christian McCaffrey       RB   4632.736944      4452.226604  180.510341      4.054383
3          Jahmyr Gibbs       RB  11167.526411     11011.192293  156.334118      1.419775
4           Jalen Hurts       QB   3102.653879      2968.160715  134.493164      4.531195
5             Joe Mixon       RB    241.883934       117.383459  124.500475    106.063049
6         J.J. McCarthy       QB    884.961720       768.304902  116.656818     15.183662
7           Zay Flowers       WR   3937.520103      3838.558101   98.962001      2.578104
8        Baker Mayfield       QB   1887.334280      1794.177775   93.156505      5.192156
9     Amon-Ra St. Brown       WR   7324.179070      7232.577143   91.601926      1.266518
10        Harold Fannin       TE   3171.158605      3105.119928   66.038677      2.126767
11         Keenan Allen       WR    303.820248       239.599568   64.220679     26.803337
12          Breece Hall       RB   4149.429836      4087.865364   61.564472      1.506030
13     Quentin Johnston       WR   2115.399384      2055.264194   60.135190      2.925910
14        Justin Fields       QB    468.344667       412.235233   56.109434     13.611023
15          Chris Olave       WR   3898.032952      4194.874550 -296.841598     -7.076293
16        Derrick Henry       RB   2928.186014      3217.009164 -288.823150     -8.978002
17             Cam Ward       QB   1905.907536      2167.559645 -261.652109    -12.071276
18          Jalen Coker       WR   1515.360552      1752.642025 -237.281472    -13.538502
19       Bijan Robinson       RB  10997.875567     11184.307330 -186.431763     -1.666905
20     Quinshon Judkins       RB   3804.960438      3982.326844 -177.366406     -4.453838
21          Gunnar Helm       TE   1200.410061      1365.672880 -165.262820    -12.101201
22      Jacoby Brissett       QB    572.655699       729.721126 -157.065426    -21.524034
23         Hunter Henry       TE   1060.088240      1216.787230 -156.698990    -12.878093
24     David Montgomery       RB   2110.477314      2265.794511 -155.317197     -6.854867
25         Malik Nabers       WR   6589.121942      6738.272511 -149.150568     -2.213484
26        Xavier Worthy       WR   1618.426543      1759.628030 -141.201486     -8.024508
27        Isaiah Likely       TE   1842.442229      1970.261055 -127.818826     -6.487406
28        Lamar Jackson       QB   3964.433635      4085.540789 -121.107153     -2.964287
29         Mark Andrews       TE   1365.981649      1484.799029 -118.817380     -8.002253

=== redraft - 10 team ===

                   name position   model_value  consensus_value    residual  residual_pct
0         Ja'Marr Chase       WR  10007.110349      9757.817630  249.292719      2.554800
1        Travis Etienne       RB   3081.280988      2857.231505  224.049483      7.841489
2                Bo Nix       QB   1673.038792      1456.802028  216.236764     14.843250
3          Jahmyr Gibbs       RB  10414.498872     10200.000000  214.498872      2.102930
4          Brock Bowers       TE   6898.913297      6694.902292  204.011005      3.047259
5   Christian McCaffrey       RB   8386.366439      8217.410706  168.955733      2.056070
6     Amon-Ra St. Brown       WR   8818.652624      8650.483990  168.168634      1.944037
7       Jonathan Taylor       RB   8515.584889      8348.486178  167.098712      2.001545
8            Jared Goff       QB    980.513451       820.597636  159.915815     19.487725
9          Tyler Warren       TE   3118.328103      2984.057130  134.270973      4.499611
10         Trey McBride       TE   6896.885426      6768.586032  128.299394      1.895512
11        D'Andre Swift       RB   2621.303309      2506.351491  114.951818      4.586420
12           Drake Maye       QB   3497.321486      3403.174253   94.147233      2.766453
13         Kyler Murray       QB    622.557982       535.465260   87.092722     16.264869
14        Jaylen Waddle       WR   3042.273847      2956.719237   85.554610      2.893566
15       Caleb Williams       QB   2450.115128      2973.213052 -523.097924    -17.593691
16          Chris Olave       WR   4046.654141      4565.987609 -519.333468    -11.373957
17        Derrick Henry       RB   4708.462760      5123.762749 -415.299989     -8.105371
18          Brock Purdy       QB   1382.168510      1725.065769 -342.897259    -19.877344
19         Dak Prescott       QB   1355.876488      1685.301088 -329.424600    -19.546929
20        Ladd McConkey       WR   3421.234447      3744.738503 -323.504056     -8.638896
21        Lamar Jackson       QB   4812.797325      5093.765601 -280.968276     -5.515925
22     Colston Loveland       TE   3635.776705      3915.261348 -279.484644     -7.138339
23           Josh Allen       QB   6145.695082      6418.861541 -273.166458     -4.255684
24       Bhayshul Tuten       RB   1621.648055      1888.701754 -267.053700    -14.139538
25        Chuba Hubbard       RB   1046.920596      1304.633317 -257.712721    -19.753652
26       Bijan Robinson       RB   9823.374040     10056.487548 -233.113508     -2.318041
27     Jameson Williams       WR   2016.106312      2229.351511 -213.245199     -9.565347
28       Jayden Daniels       QB   2776.783684      2958.004509 -181.220824     -6.126455
29   Jaxon Smith-Njigba       WR   9167.186509      9321.934016 -154.747508     -1.660037

=== redraft - 12 team ===

                   name position   model_value  consensus_value    residual  residual_pct
0         Ja'Marr Chase       WR  10170.361082      9766.883164  403.477918      4.131082
1          Jahmyr Gibbs       RB  10389.072402     10093.000000  296.072402      2.933443
2                Bo Nix       QB   1688.359193      1476.987793  211.371400     14.310978
3     Amon-Ra St. Brown       WR   9104.971168      8931.980820  172.990348      1.936752
4          Trey McBride       TE   6869.721531      6698.266194  171.455336      2.559697
5       Jonathan Taylor       RB   8419.735601      8260.942052  158.793549      1.922221
6        Travis Etienne       RB   3028.437605      2873.797663  154.639942      5.381031
7       Trevor Lawrence       QB   2335.886865      2192.795199  143.091666      6.525537
8         D'Andre Swift       RB   2634.743371      2492.527870  142.215501      5.705673
9            Drake Maye       QB   3693.036217      3592.812416  100.223801      2.789564
10        De'Von Achane       RB   7625.756839      7540.749908   85.006931      1.127301
11  Christian McCaffrey       RB   8094.800763      8012.616734   82.184029      1.025683
12         Kyler Murray       QB    619.658757       539.465260   80.193497     14.865368
13           Jared Goff       QB    900.193392       820.260806   79.932586      9.744777
14   Kenneth Walker III       RB   6401.288702      6324.154245   77.134457      1.219680
15           Josh Allen       QB   6195.112775      6683.212438 -488.099663     -7.303369
16          Chris Olave       WR   4051.553735      4528.326954 -476.773219    -10.528684
17        Lamar Jackson       QB   4690.768874      5080.737650 -389.968776     -7.675436
18       Caleb Williams       QB   2610.817625      2991.213052 -380.395426    -12.717096
19          Brock Purdy       QB   1479.565999      1808.439455 -328.873456    -18.185483
20       Bhayshul Tuten       RB   1592.804252      1898.473684 -305.669432    -16.100799
21        Ladd McConkey       WR   3454.585395      3742.906831 -288.321436     -7.703142
22        Derrick Henry       RB   4666.774161      4953.301251 -286.527090     -5.784568
23   Jaxon Smith-Njigba       WR   9147.055616      9376.516174 -229.460558     -2.447184
24       Bijan Robinson       RB   9729.714654      9951.196029 -221.481375     -2.225676
25        Chuba Hubbard       RB   1093.082052      1312.633317 -219.551265    -16.726016
26     Jameson Williams       WR   2062.103174      2281.634278 -219.531104     -9.621660
27     Matthew Stafford       QB   1033.767218      1246.058214 -212.290995    -17.037005
28           Puka Nacua       WR   9281.202798      9492.122868 -210.920070     -2.222054
29       Garrett Wilson       WR   3349.276851      3551.980923 -202.704071     -5.706789

## Stage 10 -- Sanity panel

~20 fixed, real-world-unambiguous checks (absolute top-N and pairwise orderings), run every
execution, with each player's raw feature values printed alongside any failure so the "why" is
inspectable rather than just a pass/fail flag.

In [ ]:
sanity_results = tcp.run_sanity_panel(boards, feature_table)
sanity_results

!!! SANITY CHECK FAILED !!! Josh Jacobs rank 72 (needed top-60) on ('oneqb_dynasty', 10)
    feature decomposition: position='RB', current_age=np.float64(28.0), career_games=np.float64(105.0), seasons_played=np.float64(7.0), ppg_ppr=np.float64(15.806666666666668), round=np.float64(1.0), pick=np.float64(24.0), dominator_rating=np.float64(nan), speed_score=np.float64(nan)

[sanity_panel] 19 passed, 1 failed, 0 skipped (player not found) of 20 checks

                              check                board  passed                                            detail
0                 Puka Nacua top-10     (sf_dynasty, 12)    True             rank=7 (need <= 10), model_value=8340
1              Bijan Robinson top-5     (sf_dynasty, 12)    True             rank=2 (need <= 5), model_value=10167
2                Jahmyr Gibbs top-8     (sf_dynasty, 12)    True             rank=1 (need <= 8), model_value=10361
3              Ja'Marr Chase top-10     (sf_dynasty, 12)    True            rank=3 (need <= 10), model_value=10167
4           Justin Jefferson top-30     (sf_dynasty, 12)    True            rank=15 (need <= 30), model_value=6901
5          Amon-Ra St. Brown top-15     (sf_dynasty, 12)    True             rank=9 (need <= 15), model_value=7372
6                CeeDee Lamb top-20     (sf_dynasty, 12)    True            rank=17 (need <= 20), model_value=6472
7                 Josh Allen top-20  (oneqb_dynasty, 12)    True            rank=17 (need <= 20), model_value=5668
8              Lamar Jackson top-20     (sf_dynasty, 12)    True            rank=12 (need <= 20), model_value=7068
9               Brock Bowers top-10     (sf_dynasty, 12)    True             rank=8 (need <= 10), model_value=7872
10              Trey McBride top-30     (sf_dynasty, 12)    True            rank=18 (need <= 30), model_value=6443
11            Saquon Barkley top-25        (redraft, 12)    True            rank=17 (need <= 25), model_value=6503
12           Jonathan Taylor top-15        (redraft, 12)    True             rank=7 (need <= 15), model_value=8420
13               Josh Jacobs top-60  (oneqb_dynasty, 10)   False            rank=72 (need <= 60), model_value=2832
14         Brock Bowers > Noah Fant     (sf_dynasty, 12)    True         Brock Bowers rank=8 vs Noah Fant rank=377
15          Josh Allen > Joe Flacco  (oneqb_dynasty, 12)    True         Josh Allen rank=17 vs Joe Flacco rank=367
16  Bijan Robinson > Kenny Gainwell     (sf_dynasty, 12)    True  Bijan Robinson rank=2 vs Kenny Gainwell rank=147
17      Puka Nacua > Xavier Legette     (sf_dynasty, 12)    True      Puka Nacua rank=7 vs Xavier Legette rank=283
18   Ja'Marr Chase > Andrei Iosivas     (sf_dynasty, 12)    True   Ja'Marr Chase rank=3 vs Andrei Iosivas rank=341
19  Jahmyr Gibbs > Devin Singletary     (sf_dynasty, 12)    True  Jahmyr Gibbs rank=1 vs Devin Singletary rank=380

## Stage 11 -- In-season update

`recompute_board(through_week=None, ...)` reproduces the preseason boards unchanged -- this is the
identity case, confirmed exactly equal below. Once the 2026 season is underway, calling
`tcp.recompute_board(through_week=<int>, feature_table, crosswalk, consensus_targets,
pick_universe, fit_results)` blends that many weeks of real partial-season production into the
feature snapshot (empirical-Bayes shrinkage against the prior-season baseline, with a `MIN_GAMES`
guard against small-sample noise) and re-predicts with the already-fitted models -- no retraining
required. Each call snapshots every board to `snapshots/{date}_{format}_{team_size}.csv` for
week-over-week movement tracking.

In [ ]:
preseason_again = tcp.recompute_board(
    None, feature_table, crosswalk, consensus_targets, pick_universe, fit_results, write_snapshot=False
)
import numpy as np
same = np.allclose(
    preseason_again[("sf_dynasty", 12)]["model_value"].sort_index(),
    boards[("sf_dynasty", 12)]["model_value"].sort_index(),
)
print(f"recompute_board(through_week=None) reproduces the original boards exactly: {same}")
assert same

recompute_board(through_week=None) reproduces the original boards exactly: True

---

## Scope, exclusions, and setup

See `README.md` in this directory for full methodology, known exclusions (K/DST/IDP not modeled,
TE premium not modeled, CFBD rookie college-production features degrade gracefully when the
free-tier monthly quota is exhausted), and setup instructions.

**Setup reminder:** this notebook requires a `CFBD_API_KEY` set in a gitignored `.env` file in this
directory (`CFBD_API_KEY=your_key_here`) -- get a free key at
[collegefootballdata.com/key](https://collegefootballdata.com/key). The key is never hardcoded or
printed anywhere in this notebook or in `trade_calculator_pipeline.py`.